```yaml
# KryptoŁowca configuration file
# Located at: C:\Users\kamil\Desktop\KryptoŁowca\config.yaml
# Used by config_manager.py to load settings for exchange, database, AI, trading, and risk management

exchange:
  name: binance
  testnet: true
  api_key: your_api_key
  api_secret: your_api_secret

db:
  db_url: sqlite+aiosqlite:///trading.db

ai:
  threshold_bps: 5.0
  model_types: ["rf", "lstm", "gb"]
  seq_len: 40
  epochs: 30
  batch_size: 64
  model_dir: models

trade:
  lookback_bars: 100
  max_position_size: 1.0
  stop_loss_atr_mult: 2.0
  take_profit_atr_mult: 3.0
  position_size: 0.2
  max_position_risk: 0.02

risk:
  max_position_risk: 0.02
```