function createPresets() {
    return [
        {
            id: "momentum",
            title: qsTr("Momentum Pro"),
            description: qsTr("Zestaw presetów momentum dla rynku krypto – automatyczne balansowanie ryzyka i szybkie przełączanie profili."),
            schedulerEntries: [
                {
                    name: "Momentum Alpha",
                    enabled: true,
                    scheduleCount: 4,
                    timezone: "UTC",
                    nextRun: "2024-05-18T09:00:00Z",
                    notes: qsTr("Aktywne okna 1m/5m z trailing stop"),
                },
                {
                    name: "Momentum Beta",
                    enabled: true,
                    scheduleCount: 2,
                    timezone: "UTC",
                    nextRun: "2024-05-18T10:15:00Z",
                    notes: qsTr("Agregacja multi-venue, target delta 0.3"),
                },
            ],
            exchangeConnections: [
                {
                    exchange: "BINANCE",
                    symbol: "BTC/USDT",
                    venueSymbol: "BTCUSDT",
                    status: qsTr("Demo: połączenie symulacyjne"),
                    offline: false,
                    automationRunning: true,
                    fpsTarget: 120,
                },
                {
                    exchange: "COINBASE",
                    symbol: "ETH/USD",
                    venueSymbol: "ETHUSD",
                    status: qsTr("Demo: monitorowanie danych order book"),
                    offline: false,
                    automationRunning: true,
                    fpsTarget: 90,
                },
            ],
            instrumentDetails: {
                exchange: "BINANCE",
                symbol: "BTC/USDT",
                venueSymbol: "BTCUSDT",
                quoteCurrency: "USDT",
                baseCurrency: "BTC",
                granularity: "PT1M",
            },
            aiConfiguration: {
                policy: "momentum",
                decision_window: "PT15S",
                risk_profile: "growth",
                overrides: [
                    { profile: "intraday", maxDrawdown: 0.04, takeProfit: 0.012 },
                    { profile: "swing", maxDrawdown: 0.06, takeProfit: 0.028 },
                ],
                features: ["ema12", "ema26", "vwap", "macro_feed"],
                modelRevision: "2024.04-momentum",
            },
            portfolioSummary: {
                entryCount: 64,
                minValue: 92500,
                maxValue: 132400,
                latestValue: 129800,
                profileLabel: "Momentum",
                maxDrawdown: 0.083,
                averageDrawdown: 0.031,
                maxLeverage: 2.4,
                averageLeverage: 1.7,
                maxExposureUtilization: 0.82,
                anyBreach: false,
                totalBreaches: 0,
            },
            riskSnapshot: {
                profileLabel: "Momentum",
                currentDrawdown: 0.021,
                maxDailyLoss: 0.055,
                usedLeverage: 1.68,
                generatedAt: "2024-05-18T08:55:12Z",
                exposures: [
                    { code: "XBT_PERP", current: 0.62, max: 0.8, threshold: 0.75, breach: false },
                    { code: "ETH_PERP", current: 0.48, max: 0.7, threshold: 0.65, breach: false },
                    { code: "ALT_BASKET", current: 0.31, max: 0.55, threshold: 0.5, breach: false },
                ],
            },
            riskTimeline: [
                {
                    timestamp: "2024-05-18T08:59:48Z",
                    portfolioValue: 129800,
                    drawdown: 0.021,
                    exposureUtilization: 0.79,
                    leverage: 1.68,
                    breach: false,
                    breachCount: 0,
                    profileLabel: "Momentum",
                    source: "demo",
                    notes: qsTr("Ostatnia próbka po automatycznym odświeżeniu"),
                },
                {
                    timestamp: "2024-05-18T08:55:12Z",
                    portfolioValue: 128450,
                    drawdown: 0.028,
                    exposureUtilization: 0.74,
                    leverage: 1.72,
                    breach: false,
                    breachCount: 0,
                    profileLabel: "Momentum",
                    source: "demo",
                    notes: qsTr("Monitoring wolumenów podczas sesji EU"),
                },
                {
                    timestamp: "2024-05-18T08:47:05Z",
                    portfolioValue: 126980,
                    drawdown: 0.034,
                    exposureUtilization: 0.81,
                    leverage: 1.76,
                    breach: false,
                    breachCount: 0,
                    profileLabel: "Momentum",
                    source: "demo",
                    notes: qsTr("Krótki wzrost ekspozycji na ALT_BASKET"),
                },
                {
                    timestamp: "2024-05-18T08:38:00Z",
                    portfolioValue: 125420,
                    drawdown: 0.039,
                    exposureUtilization: 0.83,
                    leverage: 1.82,
                    breach: false,
                    breachCount: 0,
                    profileLabel: "Momentum",
                    source: "demo",
                    notes: qsTr("Stabilizacja po otwarciu Londynu"),
                },
            ],
            runtimeStatus: {
                connection: qsTr("Demo: połączenie symulacyjne"),
                reduceMotion: false,
                offlineMode: false,
                offlineDaemonStatus: qsTr("Aktywny symulator"),
                automationRunning: true,
                performanceGuard: { fpsTarget: 120, jankThresholdMs: 12.0, maxOverlayCount: 3 },
                riskRefresh: {
                    enabled: true,
                    intervalSeconds: 30,
                    nextRefreshInSeconds: 18,
                    nextRefreshDueAt: "2024-05-18T09:00:18Z",
                    lastUpdateAt: "2024-05-18T08:59:48Z",
                    lastRequestAt: "2024-05-18T08:59:45Z",
                },
            },
            controlState: {
                schedulerRunning: true,
                automationRunning: true,
                offlineMode: false,
                lastActionMessage: qsTr("Tryb demo gotowy"),
                lastActionSuccess: true,
                lastActionAt: "2024-05-18T08:59:30Z",
                lastRiskRefreshAt: "2024-05-18T08:59:48Z",
                nextRiskRefreshDueAt: "2024-05-18T09:00:18Z",
                manualRefreshCount: 2,
            },
            activityLog: [
                {
                    timestamp: "2024-05-18T08:57:30Z",
                    type: "scheduler:start",
                    message: qsTr("Scheduler Momentum Alpha aktywny"),
                    success: true,
                    source: "demo",
                    details: { context: qsTr("Harmonogram główny włączony") },
                },
                {
                    timestamp: "2024-05-18T08:55:12Z",
                    type: "risk:refresh",
                    message: qsTr("Zaktualizowano metryki ryzyka"),
                    success: true,
                    source: "demo",
                    details: { context: qsTr("Nowe dane portfela momentum") },
                },
                {
                    timestamp: "2024-05-18T08:50:00Z",
                    type: "system:init",
                    message: qsTr("Załadowano profil Momentum Pro"),
                    success: true,
                    source: "demo",
                    details: { context: qsTr("Konfiguracja strategii i runtime wczytana.") },
                },
            ],
            openPositions: [
                {
                    id: "MOMENTUM-BTCUSDT",
                    symbol: "BTC/USDT",
                    exchange: "BINANCE",
                    venueSymbol: "BTCUSDT",
                    account: "Momentum-Desk",
                    side: qsTr("Long"),
                    quantity: 0.85,
                    entryPrice: 58520,
                    markPrice: 58980,
                    unrealizedPnl: 391.5,
                    leverage: 3.2,
                    margin: 15500,
                    lastUpdate: "2024-05-18T08:59:48Z",
                },
                {
                    id: "MOMENTUM-ETHUSD",
                    symbol: "ETH/USD",
                    exchange: "COINBASE",
                    venueSymbol: "ETHUSD",
                    account: "Momentum-Desk",
                    side: qsTr("Long"),
                    quantity: 12.4,
                    entryPrice: 3050,
                    markPrice: 3084,
                    unrealizedPnl: 421.6,
                    leverage: 2.1,
                    margin: 18000,
                    lastUpdate: "2024-05-18T08:58:03Z",
                },
            ],
            pendingOrders: [
                {
                    id: "MOM-ORD-001",
                    clientOrderId: "MOM-ALPHA-58950",
                    symbol: "BTC/USDT",
                    exchange: "BINANCE",
                    side: qsTr("Kupno"),
                    type: qsTr("Limit"),
                    quantity: 0.25,
                    filled: 0.1,
                    remaining: 0.15,
                    price: 58950,
                    averagePrice: 58890,
                    status: "PartiallyFilled",
                    timeInForce: "GTC",
                    postOnly: true,
                    reduceOnly: false,
                    createdAt: "2024-05-18T08:58:10Z",
                    updatedAt: "2024-05-18T08:59:30Z",
                    expiresAt: "2024-05-18T09:05:00Z",
                },
                {
                    id: "MOM-ORD-002",
                    clientOrderId: "MOM-BETA-3080",
                    symbol: "ETH/USD",
                    exchange: "COINBASE",
                    side: qsTr("Sprzedaż"),
                    type: qsTr("Stop"),
                    quantity: 4.0,
                    filled: 0.0,
                    remaining: 4.0,
                    price: 3080,
                    averagePrice: 0,
                    status: "Working",
                    timeInForce: "GTC",
                    reduceOnly: true,
                    postOnly: false,
                    createdAt: "2024-05-18T08:54:00Z",
                    updatedAt: "2024-05-18T08:58:42Z",
                    expiresAt: "2024-05-18T09:30:00Z",
                },
            ],
            tradeHistory: [
                {
                    id: "MOM-TR-001",
                    timestamp: "2024-05-18T08:47:05Z",
                    symbol: "BTC/USDT",
                    exchange: "BINANCE",
                    side: qsTr("Kupno"),
                    quantity: 0.50,
                    price: 58240,
                    pnl: 0,
                    fee: 3.4,
                    status: "Filled",
                    orderId: "MOM-ALPHA-58240",
                    notes: qsTr("Wejście po sygnale momentum"),
                },
                {
                    id: "MOM-TR-002",
                    timestamp: "2024-05-18T08:38:00Z",
                    symbol: "BTC/USDT",
                    exchange: "BINANCE",
                    side: qsTr("Kupno"),
                    quantity: 0.35,
                    price: 58380,
                    pnl: 86.4,
                    fee: 2.8,
                    status: "Filled",
                    orderId: "MOM-ALPHA-58380",
                    notes: qsTr("Rozszerzenie pozycji po wybiciu"),
                },
                {
                    id: "MOM-TR-003",
                    timestamp: "2024-05-18T08:22:10Z",
                    symbol: "ETH/USD",
                    exchange: "COINBASE",
                    side: qsTr("Sprzedaż"),
                    quantity: 6.0,
                    price: 3028,
                    pnl: 114.0,
                    fee: 2.1,
                    status: "Filled",
                    orderId: "MOM-BETA-3028",
                    notes: qsTr("Realizacja częściowa zysków"),
                },
            ],
            signalAlerts: [
                {
                    id: "MOM-SIG-001",
                    category: "momentum",
                    symbol: "BTC/USDT",
                    direction: qsTr("Long"),
                    confidence: 0.82,
                    impact: 0.64,
                    message: qsTr("Momentum breakout potwierdzony na 5m"),
                    priority: qsTr("Wysoki"),
                    generatedAt: "2024-05-18T08:58:45Z",
                    expiresAt: "2024-05-18T09:03:45Z",
                    tags: ["breakout", "momentum"],
                },
                {
                    id: "MOM-SIG-002",
                    category: "volatility",
                    symbol: "ETH/USD",
                    direction: qsTr("Long"),
                    confidence: 0.68,
                    impact: 0.52,
                    message: qsTr("Wzrost zmienności – monitoruj trailing stop"),
                    priority: qsTr("Średni"),
                    generatedAt: "2024-05-18T08:53:12Z",
                    expiresAt: "2024-05-18T09:08:12Z",
                    tags: ["volatility", "risk"],
                },
            ],
            licenseStatus: {
                active: true,
                edition: "OEM Demo",
                licenseId: "DEMO-MOMENTUM",
                holderName: "Core Labs QA",
                maintenanceActive: true,
                modules: ["momentum", "portfolio", "scheduler"],
                runtime: ["desktop-shell", "scheduler-engine"],
            },
        },
        {
            id: "hedge",
            title: qsTr("Market Neutral"),
            description: qsTr("Tryb prezentacyjny dla funduszy market-neutral – pokazuje balancing delta i zabezpieczenia krzyżowe."),
            schedulerEntries: [
                {
                    name: "Delta Hedge",
                    enabled: true,
                    scheduleCount: 6,
                    timezone: "Europe/Warsaw",
                    nextRun: "2024-05-18T09:05:00+02:00",
                    notes: qsTr("Rebalans co 10 minut z limitem slippage 2 bps"),
                },
                {
                    name: "Gamma Overlay",
                    enabled: false,
                    scheduleCount: 1,
                    timezone: "Europe/Warsaw",
                    nextRun: "2024-05-18T12:00:00+02:00",
                    notes: qsTr("Opcjonalna noga opcyjna do pokazu"),
                },
            ],
            exchangeConnections: [
                {
                    exchange: "OKX",
                    symbol: "BTC/USDT",
                    venueSymbol: "BTC-USDT-SWAP",
                    status: qsTr("Demo: kanał hedge aktywny"),
                    offline: false,
                    automationRunning: true,
                    fpsTarget: 75,
                },
                {
                    exchange: "DERIBIT",
                    symbol: "BTC-PERP",
                    venueSymbol: "BTC-PERPETUAL",
                    status: qsTr("Demo: opcje zabezpieczające"),
                    offline: false,
                    automationRunning: false,
                    fpsTarget: 60,
                },
            ],
            instrumentDetails: {
                exchange: "OKX",
                symbol: "BTC/USDT",
                venueSymbol: "BTC-USDT-SWAP",
                quoteCurrency: "USDT",
                baseCurrency: "BTC",
                granularity: "PT5M",
            },
            aiConfiguration: {
                policy: "market_neutral",
                decision_window: "PT1M",
                risk_profile: "conservative",
                overrides: [
                    { profile: "hedge", maxDrawdown: 0.025, takeProfit: 0.006 },
                ],
                features: ["zscore", "spread_mean", "inventory_skew"],
                modelRevision: "2024.03-neutral",
            },
            portfolioSummary: {
                entryCount: 48,
                minValue: 198000,
                maxValue: 205600,
                latestValue: 203450,
                profileLabel: "Neutral",
                maxDrawdown: 0.019,
                averageDrawdown: 0.011,
                maxLeverage: 1.2,
                averageLeverage: 0.9,
                maxExposureUtilization: 0.54,
                anyBreach: false,
                totalBreaches: 0,
            },
            riskSnapshot: {
                profileLabel: "Neutral",
                currentDrawdown: 0.008,
                maxDailyLoss: 0.02,
                usedLeverage: 0.95,
                generatedAt: "2024-05-18T07:42:10Z",
                exposures: [
                    { code: "BTC_DELTA", current: 0.05, max: 0.1, threshold: 0.08, breach: false },
                    { code: "ETH_DELTA", current: -0.01, max: 0.08, threshold: 0.08, breach: false },
                    { code: "BASIS_SPREAD", current: 0.12, max: 0.25, threshold: 0.2, breach: false },
                ],
            },
            riskTimeline: [
                {
                    timestamp: "2024-05-18T09:04:37+02:00",
                    portfolioValue: 203450,
                    drawdown: 0.008,
                    exposureUtilization: 0.52,
                    leverage: 0.95,
                    breach: false,
                    breachCount: 0,
                    profileLabel: "Neutral",
                    source: "demo",
                    notes: qsTr("Odczyt po korekcie delta hedge"),
                },
                {
                    timestamp: "2024-05-18T08:58:12+02:00",
                    portfolioValue: 202980,
                    drawdown: 0.011,
                    exposureUtilization: 0.49,
                    leverage: 0.97,
                    breach: false,
                    breachCount: 0,
                    profileLabel: "Neutral",
                    source: "demo",
                    notes: qsTr("Stabilizacja spreadów bazowych"),
                },
                {
                    timestamp: "2024-05-18T08:46:00+02:00",
                    portfolioValue: 201720,
                    drawdown: 0.015,
                    exposureUtilization: 0.56,
                    leverage: 1.02,
                    breach: false,
                    breachCount: 0,
                    profileLabel: "Neutral",
                    source: "demo",
                    notes: qsTr("Pik ekspozycji gamma po otwarciu"),
                },
                {
                    timestamp: "2024-05-18T08:32:40+02:00",
                    portfolioValue: 200980,
                    drawdown: 0.017,
                    exposureUtilization: 0.58,
                    leverage: 1.05,
                    breach: false,
                    breachCount: 0,
                    profileLabel: "Neutral",
                    source: "demo",
                    notes: qsTr("Aktualizacja zabezpieczeń opcyjnych"),
                },
            ],
            runtimeStatus: {
                connection: qsTr("Demo: tryb market neutral"),
                reduceMotion: false,
                offlineMode: false,
                offlineDaemonStatus: qsTr("Stabilny"),
                automationRunning: true,
                performanceGuard: { fpsTarget: 75, jankThresholdMs: 16.0, maxOverlayCount: 2 },
                riskRefresh: {
                    enabled: true,
                    intervalSeconds: 45,
                    nextRefreshInSeconds: 22,
                    nextRefreshDueAt: "2024-05-18T09:05:22+02:00",
                    lastUpdateAt: "2024-05-18T09:04:37+02:00",
                },
            },
            controlState: {
                schedulerRunning: true,
                automationRunning: true,
                offlineMode: false,
                lastActionMessage: qsTr("Hedge demo aktywne"),
                lastActionSuccess: true,
                lastActionAt: "2024-05-18T09:04:10+02:00",
                lastRiskRefreshAt: "2024-05-18T09:04:37+02:00",
                nextRiskRefreshDueAt: "2024-05-18T09:05:22+02:00",
                manualRefreshCount: 1,
            },
            activityLog: [
                {
                    timestamp: "2024-05-18T08:52:00+02:00",
                    type: "risk:refresh",
                    message: qsTr("Odświeżono zabezpieczenia krzyżowe"),
                    success: true,
                    source: "demo",
                    details: { context: qsTr("Aktualne delta/gamma w normie") },
                },
                {
                    timestamp: "2024-05-18T08:44:18+02:00",
                    type: "scheduler:start",
                    message: qsTr("Uruchomiono Delta Hedge"),
                    success: true,
                    source: "demo",
                    details: { context: qsTr("Kanał główny OKX aktywny") },
                },
                {
                    timestamp: "2024-05-18T08:30:00+02:00",
                    type: "system:init",
                    message: qsTr("Wczytano tryb Market Neutral"),
                    success: true,
                    source: "demo",
                    details: { context: qsTr("Profile delta i gamma dostępne") },
                },
            ],
            openPositions: [
                {
                    id: "HEDGE-BTC-SWAP",
                    symbol: "BTC/USDT",
                    exchange: "OKX",
                    venueSymbol: "BTC-USDT-SWAP",
                    account: "Neutral-Desk",
                    side: qsTr("Long"),
                    quantity: 1.2,
                    entryPrice: 58640,
                    markPrice: 58710,
                    unrealizedPnl: 84.0,
                    leverage: 1.5,
                    margin: 47000,
                    lastUpdate: "2024-05-18T09:04:37+02:00",
                },
                {
                    id: "HEDGE-BTC-PERP",
                    symbol: "BTC-PERP",
                    exchange: "DERIBIT",
                    venueSymbol: "BTC-PERPETUAL",
                    account: "Neutral-Desk",
                    side: qsTr("Short"),
                    quantity: 1.0,
                    entryPrice: 58590,
                    markPrice: 58630,
                    unrealizedPnl: -40.0,
                    leverage: 1.1,
                    margin: 52000,
                    lastUpdate: "2024-05-18T09:03:55+02:00",
                },
            ],
            pendingOrders: [
                {
                    id: "HEDGE-ORD-001",
                    clientOrderId: "HEDGE-LONG-DELTA",
                    symbol: "BTC/USDT",
                    exchange: "OKX",
                    side: qsTr("Kupno"),
                    type: qsTr("Limit"),
                    quantity: 0.5,
                    filled: 0.3,
                    remaining: 0.2,
                    price: 58600,
                    averagePrice: 58590,
                    status: "PartiallyFilled",
                    timeInForce: "IOC",
                    reduceOnly: false,
                    postOnly: false,
                    createdAt: "2024-05-18T09:03:10+02:00",
                    updatedAt: "2024-05-18T09:04:00+02:00",
                },
                {
                    id: "HEDGE-ORD-002",
                    clientOrderId: "HEDGE-SHORT-GAMMA",
                    symbol: "BTC-PERP",
                    exchange: "DERIBIT",
                    side: qsTr("Sprzedaż"),
                    type: qsTr("Limit"),
                    quantity: 0.7,
                    filled: 0.0,
                    remaining: 0.7,
                    price: 58650,
                    status: "Working",
                    timeInForce: "GTC",
                    reduceOnly: true,
                    postOnly: true,
                    createdAt: "2024-05-18T09:02:00+02:00",
                    updatedAt: "2024-05-18T09:04:37+02:00",
                    expiresAt: "2024-05-18T10:00:00+02:00",
                },
            ],
            tradeHistory: [
                {
                    id: "HEDGE-TR-001",
                    timestamp: "2024-05-18T08:46:00+02:00",
                    symbol: "BTC/USDT",
                    exchange: "OKX",
                    side: qsTr("Kupno"),
                    quantity: 0.6,
                    price: 58580,
                    pnl: 0,
                    fee: 1.8,
                    status: "Filled",
                    orderId: "HEDGE-DELTA-58580",
                    notes: qsTr("Przełączenie profilu delta"),
                },
                {
                    id: "HEDGE-TR-002",
                    timestamp: "2024-05-18T08:40:15+02:00",
                    symbol: "BTC-PERP",
                    exchange: "DERIBIT",
                    side: qsTr("Sprzedaż"),
                    quantity: 0.8,
                    price: 58510,
                    pnl: 52.0,
                    fee: 1.4,
                    status: "Filled",
                    orderId: "HEDGE-GAMMA-58510",
                    notes: qsTr("Hedge ekspozycji gamma"),
                },
                {
                    id: "HEDGE-TR-003",
                    timestamp: "2024-05-18T08:30:00+02:00",
                    symbol: "BTC/USDT",
                    exchange: "OKX",
                    side: qsTr("Sprzedaż"),
                    quantity: 0.6,
                    price: 58620,
                    pnl: 36.0,
                    fee: 1.8,
                    status: "Filled",
                    orderId: "HEDGE-DELTA-58620",
                    notes: qsTr("Rebalans delta po otwarciu sesji"),
                },
            ],
            signalAlerts: [
                {
                    id: "HEDGE-SIG-001",
                    category: "hedge",
                    symbol: "BTC/USDT",
                    direction: qsTr("Long"),
                    confidence: 0.55,
                    impact: 0.48,
                    message: qsTr("Delta dodatnia – doskaluj krótkie opcje"),
                    priority: qsTr("Średni"),
                    generatedAt: "2024-05-18T09:03:50+02:00",
                    expiresAt: "2024-05-18T09:08:50+02:00",
                    tags: ["delta", "hedge"],
                },
                {
                    id: "HEDGE-SIG-002",
                    category: "gamma",
                    symbol: "BTC-PERP",
                    direction: qsTr("Short"),
                    confidence: 0.61,
                    impact: 0.57,
                    message: qsTr("Gamma rośnie – przygotuj szybkie rolowanie"),
                    priority: qsTr("Wysoki"),
                    generatedAt: "2024-05-18T08:57:20+02:00",
                    expiresAt: "2024-05-18T09:12:20+02:00",
                    tags: ["gamma", "risk"],
                },
            ],
            licenseStatus: {
                active: true,
                edition: "OEM Enterprise",
                licenseId: "DEMO-HEDGE",
                holderName: "Core Labs Hedge Demo",
                maintenanceActive: true,
                modules: ["hedge", "risk", "scheduler"],
                runtime: ["desktop-shell", "risk-service"],
            },
        },
    ];
}

function findPreset(presets, id) {
    if (!id)
        return null;
    for (let i = 0; i < presets.length; ++i) {
        if (presets[i].id === id)
            return presets[i];
    }
    return null;
}

function clonePreset(preset) {
    return JSON.parse(JSON.stringify(preset));
}
