function createPresets() {
    return [
        {
            id: "momentum",
            title: qsTr("Momentum Pro"),
            description: qsTr("Zestaw presetów momentum dla rynku krypto – automatyczne balansowanie ryzyka i szybkie przełączanie profili."),
            schedulerEntries: [
                {
                    name: "Momentum Alpha",
                    enabled: true,
                    scheduleCount: 4,
                    timezone: "UTC",
                    nextRun: "2024-05-18T09:00:00Z",
                    notes: qsTr("Aktywne okna 1m/5m z trailing stop"),
                },
                {
                    name: "Momentum Beta",
                    enabled: true,
                    scheduleCount: 2,
                    timezone: "UTC",
                    nextRun: "2024-05-18T10:15:00Z",
                    notes: qsTr("Agregacja multi-venue, target delta 0.3"),
                },
            ],
            exchangeConnections: [
                {
                    exchange: "BINANCE",
                    symbol: "BTC/USDT",
                    venueSymbol: "BTCUSDT",
                    status: qsTr("Demo: połączenie symulacyjne"),
                    offline: false,
                    automationRunning: true,
                    fpsTarget: 120,
                },
                {
                    exchange: "COINBASE",
                    symbol: "ETH/USD",
                    venueSymbol: "ETHUSD",
                    status: qsTr("Demo: monitorowanie danych order book"),
                    offline: false,
                    automationRunning: true,
                    fpsTarget: 90,
                },
            ],
            instrumentDetails: {
                exchange: "BINANCE",
                symbol: "BTC/USDT",
                venueSymbol: "BTCUSDT",
                quoteCurrency: "USDT",
                baseCurrency: "BTC",
                granularity: "PT1M",
            },
            aiConfiguration: {
                policy: "momentum",
                decision_window: "PT15S",
                risk_profile: "growth",
                overrides: [
                    { profile: "intraday", maxDrawdown: 0.04, takeProfit: 0.012 },
                    { profile: "swing", maxDrawdown: 0.06, takeProfit: 0.028 },
                ],
                features: ["ema12", "ema26", "vwap", "macro_feed"],
                modelRevision: "2024.04-momentum",
            },
            portfolioSummary: {
                entryCount: 64,
                minValue: 92500,
                maxValue: 132400,
                latestValue: 129800,
                profileLabel: "Momentum",
                maxDrawdown: 0.083,
                averageDrawdown: 0.031,
                maxLeverage: 2.4,
                averageLeverage: 1.7,
                maxExposureUtilization: 0.82,
                anyBreach: false,
                totalBreaches: 0,
            },
            riskSnapshot: {
                profileLabel: "Momentum",
                currentDrawdown: 0.021,
                maxDailyLoss: 0.055,
                usedLeverage: 1.68,
                generatedAt: "2024-05-18T08:55:12Z",
                exposures: [
                    { code: "XBT_PERP", current: 0.62, max: 0.8, threshold: 0.75, breach: false },
                    { code: "ETH_PERP", current: 0.48, max: 0.7, threshold: 0.65, breach: false },
                    { code: "ALT_BASKET", current: 0.31, max: 0.55, threshold: 0.5, breach: false },
                ],
            },
            performanceComparison: {
                benchmarkName: qsTr("BTC Spot Index"),
                since: "2023-11-01T00:00:00Z",
                updatedAt: "2024-05-18T08:59:30Z",
                strategyReturn: 0.186,
                benchmarkReturn: 0.142,
                alpha: 0.044,
                beta: 0.82,
                sharpe: 1.64,
                sortino: 2.31,
                volatility: 0.28,
                trackingError: 0.12,
                maxDrawdown: 0.095,
                notes: qsTr("Momentum przewyższa benchmark dzięki aktywnej kontroli ryzyka."),
            },
            capitalAllocation: [
                {
                    segment: qsTr("Momentum Core"),
                    weight: 0.38,
                    targetWeight: 0.35,
                    deltaWeight: 0.03,
                    notional: 52000,
                    leverage: 1.6,
                    hedged: false,
                    notes: qsTr("Główna ekspozycja na BTC perpetual."),
                },
                {
                    segment: qsTr("Alt overlay"),
                    weight: 0.24,
                    targetWeight: 0.25,
                    deltaWeight: -0.01,
                    notional: 33000,
                    leverage: 1.4,
                    hedged: false,
                    notes: qsTr("Koszyk altcoinów śledzony w trybie momentum."),
                },
                {
                    segment: qsTr("DeFi basket"),
                    weight: 0.18,
                    targetWeight: 0.20,
                    deltaWeight: -0.02,
                    notional: 24000,
                    leverage: 1.3,
                    hedged: true,
                    notes: qsTr("Częściowo zabezpieczony kontraktami futures."),
                },
                {
                    segment: qsTr("Stable yield"),
                    weight: 0.20,
                    targetWeight: 0.20,
                    deltaWeight: 0.0,
                    notional: 27000,
                    leverage: 1.0,
                    hedged: true,
                    notes: qsTr("Stabilna noga generująca finansowanie strategii."),
                },
            ],
            riskTimeline: [
                {
                    timestamp: "2024-05-18T08:59:48Z",
                    portfolioValue: 129800,
                    drawdown: 0.021,
                    exposureUtilization: 0.79,
                    leverage: 1.68,
                    breach: false,
                    breachCount: 0,
                    profileLabel: "Momentum",
                    source: "demo",
                    notes: qsTr("Ostatnia próbka po automatycznym odświeżeniu"),
                },
                {
                    timestamp: "2024-05-18T08:55:12Z",
                    portfolioValue: 128450,
                    drawdown: 0.028,
                    exposureUtilization: 0.74,
                    leverage: 1.72,
                    breach: false,
                    breachCount: 0,
                    profileLabel: "Momentum",
                    source: "demo",
                    notes: qsTr("Monitoring wolumenów podczas sesji EU"),
                },
                {
                    timestamp: "2024-05-18T08:47:05Z",
                    portfolioValue: 126980,
                    drawdown: 0.034,
                    exposureUtilization: 0.81,
                    leverage: 1.76,
                    breach: false,
                    breachCount: 0,
                    profileLabel: "Momentum",
                    source: "demo",
                    notes: qsTr("Krótki wzrost ekspozycji na ALT_BASKET"),
                },
                {
                    timestamp: "2024-05-18T08:38:00Z",
                    portfolioValue: 125420,
                    drawdown: 0.039,
                    exposureUtilization: 0.83,
                    leverage: 1.82,
                    breach: false,
                    breachCount: 0,
                    profileLabel: "Momentum",
                    source: "demo",
                    notes: qsTr("Stabilizacja po otwarciu Londynu"),
                },
            ],
            runtimeStatus: {
                connection: qsTr("Demo: połączenie symulacyjne"),
                reduceMotion: false,
                offlineMode: false,
                offlineDaemonStatus: qsTr("Aktywny symulator"),
                automationRunning: true,
                performanceGuard: { fpsTarget: 120, jankThresholdMs: 12.0, maxOverlayCount: 3 },
                riskRefresh: {
                    enabled: true,
                    intervalSeconds: 30,
                    nextRefreshInSeconds: 18,
                    nextRefreshDueAt: "2024-05-18T09:00:18Z",
                    lastUpdateAt: "2024-05-18T08:59:48Z",
                    lastRequestAt: "2024-05-18T08:59:45Z",
                },
            },
            controlState: {
                schedulerRunning: true,
                automationRunning: true,
                offlineMode: false,
                lastActionMessage: qsTr("Tryb demo gotowy"),
                lastActionSuccess: true,
                lastActionAt: "2024-05-18T08:59:30Z",
                lastRiskRefreshAt: "2024-05-18T08:59:48Z",
                nextRiskRefreshDueAt: "2024-05-18T09:00:18Z",
                manualRefreshCount: 2,
            },
            activityLog: [
                {
                    timestamp: "2024-05-18T08:57:30Z",
                    type: "scheduler:start",
                    message: qsTr("Scheduler Momentum Alpha aktywny"),
                    success: true,
                    source: "demo",
                    details: { context: qsTr("Harmonogram główny włączony") },
                },
                {
                    timestamp: "2024-05-18T08:55:12Z",
                    type: "risk:refresh",
                    message: qsTr("Zaktualizowano metryki ryzyka"),
                    success: true,
                    source: "demo",
                    details: { context: qsTr("Nowe dane portfela momentum") },
                },
                {
                    timestamp: "2024-05-18T08:50:00Z",
                    type: "system:init",
                    message: qsTr("Załadowano profil Momentum Pro"),
                    success: true,
                    source: "demo",
                    details: { context: qsTr("Konfiguracja strategii i runtime wczytana.") },
                },
            ],
            openPositions: [
                {
                    id: "MOMENTUM-BTCUSDT",
                    symbol: "BTC/USDT",
                    exchange: "BINANCE",
                    venueSymbol: "BTCUSDT",
                    account: "Momentum-Desk",
                    side: qsTr("Long"),
                    quantity: 0.85,
                    entryPrice: 58520,
                    markPrice: 58980,
                    unrealizedPnl: 391.5,
                    leverage: 3.2,
                    margin: 15500,
                    lastUpdate: "2024-05-18T08:59:48Z",
                },
                {
                    id: "MOMENTUM-ETHUSD",
                    symbol: "ETH/USD",
                    exchange: "COINBASE",
                    venueSymbol: "ETHUSD",
                    account: "Momentum-Desk",
                    side: qsTr("Long"),
                    quantity: 12.4,
                    entryPrice: 3050,
                    markPrice: 3084,
                    unrealizedPnl: 421.6,
                    leverage: 2.1,
                    margin: 18000,
                    lastUpdate: "2024-05-18T08:58:03Z",
                },
            ],
            pendingOrders: [
                {
                    id: "MOM-ORD-001",
                    clientOrderId: "MOM-ALPHA-58950",
                    symbol: "BTC/USDT",
                    exchange: "BINANCE",
                    side: qsTr("Kupno"),
                    type: qsTr("Limit"),
                    quantity: 0.25,
                    filled: 0.1,
                    remaining: 0.15,
                    price: 58950,
                    averagePrice: 58890,
                    status: "PartiallyFilled",
                    timeInForce: "GTC",
                    postOnly: true,
                    reduceOnly: false,
                    createdAt: "2024-05-18T08:58:10Z",
                    updatedAt: "2024-05-18T08:59:30Z",
                    expiresAt: "2024-05-18T09:05:00Z",
                },
                {
                    id: "MOM-ORD-002",
                    clientOrderId: "MOM-BETA-3080",
                    symbol: "ETH/USD",
                    exchange: "COINBASE",
                    side: qsTr("Sprzedaż"),
                    type: qsTr("Stop"),
                    quantity: 4.0,
                    filled: 0.0,
                    remaining: 4.0,
                    price: 3080,
                    averagePrice: 0,
                    status: "Working",
                    timeInForce: "GTC",
                    reduceOnly: true,
                    postOnly: false,
                    createdAt: "2024-05-18T08:54:00Z",
                    updatedAt: "2024-05-18T08:58:42Z",
                    expiresAt: "2024-05-18T09:30:00Z",
                },
            ],
            tradeHistory: [
                {
                    id: "MOM-TR-001",
                    timestamp: "2024-05-18T08:47:05Z",
                    symbol: "BTC/USDT",
                    exchange: "BINANCE",
                    side: qsTr("Kupno"),
                    quantity: 0.50,
                    price: 58240,
                    pnl: 0,
                    fee: 3.4,
                    status: "Filled",
                    orderId: "MOM-ALPHA-58240",
                    notes: qsTr("Wejście po sygnale momentum"),
                },
                {
                    id: "MOM-TR-002",
                    timestamp: "2024-05-18T08:38:00Z",
                    symbol: "BTC/USDT",
                    exchange: "BINANCE",
                    side: qsTr("Kupno"),
                    quantity: 0.35,
                    price: 58380,
                    pnl: 86.4,
                    fee: 2.8,
                    status: "Filled",
                    orderId: "MOM-ALPHA-58380",
                    notes: qsTr("Rozszerzenie pozycji po wybiciu"),
                },
                {
                    id: "MOM-TR-003",
                    timestamp: "2024-05-18T08:22:10Z",
                    symbol: "ETH/USD",
                    exchange: "COINBASE",
                    side: qsTr("Sprzedaż"),
                    quantity: 6.0,
                    price: 3028,
                    pnl: 114.0,
                    fee: 2.1,
                    status: "Filled",
                    orderId: "MOM-BETA-3028",
                    notes: qsTr("Realizacja częściowa zysków"),
                },
            ],
            signalAlerts: [
                {
                    id: "MOM-SIG-001",
                    category: "momentum",
                    symbol: "BTC/USDT",
                    direction: qsTr("Long"),
                    confidence: 0.82,
                    impact: 0.64,
                    message: qsTr("Momentum breakout potwierdzony na 5m"),
                    priority: qsTr("Wysoki"),
                    generatedAt: "2024-05-18T08:58:45Z",
                    expiresAt: "2024-05-18T09:03:45Z",
                    tags: ["breakout", "momentum"],
                },
                {
                    id: "MOM-SIG-002",
                    category: "volatility",
                    symbol: "ETH/USD",
                    direction: qsTr("Long"),
                    confidence: 0.68,
                    impact: 0.52,
                    message: qsTr("Wzrost zmienności – monitoruj trailing stop"),
                    priority: qsTr("Średni"),
                    generatedAt: "2024-05-18T08:53:12Z",
                    expiresAt: "2024-05-18T09:08:12Z",
                    tags: ["volatility", "risk"],
                },
            ],
            scenarioTests: [
                {
                    id: "MOM-SC-001",
                    name: qsTr("Flash Crash 15%"),
                    category: "stress",
                    severity: qsTr("wysoki"),
                    status: qsTr("Zakończony"),
                    success: true,
                    pnlImpact: -0.042,
                    maxDrawdown: 0.058,
                    liquidityImpact: 0.32,
                    marginUsage: 0.61,
                    durationSeconds: 180,
                    lastRunAt: "2024-05-17T21:00:00Z",
                    completedAt: "2024-05-17T21:00:00Z",
                    runCount: 4,
                    notes: [
                        qsTr("Zabezpieczenie delta aktywne"),
                        qsTr("Pozycje zredukowane do 60% ekspozycji"),
                    ],
                },
                {
                    id: "MOM-SC-002",
                    name: qsTr("Nagły wzrost zmienności"),
                    category: "volatility",
                    severity: qsTr("wysoki"),
                    status: qsTr("Nieudany"),
                    success: false,
                    pnlImpact: -0.095,
                    maxDrawdown: 0.128,
                    liquidityImpact: 0.45,
                    marginUsage: 0.74,
                    durationSeconds: 240,
                    lastRunAt: "2024-05-15T18:30:00Z",
                    completedAt: "2024-05-15T18:30:00Z",
                    runCount: 2,
                    notes: [
                        qsTr("Limit dźwigni przekroczony w 32 minucie"),
                        qsTr("Rekomendacja: zwiększyć bufor kapitału bezpieczeństwa"),
                    ],
                },
                {
                    id: "MOM-SC-003",
                    name: qsTr("Dryf trendu bocznego"),
                    category: "regime",
                    severity: qsTr("średni"),
                    status: qsTr("Zakończony"),
                    success: true,
                    pnlImpact: 0.012,
                    maxDrawdown: 0.021,
                    liquidityImpact: 0.18,
                    marginUsage: 0.42,
                    durationSeconds: 3600,
                    lastRunAt: "2024-05-16T11:00:00Z",
                    completedAt: "2024-05-16T12:00:00Z",
                    runCount: 6,
                    notes: [qsTr("Strategia utrzymuje dodatnie PnL w okresie konsolidacji.")],
                },
            ],
            marketSentiment: {
                trend: qsTr("Bullish"),
                globalScore: 0.64,
                confidence: 0.72,
                volatilityIndex: 31.5,
                onChainFlow: 1.28,
                newsScore: 0.48,
                derivedAt: "2024-05-18T08:58:00Z",
                sources: [
                    {
                        name: qsTr("Fear & Greed Index"),
                        score: 0.68,
                        weight: 0.35,
                        sentiment: qsTr("Bullish"),
                        updatedAt: "2024-05-18T08:55:00Z",
                        notes: qsTr("Odczyt wzrósł o 3 punkty w stosunku do dnia poprzedniego."),
                    },
                    {
                        name: qsTr("Funding rates"),
                        score: 0.61,
                        weight: 0.28,
                        sentiment: qsTr("Positive"),
                        updatedAt: "2024-05-18T08:52:00Z",
                        notes: qsTr("Dodatnie stopy finansowania wspierają trend wzrostowy."),
                    },
                    {
                        name: qsTr("On-chain flows"),
                        score: 0.57,
                        weight: 0.22,
                        sentiment: qsTr("Accumulation"),
                        updatedAt: "2024-05-18T08:50:00Z",
                        notes: qsTr("Większe wypłaty z giełd sugerują popyt spot."),
                    },
                ],
            },
            newsHeadlines: [
                {
                    id: "MOM-NEWS-001",
                    title: qsTr("ETF-y spot zwiększają napływy na rynek BTC"),
                    summary: qsTr("Nowe środki napływają do funduszy ETF na Bitcoina, co podbija aktywność kupujących."),
                    source: "CryptoTimes",
                    sentiment: qsTr("Positive"),
                    publishedAt: "2024-05-18T08:40:00Z",
                    url: "https://news.example.com/etf-flows",
                },
                {
                    id: "MOM-NEWS-002",
                    title: qsTr("Deweloperzy DeFi wdrażają kolejne aktualizacje bezpieczeństwa"),
                    summary: qsTr("Segment DeFi wzmacnia kontrole ryzyka po ostatnich exploitach, stabilizując nastroje inwestorów."),
                    source: "DeFi Journal",
                    sentiment: qsTr("Neutral"),
                    publishedAt: "2024-05-18T08:32:00Z",
                    url: "https://news.example.com/defi-security",
                },
                {
                    id: "MOM-NEWS-003",
                    title: qsTr("Odbicie na altcoinach po sygnale momentum"),
                    summary: qsTr("Szeroki koszyk altcoinów notuje dwucyfrowe wzrosty wraz z aktywacją strategii momentum."),
                    source: "Market Pulse",
                    sentiment: qsTr("Positive"),
                    publishedAt: "2024-05-18T08:20:00Z",
                    url: "https://news.example.com/altcoin-rebound",
                },
            ],
            licenseStatus: {
                active: true,
                edition: "OEM Demo",
                licenseId: "DEMO-MOMENTUM",
                holderName: "Core Labs QA",
                maintenanceActive: true,
                modules: ["momentum", "portfolio", "scheduler"],
                runtime: ["desktop-shell", "scheduler-engine"],
            },
        },
        {
            id: "hedge",
            title: qsTr("Market Neutral"),
            description: qsTr("Tryb prezentacyjny dla funduszy market-neutral – pokazuje balancing delta i zabezpieczenia krzyżowe."),
            schedulerEntries: [
                {
                    name: "Delta Hedge",
                    enabled: true,
                    scheduleCount: 6,
                    timezone: "Europe/Warsaw",
                    nextRun: "2024-05-18T09:05:00+02:00",
                    notes: qsTr("Rebalans co 10 minut z limitem slippage 2 bps"),
                },
                {
                    name: "Gamma Overlay",
                    enabled: false,
                    scheduleCount: 1,
                    timezone: "Europe/Warsaw",
                    nextRun: "2024-05-18T12:00:00+02:00",
                    notes: qsTr("Opcjonalna noga opcyjna do pokazu"),
                },
            ],
            exchangeConnections: [
                {
                    exchange: "OKX",
                    symbol: "BTC/USDT",
                    venueSymbol: "BTC-USDT-SWAP",
                    status: qsTr("Demo: kanał hedge aktywny"),
                    offline: false,
                    automationRunning: true,
                    fpsTarget: 75,
                },
                {
                    exchange: "DERIBIT",
                    symbol: "BTC-PERP",
                    venueSymbol: "BTC-PERPETUAL",
                    status: qsTr("Demo: opcje zabezpieczające"),
                    offline: false,
                    automationRunning: false,
                    fpsTarget: 60,
                },
            ],
            instrumentDetails: {
                exchange: "OKX",
                symbol: "BTC/USDT",
                venueSymbol: "BTC-USDT-SWAP",
                quoteCurrency: "USDT",
                baseCurrency: "BTC",
                granularity: "PT5M",
            },
            aiConfiguration: {
                policy: "market_neutral",
                decision_window: "PT1M",
                risk_profile: "conservative",
                overrides: [
                    { profile: "hedge", maxDrawdown: 0.025, takeProfit: 0.006 },
                ],
                features: ["zscore", "spread_mean", "inventory_skew"],
                modelRevision: "2024.03-neutral",
            },
            portfolioSummary: {
                entryCount: 48,
                minValue: 198000,
                maxValue: 205600,
                latestValue: 203450,
                profileLabel: "Neutral",
                maxDrawdown: 0.019,
                averageDrawdown: 0.011,
                maxLeverage: 1.2,
                averageLeverage: 0.9,
                maxExposureUtilization: 0.54,
                anyBreach: false,
                totalBreaches: 0,
            },
            riskSnapshot: {
                profileLabel: "Neutral",
                currentDrawdown: 0.008,
                maxDailyLoss: 0.02,
                usedLeverage: 0.95,
                generatedAt: "2024-05-18T07:42:10Z",
                exposures: [
                    { code: "BTC_DELTA", current: 0.05, max: 0.1, threshold: 0.08, breach: false },
                    { code: "ETH_DELTA", current: -0.01, max: 0.08, threshold: 0.08, breach: false },
                    { code: "BASIS_SPREAD", current: 0.12, max: 0.25, threshold: 0.2, breach: false },
                ],
            },
            performanceComparison: {
                benchmarkName: qsTr("Koszyk delta-neutral"),
                since: "2023-09-01T00:00:00+02:00",
                updatedAt: "2024-05-18T09:04:00+02:00",
                strategyReturn: 0.082,
                benchmarkReturn: 0.054,
                alpha: 0.028,
                beta: 0.18,
                sharpe: 1.12,
                sortino: 1.74,
                volatility: 0.11,
                trackingError: 0.05,
                maxDrawdown: 0.036,
                notes: qsTr("Strategia neutralna utrzymuje niższą zmienność względem benchmarku."),
            },
            capitalAllocation: [
                {
                    segment: qsTr("Perpetual hedge"),
                    weight: 0.32,
                    targetWeight: 0.30,
                    deltaWeight: 0.02,
                    notional: 64000,
                    leverage: 1.2,
                    hedged: true,
                    notes: qsTr("Kontrakt perpetual jako noga zabezpieczająca delta."),
                },
                {
                    segment: qsTr("Options overlay"),
                    weight: 0.18,
                    targetWeight: 0.20,
                    deltaWeight: -0.02,
                    notional: 36000,
                    leverage: 0.8,
                    hedged: true,
                    notes: qsTr("Ekspozycja opcyjna wspierająca gamma."),
                },
                {
                    segment: qsTr("Spot carry"),
                    weight: 0.28,
                    targetWeight: 0.30,
                    deltaWeight: -0.02,
                    notional: 56000,
                    leverage: 1.1,
                    hedged: false,
                    notes: qsTr("Neutralna noga spot finansowana na stablecoinach."),
                },
                {
                    segment: qsTr("Liquidity reserves"),
                    weight: 0.22,
                    targetWeight: 0.20,
                    deltaWeight: 0.02,
                    notional: 44000,
                    leverage: 0.5,
                    hedged: true,
                    notes: qsTr("Bufor płynności na potrzeby rebalansów i margin calli."),
                },
            ],
            riskTimeline: [
                {
                    timestamp: "2024-05-18T09:04:37+02:00",
                    portfolioValue: 203450,
                    drawdown: 0.008,
                    exposureUtilization: 0.52,
                    leverage: 0.95,
                    breach: false,
                    breachCount: 0,
                    profileLabel: "Neutral",
                    source: "demo",
                    notes: qsTr("Odczyt po korekcie delta hedge"),
                },
                {
                    timestamp: "2024-05-18T08:58:12+02:00",
                    portfolioValue: 202980,
                    drawdown: 0.011,
                    exposureUtilization: 0.49,
                    leverage: 0.97,
                    breach: false,
                    breachCount: 0,
                    profileLabel: "Neutral",
                    source: "demo",
                    notes: qsTr("Stabilizacja spreadów bazowych"),
                },
                {
                    timestamp: "2024-05-18T08:46:00+02:00",
                    portfolioValue: 201720,
                    drawdown: 0.015,
                    exposureUtilization: 0.56,
                    leverage: 1.02,
                    breach: false,
                    breachCount: 0,
                    profileLabel: "Neutral",
                    source: "demo",
                    notes: qsTr("Pik ekspozycji gamma po otwarciu"),
                },
                {
                    timestamp: "2024-05-18T08:32:40+02:00",
                    portfolioValue: 200980,
                    drawdown: 0.017,
                    exposureUtilization: 0.58,
                    leverage: 1.05,
                    breach: false,
                    breachCount: 0,
                    profileLabel: "Neutral",
                    source: "demo",
                    notes: qsTr("Aktualizacja zabezpieczeń opcyjnych"),
                },
            ],
            runtimeStatus: {
                connection: qsTr("Demo: tryb market neutral"),
                reduceMotion: false,
                offlineMode: false,
                offlineDaemonStatus: qsTr("Stabilny"),
                automationRunning: true,
                performanceGuard: { fpsTarget: 75, jankThresholdMs: 16.0, maxOverlayCount: 2 },
                riskRefresh: {
                    enabled: true,
                    intervalSeconds: 45,
                    nextRefreshInSeconds: 22,
                    nextRefreshDueAt: "2024-05-18T09:05:22+02:00",
                    lastUpdateAt: "2024-05-18T09:04:37+02:00",
                },
            },
            controlState: {
                schedulerRunning: true,
                automationRunning: true,
                offlineMode: false,
                lastActionMessage: qsTr("Hedge demo aktywne"),
                lastActionSuccess: true,
                lastActionAt: "2024-05-18T09:04:10+02:00",
                lastRiskRefreshAt: "2024-05-18T09:04:37+02:00",
                nextRiskRefreshDueAt: "2024-05-18T09:05:22+02:00",
                manualRefreshCount: 1,
            },
            activityLog: [
                {
                    timestamp: "2024-05-18T08:52:00+02:00",
                    type: "risk:refresh",
                    message: qsTr("Odświeżono zabezpieczenia krzyżowe"),
                    success: true,
                    source: "demo",
                    details: { context: qsTr("Aktualne delta/gamma w normie") },
                },
                {
                    timestamp: "2024-05-18T08:44:18+02:00",
                    type: "scheduler:start",
                    message: qsTr("Uruchomiono Delta Hedge"),
                    success: true,
                    source: "demo",
                    details: { context: qsTr("Kanał główny OKX aktywny") },
                },
                {
                    timestamp: "2024-05-18T08:30:00+02:00",
                    type: "system:init",
                    message: qsTr("Wczytano tryb Market Neutral"),
                    success: true,
                    source: "demo",
                    details: { context: qsTr("Profile delta i gamma dostępne") },
                },
            ],
            openPositions: [
                {
                    id: "HEDGE-BTC-SWAP",
                    symbol: "BTC/USDT",
                    exchange: "OKX",
                    venueSymbol: "BTC-USDT-SWAP",
                    account: "Neutral-Desk",
                    side: qsTr("Long"),
                    quantity: 1.2,
                    entryPrice: 58640,
                    markPrice: 58710,
                    unrealizedPnl: 84.0,
                    leverage: 1.5,
                    margin: 47000,
                    lastUpdate: "2024-05-18T09:04:37+02:00",
                },
                {
                    id: "HEDGE-BTC-PERP",
                    symbol: "BTC-PERP",
                    exchange: "DERIBIT",
                    venueSymbol: "BTC-PERPETUAL",
                    account: "Neutral-Desk",
                    side: qsTr("Short"),
                    quantity: 1.0,
                    entryPrice: 58590,
                    markPrice: 58630,
                    unrealizedPnl: -40.0,
                    leverage: 1.1,
                    margin: 52000,
                    lastUpdate: "2024-05-18T09:03:55+02:00",
                },
            ],
            pendingOrders: [
                {
                    id: "HEDGE-ORD-001",
                    clientOrderId: "HEDGE-LONG-DELTA",
                    symbol: "BTC/USDT",
                    exchange: "OKX",
                    side: qsTr("Kupno"),
                    type: qsTr("Limit"),
                    quantity: 0.5,
                    filled: 0.3,
                    remaining: 0.2,
                    price: 58600,
                    averagePrice: 58590,
                    status: "PartiallyFilled",
                    timeInForce: "IOC",
                    reduceOnly: false,
                    postOnly: false,
                    createdAt: "2024-05-18T09:03:10+02:00",
                    updatedAt: "2024-05-18T09:04:00+02:00",
                },
                {
                    id: "HEDGE-ORD-002",
                    clientOrderId: "HEDGE-SHORT-GAMMA",
                    symbol: "BTC-PERP",
                    exchange: "DERIBIT",
                    side: qsTr("Sprzedaż"),
                    type: qsTr("Limit"),
                    quantity: 0.7,
                    filled: 0.0,
                    remaining: 0.7,
                    price: 58650,
                    status: "Working",
                    timeInForce: "GTC",
                    reduceOnly: true,
                    postOnly: true,
                    createdAt: "2024-05-18T09:02:00+02:00",
                    updatedAt: "2024-05-18T09:04:37+02:00",
                    expiresAt: "2024-05-18T10:00:00+02:00",
                },
            ],
            tradeHistory: [
                {
                    id: "HEDGE-TR-001",
                    timestamp: "2024-05-18T08:46:00+02:00",
                    symbol: "BTC/USDT",
                    exchange: "OKX",
                    side: qsTr("Kupno"),
                    quantity: 0.6,
                    price: 58580,
                    pnl: 0,
                    fee: 1.8,
                    status: "Filled",
                    orderId: "HEDGE-DELTA-58580",
                    notes: qsTr("Przełączenie profilu delta"),
                },
                {
                    id: "HEDGE-TR-002",
                    timestamp: "2024-05-18T08:40:15+02:00",
                    symbol: "BTC-PERP",
                    exchange: "DERIBIT",
                    side: qsTr("Sprzedaż"),
                    quantity: 0.8,
                    price: 58510,
                    pnl: 52.0,
                    fee: 1.4,
                    status: "Filled",
                    orderId: "HEDGE-GAMMA-58510",
                    notes: qsTr("Hedge ekspozycji gamma"),
                },
                {
                    id: "HEDGE-TR-003",
                    timestamp: "2024-05-18T08:30:00+02:00",
                    symbol: "BTC/USDT",
                    exchange: "OKX",
                    side: qsTr("Sprzedaż"),
                    quantity: 0.6,
                    price: 58620,
                    pnl: 36.0,
                    fee: 1.8,
                    status: "Filled",
                    orderId: "HEDGE-DELTA-58620",
                    notes: qsTr("Rebalans delta po otwarciu sesji"),
                },
            ],
            signalAlerts: [
                {
                    id: "HEDGE-SIG-001",
                    category: "hedge",
                    symbol: "BTC/USDT",
                    direction: qsTr("Long"),
                    confidence: 0.55,
                    impact: 0.48,
                    message: qsTr("Delta dodatnia – doskaluj krótkie opcje"),
                    priority: qsTr("Średni"),
                    generatedAt: "2024-05-18T09:03:50+02:00",
                    expiresAt: "2024-05-18T09:08:50+02:00",
                    tags: ["delta", "hedge"],
                },
                {
                    id: "HEDGE-SIG-002",
                    category: "gamma",
                    symbol: "BTC-PERP",
                    direction: qsTr("Short"),
                    confidence: 0.61,
                    impact: 0.57,
                    message: qsTr("Gamma rośnie – przygotuj szybkie rolowanie"),
                    priority: qsTr("Wysoki"),
                    generatedAt: "2024-05-18T08:57:20+02:00",
                    expiresAt: "2024-05-18T09:12:20+02:00",
                    tags: ["gamma", "risk"],
                },
            ],
            scenarioTests: [
                {
                    id: "HEDGE-SC-001",
                    name: qsTr("Nagły skok funding rate"),
                    category: "funding",
                    severity: qsTr("średni"),
                    status: qsTr("Zakończony"),
                    success: true,
                    pnlImpact: -0.018,
                    maxDrawdown: 0.032,
                    liquidityImpact: 0.24,
                    marginUsage: 0.48,
                    durationSeconds: 900,
                    lastRunAt: "2024-05-16T19:45:00+02:00",
                    completedAt: "2024-05-16T20:00:00+02:00",
                    runCount: 5,
                    notes: [qsTr("Hedging opcyjny pokrył wzrost kosztów finansowania.")],
                },
                {
                    id: "HEDGE-SC-002",
                    name: qsTr("Zanik płynności na BTC-PERP"),
                    category: "liquidity",
                    severity: qsTr("wysoki"),
                    status: qsTr("Nieudany"),
                    success: false,
                    pnlImpact: -0.062,
                    maxDrawdown: 0.094,
                    liquidityImpact: 0.52,
                    marginUsage: 0.67,
                    durationSeconds: 420,
                    lastRunAt: "2024-05-14T22:10:00+02:00",
                    completedAt: "2024-05-14T22:17:00+02:00",
                    runCount: 3,
                    notes: [
                        qsTr("Niedobór płynności na głównych giełdach"),
                        qsTr("Proponowany plan: aktywować dodatkowe venue OTC"),
                    ],
                },
                {
                    id: "HEDGE-SC-003",
                    name: qsTr("Dryf niskiej zmienności"),
                    category: "regime",
                    severity: qsTr("niski"),
                    status: qsTr("Zakończony"),
                    success: true,
                    pnlImpact: 0.006,
                    maxDrawdown: 0.015,
                    liquidityImpact: 0.12,
                    marginUsage: 0.35,
                    durationSeconds: 5400,
                    lastRunAt: "2024-05-17T07:30:00+02:00",
                    completedAt: "2024-05-17T09:00:00+02:00",
                    runCount: 7,
                    notes: [qsTr("Strategia utrzymuje neutralną deltę z dodatnią alfą.")],
                },
            ],
            marketSentiment: {
                trend: qsTr("Neutral"),
                globalScore: 0.41,
                confidence: 0.58,
                volatilityIndex: 27.2,
                onChainFlow: 0.18,
                newsScore: 0.36,
                derivedAt: "2024-05-18T09:04:30+02:00",
                sources: [
                    {
                        name: qsTr("Basis spreads"),
                        score: 0.44,
                        weight: 0.32,
                        sentiment: qsTr("Neutral"),
                        updatedAt: "2024-05-18T09:03:00+02:00",
                        notes: qsTr("Spready terminowe utrzymują się w umiarkowanym zakresie."),
                    },
                    {
                        name: qsTr("Options skew"),
                        score: 0.39,
                        weight: 0.27,
                        sentiment: qsTr("Cautious"),
                        updatedAt: "2024-05-18T08:59:00+02:00",
                        notes: qsTr("Skew dodatni sygnalizuje popyt na opcje call."),
                    },
                    {
                        name: qsTr("Macro calendar"),
                        score: 0.36,
                        weight: 0.21,
                        sentiment: qsTr("Watchlist"),
                        updatedAt: "2024-05-18T08:45:00+02:00",
                        notes: qsTr("Oczekiwane dane CPI mogą zwiększyć zmienność."),
                    },
                ],
            },
            newsHeadlines: [
                {
                    id: "HEDGE-NEWS-001",
                    title: qsTr("Spread między futures i spot BTC kurczy się"),
                    summary: qsTr("Arbitrażyści zamykają część pozycji, utrzymując neutralne nastawienie do kierunku rynku."),
                    source: "Arb Monitor",
                    sentiment: qsTr("Neutral"),
                    publishedAt: "2024-05-18T08:55:00+02:00",
                    url: "https://news.example.com/basis-tightens",
                },
                {
                    id: "HEDGE-NEWS-002",
                    title: qsTr("Opcje call na BTC z rosnącym popytem instytucji"),
                    summary: qsTr("Dealerzy raportują wzrost zapotrzebowania na call'e out-of-the-money jako zabezpieczenie."),
                    source: "Derivatives Desk",
                    sentiment: qsTr("Positive"),
                    publishedAt: "2024-05-18T08:42:00+02:00",
                    url: "https://news.example.com/call-demand",
                },
                {
                    id: "HEDGE-NEWS-003",
                    title: qsTr("Dolar stabilny przed publikacją danych CPI"),
                    summary: qsTr("Stabilizacja USD sprzyja utrzymaniu neutralnej ekspozycji na rynku krypto."),
                    source: "Macro Radar",
                    sentiment: qsTr("Neutral"),
                    publishedAt: "2024-05-18T08:30:00+02:00",
                    url: "https://news.example.com/usd-cpi-preview",
                },
            ],
            licenseStatus: {
                active: true,
                edition: "OEM Enterprise",
                licenseId: "DEMO-HEDGE",
                holderName: "Core Labs Hedge Demo",
                maintenanceActive: true,
                modules: ["hedge", "risk", "scheduler"],
                runtime: ["desktop-shell", "risk-service"],
            },
        },
    ];
}

function findPreset(presets, id) {
    if (!id)
        return null;
    for (let i = 0; i < presets.length; ++i) {
        if (presets[i].id === id)
            return presets[i];
    }
    return null;
}

function clonePreset(preset) {
    return JSON.parse(JSON.stringify(preset));
}
