"""Semantic contracts for the exact desktop release dependency authority."""

from __future__ import annotations

import json
import re
import tomllib
from pathlib import Path

import pytest
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

from scripts.ci.bootstrap_dependency import project_requirements
from scripts.ci.require_python311 import require_python311
from scripts.ci.validate_locked_resolution import locked_versions, validate_target_resolution

LOCK = Path("deploy/packaging/requirements-desktop.lock")
LOCK_TEXT = str(LOCK)
PYSIDE_STACK = {"pyside6", "pyside6-addons", "pyside6-essentials", "shiboken6"}
PIP_BOOTSTRAP = f"python scripts/ci/bootstrap_locked_pip.py {LOCK_TEXT}"


def _text(path: str) -> str:
    return Path(path).read_text(encoding="utf-8")


def test_release_workflows_install_and_audit_canonical_lock() -> None:
    windows = _text(".github/workflows/windows-build.yml")
    packaging = _text(".github/workflows/main.yml")
    cross_installer = _text("deploy/ci/github_actions_cross_installer.yml")
    audit = _text(".github/workflows/ci.yml")
    assert f"pip install --no-deps -r {LOCK_TEXT}" in windows
    assert packaging.count(f"pip install --no-deps -r {LOCK_TEXT}") == 3
    assert cross_installer.count(f"pip install --no-deps -r {LOCK_TEXT}") == 2
    assert packaging.count(f"validate_locked_resolution.py {LOCK_TEXT}") == 3
    assert cross_installer.count(f"validate_locked_resolution.py {LOCK_TEXT}") == 2
    assert f"--requirement {LOCK_TEXT}" in audit


def test_release_build_environments_have_no_loose_python_resolver_mutations() -> None:
    windows = _text(".github/workflows/windows-build.yml")
    packaging = _text(".github/workflows/main.yml")
    cross_installer = _text("deploy/ci/github_actions_cross_installer.yml")
    ci = _text(".github/workflows/ci.yml")
    wheelhouse_job = ci[ci.index("  prepare-wheelhouse:") : ci.index("  sbom:")]

    assert windows.count(PIP_BOOTSTRAP) == 1
    assert packaging.count(PIP_BOOTSTRAP) == 3
    assert cross_installer.count(PIP_BOOTSTRAP) == 2
    assert wheelhouse_job.count(PIP_BOOTSTRAP) == 1
    bootstrap = wheelhouse_job.index("- name: Bootstrap canonical pip")
    validation = wheelhouse_job.index("- name: Validate exact lock resolution")
    build = wheelhouse_job.index("- name: Build wheelhouse")
    assert bootstrap < validation < build
    for release_path in (windows, packaging, cross_installer, wheelhouse_job):
        assert "pip install --upgrade pip" not in release_path
        assert "pip install -U pip" not in release_path

    loose_tools = "python -m pip install pytest mypy ruff openpyxl"
    exact_tools = (
        "python -m pip install --no-deps -r deploy/packaging/requirements-windows-build-tools.lock"
    )
    assert loose_tools not in windows
    assert exact_tools in windows


def test_cross_installer_binds_release_install_to_bootstrapped_python() -> None:
    cross_installer = _text("deploy/ci/github_actions_cross_installer.yml")
    bound_install = f"python -m pip install --no-deps -r {LOCK_TEXT}"
    assert cross_installer.count(bound_install) == 2
    assert not re.search(
        rf"(?m)^\s+pip install --no-deps -r {re.escape(LOCK_TEXT)}$", cross_installer
    )


def test_windows_build_tooling_authority_is_exact_and_separate_from_runtime() -> None:
    tooling_lock = Path("deploy/packaging/requirements-windows-build-tools.lock")
    tooling = locked_versions(tooling_lock)
    assert tooling == {
        "colorama": "0.4.6",
        "iniconfig": "2.3.0",
        "pluggy": "1.6.0",
        "pytest": "9.0.2",
    }
    runtime = locked_versions(LOCK)
    assert "pytest" not in runtime


def test_canonical_pyside_stack_has_one_version_everywhere() -> None:
    locked = locked_versions(LOCK)
    versions = {locked[name] for name in PYSIDE_STACK}
    direct = locked_versions(Path("deploy/packaging/requirements-desktop.txt"))
    assert versions == {direct["pyside6"]}
    workflow = _text(".github/workflows/ci.yml")
    configured = re.search(r'^  PYSIDE6_VERSION: "([^"]+)"$', workflow, re.MULTILINE)
    assert configured and configured.group(1) in versions
    builder = _text("scripts/ci/build_wheelhouse.py")
    assert "--pyside6-version" not in builder
    assert "pyside_packages" not in builder
    assert "PYSIDE6_VERSION" not in _text(".github/workflows/main.yml")


def test_generator_rejects_every_non_python311_runtime() -> None:
    require_python311((3, 11, 9))
    for version in ((3, 10, 14), (3, 12, 0), (3, 14, 0)):
        with pytest.raises(SystemExit, match="requires Python 3.11"):
            require_python311(version)


def test_lock_generation_authority_is_self_consistent() -> None:
    header = LOCK.read_text(encoding="utf-8").splitlines()[:2]
    generator = _text("scripts/compile_desktop_lock.sh")
    assert header == [
        "# Generated by scripts/compile_desktop_lock.sh.",
        "# Python 3.11 is required; that script is the canonical generation authority.",
    ]
    assert "scripts/ci/require_python311.py" in generator
    assert "--no-header" in generator
    for package, version in {
        "click": "8.3.3",
        "GitPython": "3.1.60",
        "Pygments": "2.20.0",
        "idna": "3.15",
        "requests": "2.33.0",
        "urllib3": "2.8.0",
    }.items():
        assert f"--upgrade-package {package}=={version}" in generator


def test_cross_platform_jobs_validate_native_plan_before_wheelhouse() -> None:
    workflow = _text(".github/workflows/ci.yml")
    assert "os: [ubuntu-latest, windows-latest, macos-latest]" in workflow
    validation = f"validate_locked_resolution.py {LOCK_TEXT}"
    assert validation in workflow
    assert '--target ".[desktop]"' in workflow
    assert workflow.index(validation) < workflow.index("Build wheelhouse")
    assert f"--requirements {LOCK_TEXT}" in workflow
    builder = _text("scripts/ci/build_wheelhouse.py")
    assert "validate_desktop_resolution(args.python, args.requirements)" in builder
    assert builder.count(".[desktop]") == 1  # validator CLI compatibility only
    for local_target in (".[tools]", ".[dev]", ".[test,codegen]"):
        assert local_target not in builder


@pytest.mark.parametrize(
    ("name", "version", "expected"),
    [("foo", "1.2.3", "foo==1.2.3"), ("requests", "0.0.1", "requests==0.0.1")],
)
def test_actual_desktop_target_rejects_missing_or_mismatched_dependency(
    name: str, version: str, expected: str
) -> None:
    def fake_runner(command: list[str], *, check: bool) -> object:
        assert check is True
        report = Path(command[command.index("--report") + 1])
        if "--requirement" in command:
            assert command[command.index("--requirement") + 1] == LOCK_TEXT
            install = []
        else:
            assert command[command.index("--constraint") + 1] == LOCK_TEXT
            assert ".[desktop]" not in command
            assert "pyarrow>=21.0.0" in command
            assert "pyinstaller>=6.5" in command
            install = [
                {"requested": True, "metadata": {"name": name, "version": version}},
            ]
        report.write_text(json.dumps({"install": install}))
        return object()

    with pytest.raises(SystemExit, match=expected):
        validate_target_resolution(LOCK, ".[desktop]", runner=fake_runner)


def test_every_desktop_direct_dependency_is_in_canonical_lock() -> None:
    project = tomllib.loads(Path("pyproject.toml").read_text(encoding="utf-8"))["project"]
    desktop = project["optional-dependencies"]["desktop"]
    locked = locked_versions(LOCK)
    missing = [
        requirement.name
        for raw in desktop
        if canonicalize_name((requirement := Requirement(raw)).name) not in locked
    ]
    assert not missing


def test_every_build_system_requirement_is_satisfied_by_canonical_lock() -> None:
    build_requirements = tomllib.loads(Path("pyproject.toml").read_text(encoding="utf-8"))[
        "build-system"
    ]["requires"]
    locked = locked_versions(LOCK)
    for raw in build_requirements:
        requirement = Requirement(raw)
        name = canonicalize_name(requirement.name)
        assert name in locked
        assert requirement.specifier.contains(locked[name], prereleases=True)


def test_validator_reads_static_base_and_desktop_dependencies() -> None:
    requirements = project_requirements(Path("pyproject.toml"), ("desktop",))
    assert "pyarrow>=21.0.0" in requirements
    assert "pyinstaller>=6.5" in requirements


def test_every_lock_entry_is_an_exact_pin() -> None:
    for raw in LOCK.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        requirement = Requirement(line)
        assert canonicalize_name(requirement.name) in locked_versions(LOCK)
