"""Semantic contracts for the exact desktop release dependency authority."""

from __future__ import annotations

import json
import re
import tomllib
from pathlib import Path

import pytest
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

from scripts.ci.require_python311 import require_python311
from scripts.ci.validate_locked_resolution import locked_versions, validate_target_resolution

LOCK = Path("deploy/packaging/requirements-desktop.lock")
LOCK_TEXT = str(LOCK)
PYSIDE_STACK = {"pyside6", "pyside6-addons", "pyside6-essentials", "shiboken6"}


def _text(path: str) -> str:
    return Path(path).read_text(encoding="utf-8")


def test_release_workflows_install_and_audit_canonical_lock() -> None:
    windows = _text(".github/workflows/windows-build.yml")
    packaging = _text(".github/workflows/main.yml")
    cross_installer = _text("deploy/ci/github_actions_cross_installer.yml")
    audit = _text(".github/workflows/ci.yml")
    assert f"pip install --no-deps -r {LOCK_TEXT}" in windows
    assert packaging.count(f"pip install --no-deps -r {LOCK_TEXT}") == 3
    assert cross_installer.count(f"pip install --no-deps -r {LOCK_TEXT}") == 2
    assert packaging.count(f"validate_locked_resolution.py {LOCK_TEXT}") == 3
    assert cross_installer.count(f"validate_locked_resolution.py {LOCK_TEXT}") == 2
    assert f"--requirement {LOCK_TEXT}" in audit


def test_canonical_pyside_stack_has_one_version_everywhere() -> None:
    locked = locked_versions(LOCK)
    versions = {locked[name] for name in PYSIDE_STACK}
    direct = locked_versions(Path("deploy/packaging/requirements-desktop.txt"))
    assert versions == {direct["pyside6"]}
    workflow = _text(".github/workflows/ci.yml")
    configured = re.search(r'^  PYSIDE6_VERSION: "([^"]+)"$', workflow, re.MULTILINE)
    assert configured and configured.group(1) in versions
    builder = _text("scripts/ci/build_wheelhouse.py")
    assert "--pyside6-version" not in builder
    assert "pyside_packages" not in builder
    assert "PYSIDE6_VERSION" not in _text(".github/workflows/main.yml")


def test_generator_rejects_every_non_python311_runtime() -> None:
    require_python311((3, 11, 9))
    for version in ((3, 10, 14), (3, 12, 0), (3, 14, 0)):
        with pytest.raises(SystemExit, match="requires Python 3.11"):
            require_python311(version)


def test_lock_generation_authority_is_self_consistent() -> None:
    header = LOCK.read_text(encoding="utf-8").splitlines()[:2]
    generator = _text("scripts/compile_desktop_lock.sh")
    assert header == [
        "# Generated by scripts/compile_desktop_lock.sh.",
        "# Python 3.11 is required; that script is the canonical generation authority.",
    ]
    assert "scripts/ci/require_python311.py" in generator
    assert "--no-header" in generator
    for package, version in {
        "click": "8.3.3",
        "GitPython": "3.1.60",
        "Pygments": "2.20.0",
        "idna": "3.15",
        "requests": "2.33.0",
        "urllib3": "2.8.0",
    }.items():
        assert f"--upgrade-package {package}=={version}" in generator


def test_cross_platform_jobs_validate_native_plan_before_wheelhouse() -> None:
    workflow = _text(".github/workflows/ci.yml")
    assert "os: [ubuntu-latest, windows-latest, macos-latest]" in workflow
    validation = f"validate_locked_resolution.py {LOCK_TEXT}"
    assert validation in workflow
    assert '--target ".[desktop]"' in workflow
    assert workflow.index(validation) < workflow.index("Build wheelhouse")
    assert f"--requirements {LOCK_TEXT}" in workflow
    builder = _text("scripts/ci/build_wheelhouse.py")
    assert "validate_desktop_resolution(args.python, args.requirements)" in builder


@pytest.mark.parametrize(
    ("name", "version", "expected"),
    [("foo", "1.2.3", "foo==1.2.3"), ("requests", "0.0.1", "requests==0.0.1")],
)
def test_actual_desktop_target_rejects_missing_or_mismatched_dependency(
    name: str, version: str, expected: str
) -> None:
    def fake_runner(command: list[str], *, check: bool) -> object:
        assert check is True
        assert command[-1] == ".[desktop]"
        assert command[command.index("--constraint") + 1] == LOCK_TEXT
        report = Path(command[command.index("--report") + 1])
        report.write_text(
            json.dumps(
                {
                    "install": [
                        {
                            "requested": True,
                            "metadata": {"name": "dudzian-bot", "version": "0.1.0"},
                        },
                        {"requested": False, "metadata": {"name": name, "version": version}},
                    ]
                }
            )
        )
        return object()

    with pytest.raises(SystemExit, match=expected):
        validate_target_resolution(LOCK, ".[desktop]", runner=fake_runner)


def test_every_desktop_direct_dependency_is_in_canonical_lock() -> None:
    project = tomllib.loads(Path("pyproject.toml").read_text(encoding="utf-8"))["project"]
    desktop = project["optional-dependencies"]["desktop"]
    locked = locked_versions(LOCK)
    missing = [
        requirement.name
        for raw in desktop
        if canonicalize_name((requirement := Requirement(raw)).name) not in locked
    ]
    assert not missing


def test_every_lock_entry_is_an_exact_pin() -> None:
    for raw in LOCK.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        requirement = Requirement(line)
        assert canonicalize_name(requirement.name) in locked_versions(LOCK)
