listen_addresses = ''
unix_socket_directories = '/run/postgresql'
port = 5432
fsync = on
synchronous_commit = on
hba_file = '/etc/cryptohunter/postgresql/pg_hba.conf'
ident_file = '/etc/cryptohunter/postgresql/pg_ident.conf'
