"""FUNCTIONAL-PREVIEW-13.0 Block K observability audit rollback soak contract.

Pure-data contract for starting Block K from the accepted Block J closure audit.
This module only assembles static dictionaries and does not activate runtime
observability, audit writing/exporting, rollback, soak, networking, filesystem
I/O, QML, bridge, or order flow.
"""

from __future__ import annotations

from typing import Any, Final

from ui.pyside_app.preview_block_j_closure_audit import build_preview_block_j_closure_audit

PREVIEW_OBSERVABILITY_AUDIT_ROLLBACK_SOAK_CONTRACT_SCHEMA_VERSION: Final[str] = (
    "preview_observability_audit_rollback_soak_contract.v1"
)
PREVIEW_OBSERVABILITY_AUDIT_ROLLBACK_SOAK_CONTRACT_KIND: Final[str] = (
    "functional_preview_block_k_observability_audit_rollback_soak_contract"
)
BLOCK_ID: Final[str] = "K"
STEP_ID: Final[str] = "13.0"
OBSERVABILITY_AUDIT_ROLLBACK_SOAK_CONTRACT_STATUS: Final[str] = (
    "observability_audit_rollback_soak_contract_ready_no_runtime"
)
OBSERVABILITY_AUDIT_ROLLBACK_SOAK_CONTRACT_DECISION: Final[str] = (
    "START_BLOCK_K_WITH_CONTRACT_ONLY_NO_RUNTIME_NO_EXPORTS_NO_ORDER_FLOW"
)
READY_FOR_BLOCK_K_1: Final[bool] = True
NEXT_STEP: Final[str] = "FUNCTIONAL-PREVIEW-13.1"
NEXT_STEP_TITLE: Final[str] = "OBSERVABILITY READ MODEL"
STATUS: Final[str] = "ready_for_functional_preview_13_1_observability_read_model"

_BLOCK_J_SAFE_KEYS: Final[list[str]] = [
    "schema_version",
    "block_j_closure_audit_kind",
    "block_j_closure_audit_status",
    "block_j_closure_audit_decision",
    "ready_for_next_block",
    "next_block",
    "next_step",
    "next_step_title",
    "closure_line",
    "status",
]

_FALSE_SCOPE_FLAGS: Final[list[str]] = [
    "observability_runtime_allowed_now",
    "audit_writer_allowed_now",
    "audit_export_allowed_now",
    "rollback_execution_allowed_now",
    "soak_runtime_allowed_now",
    "metrics_export_allowed_now",
    "log_file_read_allowed_now",
    "log_file_write_allowed_now",
    "filesystem_io_allowed_now",
    "runtime_enforcement_allowed_now",
    "risk_decision_runtime_allowed_now",
    "limit_enforcement_runtime_allowed_now",
    "kill_switch_runtime_allowed_now",
    "manual_trigger_allowed_now",
    "automatic_trigger_allowed_now",
    "kill_switch_state_mutation_allowed_now",
    "order_generation_allowed_now",
    "order_submission_allowed_now",
    "order_cancel_allowed_now",
    "order_replace_allowed_now",
    "position_mutation_allowed_now",
    "private_endpoint_access_allowed_now",
    "account_read_allowed_now",
    "balance_read_allowed_now",
    "positions_read_allowed_now",
    "orders_read_allowed_now",
    "fills_read_allowed_now",
    "market_data_read_allowed_now",
    "network_io_allowed_now",
    "dns_lookup_allowed_now",
    "http_request_allowed_now",
    "websocket_allowed_now",
    "adapter_instantiation_allowed_now",
    "adapter_wiring_allowed_now",
    "scheduler_allowed_now",
    "config_file_read_allowed_now",
    "config_discovery_allowed_now",
    "yaml_parse_allowed_now",
    "json_parse_allowed_now",
    "environment_variable_read_allowed_now",
    "credential_secret_read_allowed_now",
    "credential_validation_allowed_now",
    "secure_store_read_allowed_now",
    "secure_store_write_allowed_now",
    "qml_changes_allowed",
    "new_qml_method_calls_allowed",
    "bridge_api_changes_allowed",
    "exe_packaging_in_scope",
    "bat_productization_allowed",
]

_PRINCIPLE_IDS: Final[list[str]] = [
    "observability_before_runtime",
    "audit_before_side_effects",
    "rollback_before_activation",
    "soak_before_runtime_expansion",
    "fail_closed_on_missing_audit",
    "no_runtime_without_explicit_gate",
    "no_export_without_explicit_gate",
    "no_filesystem_io_without_explicit_gate",
    "no_network_without_explicit_gate",
    "live_trading_stays_blocked",
]

BLOCKED_BLOCK_K_CONTRACT_CAPABILITIES: Final[list[str]] = [
    "observability runtime collection",
    "metrics export",
    "log file read",
    "log file write",
    "audit writer",
    "audit export",
    "rollback execution",
    "runtime shutdown",
    "soak runtime",
    "soak scheduler",
    "filesystem I/O",
    "risk runtime enforcement",
    "limit runtime enforcement",
    "kill switch runtime trigger",
    "manual kill switch trigger",
    "automatic kill switch trigger",
    "kill switch state mutation",
    "order generation",
    "order submission",
    "order cancel",
    "order replace",
    "position mutation",
    "private endpoint access",
    "account read",
    "balance read",
    "positions read",
    "orders read",
    "fills read",
    "market data read",
    "adapter instantiation",
    "adapter runtime wiring",
    "runtime loop",
    "scheduler",
    "network I/O",
    "DNS lookup",
    "HTTP request",
    "WebSocket connection",
    "credential read",
    "secret read",
    "secure store read",
    "secure store write",
    "config file read",
    "config discovery",
    "YAML parse",
    "JSON parse",
    "environment variable read",
    "TradingController change",
    "DecisionEnvelope change",
    "QML action dispatch",
    "bridge API changes",
    "PyInstaller/EXE packaging",
]

SOURCE_BOUNDARIES: Final[list[str]] = [
    "no PySide import",
    "no QML import",
    "no runtime loop import",
    "no scheduler import",
    "no TradingController import",
    "no DecisionEnvelope import",
    "no strategy/AI/scoring/recommendation import",
    "no order module import",
    "no live adapter import",
    "no testnet adapter import",
    "no sandbox adapter import",
    "no exchange adapter runtime import",
    "no account module import",
    "no secrets module import",
    "no security store import",
    "no observability runtime import",
    "no logger/exporter runtime import",
    "no metrics exporter import",
    "no rollback runner import",
    "no soak runner import",
    "no filesystem I/O",
    "no log file read",
    "no log file write",
    "no audit write",
    "no audit export",
    "no config file read",
    "no config discovery",
    "no YAML parse",
    "no JSON parse",
    "no environment variable read",
    "no credential read",
    "no credential validation",
    "no secret material handling",
    "no secure store read",
    "no secure store write",
    "no real market data read",
    "no private endpoint access",
    "no account read",
    "no balance read",
    "no positions read",
    "no orders read",
    "no fills read",
    "no order generation",
    "no order submission",
    "no order cancel",
    "no order replace",
    "no position mutation",
    "no network I/O",
    "no DNS lookup",
    "no HTTP request",
    "no WebSocket connection",
    "no QML changes",
    "no bridge API changes",
    "no .bat changes",
    "no app.py changes",
    "no dependency declarations changes",
    "no workflow changes",
]


def _subset(source: dict[str, Any], keys: list[str]) -> dict[str, Any]:
    return {key: source[key] for key in keys}


def _principles() -> list[dict[str, Any]]:
    return [
        {
            "principle_id": principle_id,
            "description": f"Block K contract principle: {principle_id}.",
            "required_for_next_step": True,
            "runtime_enabled_now": False,
            "order_flow_enabled_now": False,
            "safe_for_offline_tests": True,
        }
        for principle_id in _PRINCIPLE_IDS
    ]


def build_preview_observability_audit_rollback_soak_contract() -> dict[str, Any]:
    """Build the static Block K observability/audit/rollback/soak contract payload."""
    block_j_closure = build_preview_block_j_closure_audit()
    return {
        "schema_version": PREVIEW_OBSERVABILITY_AUDIT_ROLLBACK_SOAK_CONTRACT_SCHEMA_VERSION,
        "observability_audit_rollback_soak_contract_kind": PREVIEW_OBSERVABILITY_AUDIT_ROLLBACK_SOAK_CONTRACT_KIND,
        "block": BLOCK_ID,
        "step": STEP_ID,
        "observability_audit_rollback_soak_contract_status": OBSERVABILITY_AUDIT_ROLLBACK_SOAK_CONTRACT_STATUS,
        "observability_audit_rollback_soak_contract_decision": OBSERVABILITY_AUDIT_ROLLBACK_SOAK_CONTRACT_DECISION,
        "ready_for_block_k_1": READY_FOR_BLOCK_K_1,
        "next_step": NEXT_STEP,
        "next_step_title": NEXT_STEP_TITLE,
        "block_j_closure_reference": _subset(block_j_closure, _BLOCK_J_SAFE_KEYS),
        "block_k_contract_scope": {
            "scope_name": "observability_audit_rollback_soak_contract",
            "contract_only": True,
            "starts_block_k": True,
            "derived_from_block_j_closure_12_5": True,
            **{key: False for key in _FALSE_SCOPE_FLAGS},
            "exe_direction_preserved": True,
        },
        "block_k_contract_principles": _principles(),
        "observability_contract": {
            "contract_id": "block_k_observability_contract",
            "read_model_required": True,
            "runtime_metrics_collection_allowed_now": False,
            "metrics_export_allowed_now": False,
            "log_file_read_allowed_now": False,
            "log_file_write_allowed_now": False,
            "filesystem_io_allowed_now": False,
            "network_io_allowed_now": False,
            "ui_surface_allowed_now": False,
            "next_step": "FUNCTIONAL-PREVIEW-13.1",
            "next_step_title": "OBSERVABILITY READ MODEL",
        },
        "audit_contract": {
            "contract_id": "block_k_audit_contract",
            "audit_envelope_required": True,
            "audit_writer_allowed_now": False,
            "audit_export_allowed_now": False,
            "filesystem_io_allowed_now": False,
            "network_io_allowed_now": False,
            "credential_secret_read_allowed_now": False,
            "next_step": "FUNCTIONAL-PREVIEW-13.2",
            "next_step_title": "AUDIT ENVELOPE READ MODEL",
        },
        "rollback_contract": {
            "contract_id": "block_k_rollback_contract",
            "rollback_plan_required": True,
            "rollback_execution_allowed_now": False,
            "state_mutation_allowed_now": False,
            "runtime_shutdown_allowed_now": False,
            "order_cancel_allowed_now": False,
            "private_endpoint_access_allowed_now": False,
            "next_step": "FUNCTIONAL-PREVIEW-13.3",
            "next_step_title": "ROLLBACK READ MODEL",
        },
        "soak_contract": {
            "contract_id": "block_k_soak_contract",
            "soak_plan_required": True,
            "soak_runtime_allowed_now": False,
            "scheduler_allowed_now": False,
            "runtime_loop_allowed_now": False,
            "network_io_allowed_now": False,
            "order_flow_allowed_now": False,
            "private_endpoint_access_allowed_now": False,
            "next_step": "FUNCTIONAL-PREVIEW-13.4",
            "next_step_title": "SOAK READ MODEL",
        },
        "block_k_dependency_matrix": {
            "source_block": "BLOK J",
            "source_step": "FUNCTIONAL-PREVIEW-12.5",
            "target_block": "BLOK K",
            "target_step": "FUNCTIONAL-PREVIEW-13.0",
            "requires_block_j_closure": True,
            "requires_observability_contract": True,
            "requires_audit_contract": True,
            "requires_rollback_contract": True,
            "requires_soak_contract": True,
            "requires_order_flow_blocked": True,
            "requires_private_endpoint_blocked": True,
            "requires_network_blocked_until_future_gate": True,
            "requires_live_trading_blocked": True,
            "ready_for_13_1_observability_read_model": True,
        },
        "blocked_block_k_contract_capabilities": BLOCKED_BLOCK_K_CONTRACT_CAPABILITIES,
        "block_k_contract_boundaries": {
            key: True
            for key in [
                "block_k_contract_is_static",
                "block_k_contract_starts_block_k",
                "block_k_contract_is_derived_from_block_j_closure",
                "block_k_contract_can_feed_13_1_observability_read_model",
                "block_k_contract_can_feed_future_audit_rollback_soak_steps",
                "block_k_contract_cannot_feed_runtime_directly",
                "block_k_contract_cannot_collect_metrics",
                "block_k_contract_cannot_export_metrics",
                "block_k_contract_cannot_read_logs",
                "block_k_contract_cannot_write_logs",
                "block_k_contract_cannot_write_audit",
                "block_k_contract_cannot_export_audit",
                "block_k_contract_cannot_execute_rollback",
                "block_k_contract_cannot_run_soak",
                "block_k_contract_cannot_touch_filesystem",
                "block_k_contract_cannot_enable_runtime",
                "block_k_contract_cannot_enforce_limits",
                "block_k_contract_cannot_trigger_kill_switch",
                "block_k_contract_cannot_mutate_kill_switch_state",
                "block_k_contract_cannot_generate_orders",
                "block_k_contract_cannot_submit_orders",
                "block_k_contract_cannot_cancel_orders",
                "block_k_contract_cannot_replace_orders",
                "block_k_contract_cannot_access_private_endpoints",
                "block_k_contract_cannot_read_account",
                "block_k_contract_balance_read_blocked",
                "block_k_contract_cannot_read_positions",
                "block_k_contract_cannot_read_orders",
                "block_k_contract_cannot_read_fills",
                "block_k_contract_cannot_read_market_data",
                "block_k_contract_cannot_open_network_connection",
                "block_k_contract_cannot_perform_dns_lookup",
                "block_k_contract_cannot_perform_http_request",
                "block_k_contract_cannot_open_websocket",
                "block_k_contract_cannot_read_credentials",
                "block_k_contract_cannot_read_secrets",
                "block_k_contract_cannot_read_secure_store",
                "block_k_contract_cannot_change_qml_or_bridge",
            ]
        },
        "non_activation_evidence": {
            "block_j_closure_12_5_read": True,
            "block_k_contract_built": True,
            **{
                key: False
                for key in [
                    "observability_runtime_started",
                    "metrics_collected",
                    "metrics_exported",
                    "log_file_read",
                    "log_file_written",
                    "audit_writer_started",
                    "audit_exported",
                    "rollback_executed",
                    "runtime_shutdown_executed",
                    "soak_runtime_started",
                    "soak_scheduler_started",
                    "filesystem_io_performed",
                    "risk_runtime_enforcement_started",
                    "limit_runtime_enforcement_started",
                    "kill_switch_runtime_trigger_enabled",
                    "manual_kill_switch_trigger_enabled",
                    "automatic_kill_switch_trigger_enabled",
                    "kill_switch_state_mutated",
                    "order_generated",
                    "order_submitted",
                    "order_cancelled",
                    "order_replaced",
                    "position_mutated",
                    "private_endpoint_accessed",
                    "account_read_performed",
                    "balance_read_performed",
                    "positions_read_performed",
                    "orders_read_performed",
                    "fills_read_performed",
                    "market_data_read_performed",
                    "adapter_instantiated",
                    "adapter_wired_to_runtime",
                    "runtime_started",
                    "scheduler_started",
                    "network_io_performed",
                    "dns_lookup_performed",
                    "http_request_performed",
                    "websocket_opened",
                    "credentials_read",
                    "secrets_read",
                    "secure_store_read",
                    "secure_store_write",
                    "config_files_read",
                    "config_discovery_performed",
                    "yaml_parsed",
                    "json_parsed",
                    "environment_variables_read",
                    "trading_controller_touched",
                    "decision_envelope_touched",
                    "qml_changed",
                    "bridge_api_changed",
                ]
            },
        },
        "source_boundaries": SOURCE_BOUNDARIES,
        "future_steps": [
            "functional_preview_13_1_observability_read_model",
            "functional_preview_13_2_audit_envelope_read_model",
            "functional_preview_13_3_rollback_read_model",
            "functional_preview_13_4_soak_read_model",
            "functional_preview_13_5_observability_audit_rollback_soak_gate_matrix",
            "functional_preview_13_6_block_k_closure_audit",
        ],
        "status": STATUS,
    }
