"""FUNCTIONAL-PREVIEW-13.6 Block K closure audit.

Pure-data Block K closure audit built from safe static previews for 13.0
through 13.5. It closes Block K without activating runtime, writers,
exporters, rollback, soak, orders, private endpoints, network access,
filesystem access, QML, or bridge surfaces.
"""

from __future__ import annotations

from typing import Any, Final

from ui.pyside_app.preview_audit_envelope_read_model import (
    build_preview_audit_envelope_read_model,
)
from ui.pyside_app.preview_observability_audit_rollback_soak_contract import (
    build_preview_observability_audit_rollback_soak_contract,
)
from ui.pyside_app.preview_observability_audit_rollback_soak_gate_matrix import (
    build_preview_observability_audit_rollback_soak_gate_matrix,
)
from ui.pyside_app.preview_observability_read_model import build_preview_observability_read_model
from ui.pyside_app.preview_rollback_read_model import build_preview_rollback_read_model
from ui.pyside_app.preview_soak_read_model import build_preview_soak_read_model

PREVIEW_BLOCK_K_CLOSURE_AUDIT_SCHEMA_VERSION: Final[str] = "preview_block_k_closure_audit.v1"
PREVIEW_BLOCK_K_CLOSURE_AUDIT_KIND: Final[str] = "functional_preview_block_k_closure_audit"
BLOCK_ID: Final[str] = "K"
STEP_ID: Final[str] = "13.6"
BLOCK_K_CLOSURE_AUDIT_STATUS: Final[str] = (
    "block_k_observability_audit_rollback_soak_complete_ready_for_next_block"
)
BLOCK_K_CLOSURE_AUDIT_DECISION: Final[str] = (
    "CLOSE_BLOCK_K_OBSERVABILITY_AUDIT_ROLLBACK_SOAK_NO_RUNTIME_NO_EXPORTS_NO_IO"
)
READY_FOR_NEXT_BLOCK: Final[bool] = True
NEXT_BLOCK: Final[str] = "BLOK L — RUNTIME ACTIVATION / LIVE CANARY GATES"
NEXT_STEP: Final[str] = "FUNCTIONAL-PREVIEW-14.0"
NEXT_STEP_TITLE: Final[str] = "BLOK L — RUNTIME ACTIVATION CONTRACT"
CLOSURE_LINE: Final[str] = "BLOK GOTOWY — PRZECHODZIMY DO KOLEJNEGO BLOKU"
STATUS: Final[str] = "ready_for_functional_preview_14_0_runtime_activation_contract"

_TOP_LEVEL_FIELDS: Final[list[str]] = [
    "schema_version",
    "block_k_closure_audit_kind",
    "block",
    "step",
    "block_k_closure_audit_status",
    "block_k_closure_audit_decision",
    "ready_for_next_block",
    "next_block",
    "next_step",
    "next_step_title",
    "closure_line",
    "block_k_contract_reference",
    "observability_read_model_reference",
    "audit_envelope_read_model_reference",
    "rollback_read_model_reference",
    "soak_read_model_reference",
    "gate_matrix_reference",
    "block_k_closure_scope",
    "block_k_completed_steps",
    "block_k_completion_matrix",
    "block_k_safety_summary",
    "observability_audit_rollback_soak_capability_closure",
    "runtime_order_private_network_closure",
    "blocked_block_k_capabilities",
    "block_k_source_boundaries",
    "non_activation_evidence",
    "next_block_entry_requirements",
    "future_blocks",
    "status",
]
_BLOCK_K_KEYS: Final[list[str]] = [
    "schema_version",
    "observability_audit_rollback_soak_contract_kind",
    "observability_audit_rollback_soak_contract_status",
    "observability_audit_rollback_soak_contract_decision",
    "ready_for_block_k_1",
    "next_step",
    "next_step_title",
    "status",
]
_OBSERVABILITY_KEYS: Final[list[str]] = [
    "schema_version",
    "observability_read_model_kind",
    "observability_read_model_status",
    "observability_read_model_decision",
    "ready_for_block_k_2",
    "next_step",
    "next_step_title",
    "status",
]
_AUDIT_KEYS: Final[list[str]] = [
    "schema_version",
    "audit_envelope_read_model_kind",
    "audit_envelope_read_model_status",
    "audit_envelope_read_model_decision",
    "ready_for_block_k_3",
    "next_step",
    "next_step_title",
    "status",
]
_ROLLBACK_KEYS: Final[list[str]] = [
    "schema_version",
    "rollback_read_model_kind",
    "rollback_read_model_status",
    "rollback_read_model_decision",
    "ready_for_block_k_4",
    "next_step",
    "next_step_title",
    "status",
]
_SOAK_KEYS: Final[list[str]] = [
    "schema_version",
    "soak_read_model_kind",
    "soak_read_model_status",
    "soak_read_model_decision",
    "ready_for_block_k_5",
    "next_step",
    "next_step_title",
    "status",
]
_GATE_KEYS: Final[list[str]] = [
    "schema_version",
    "observability_audit_rollback_soak_gate_matrix_kind",
    "observability_audit_rollback_soak_gate_matrix_status",
    "observability_audit_rollback_soak_gate_matrix_decision",
    "ready_for_block_k_6",
    "next_step",
    "next_step_title",
    "status",
]

_FALSE_SCOPE_FLAGS: Final[list[str]] = [
    "runtime_activation_allowed_now",
    "block_l_implementation_allowed_now",
    "live_canary_allowed_now",
    "testnet_runtime_allowed_now",
    "paper_runtime_activation_allowed_now",
    "runtime_gate_execution_allowed_now",
    "gate_state_mutation_allowed_now",
    "observability_runtime_allowed_now",
    "audit_writer_allowed_now",
    "audit_export_allowed_now",
    "rollback_execution_allowed_now",
    "runtime_shutdown_allowed_now",
    "soak_runtime_allowed_now",
    "soak_scheduler_allowed_now",
    "runtime_loop_allowed_now",
    "metrics_collection_allowed_now",
    "metrics_export_allowed_now",
    "log_file_read_allowed_now",
    "log_file_write_allowed_now",
    "audit_file_read_allowed_now",
    "audit_file_write_allowed_now",
    "filesystem_io_allowed_now",
    "state_mutation_allowed_now",
    "order_cancel_allowed_now",
    "order_replace_allowed_now",
    "order_generation_allowed_now",
    "order_submission_allowed_now",
    "position_mutation_allowed_now",
    "private_endpoint_access_allowed_now",
    "account_read_allowed_now",
    "balance_read_allowed_now",
    "positions_read_allowed_now",
    "orders_read_allowed_now",
    "fills_read_allowed_now",
    "market_data_read_allowed_now",
    "network_io_allowed_now",
    "dns_lookup_allowed_now",
    "http_request_allowed_now",
    "websocket_allowed_now",
    "adapter_instantiation_allowed_now",
    "adapter_wiring_allowed_now",
    "scheduler_allowed_now",
    "config_file_read_allowed_now",
    "config_discovery_allowed_now",
    "yaml_parse_allowed_now",
    "json_parse_allowed_now",
    "environment_variable_read_allowed_now",
    "credential_secret_read_allowed_now",
    "credential_validation_allowed_now",
    "secure_store_read_allowed_now",
    "secure_store_write_allowed_now",
    "qml_changes_allowed",
    "new_qml_method_calls_allowed",
    "bridge_api_changes_allowed",
    "exe_packaging_in_scope",
    "bat_productization_allowed",
]
_COMPLETED: Final[list[tuple[str, str, str, str]]] = [
    (
        "functional_preview_13_0_contract",
        "FUNCTIONAL-PREVIEW-13.0",
        "Observability Audit Rollback Soak Contract",
        "ready_for_block_k_1",
    ),
    (
        "functional_preview_13_1_observability_read_model",
        "FUNCTIONAL-PREVIEW-13.1",
        "Observability Read Model",
        "ready_for_block_k_2",
    ),
    (
        "functional_preview_13_2_audit_envelope_read_model",
        "FUNCTIONAL-PREVIEW-13.2",
        "Audit Envelope Read Model",
        "ready_for_block_k_3",
    ),
    (
        "functional_preview_13_3_rollback_read_model",
        "FUNCTIONAL-PREVIEW-13.3",
        "Rollback Read Model",
        "ready_for_block_k_4",
    ),
    (
        "functional_preview_13_4_soak_read_model",
        "FUNCTIONAL-PREVIEW-13.4",
        "Soak Read Model",
        "ready_for_block_k_5",
    ),
    (
        "functional_preview_13_5_gate_matrix",
        "FUNCTIONAL-PREVIEW-13.5",
        "Observability Audit Rollback Soak Gate Matrix",
        "ready_for_block_k_6",
    ),
    (
        "functional_preview_13_6_closure_audit",
        "FUNCTIONAL-PREVIEW-13.6",
        "Block K Closure Audit",
        "ready_for_next_block",
    ),
]
BLOCKED_BLOCK_K_CAPABILITIES: Final[list[str]] = [
    "Block L implementation",
    "runtime activation",
    "runtime gate execution",
    "gate state mutation",
    "live canary",
    "testnet runtime",
    "paper runtime activation",
    "observability runtime collection",
    "metrics collection",
    "metrics export",
    "audit writer",
    "audit export",
    "audit file read",
    "audit file write",
    "log file read",
    "log file write",
    "rollback execution",
    "runtime shutdown",
    "soak runtime",
    "soak scheduler",
    "runtime loop",
    "wall-clock runtime measurement",
    "stability probe",
    "state mutation",
    "order generation",
    "order submission",
    "order cancel",
    "order replace",
    "position mutation",
    "private endpoint access",
    "account read",
    "balance read",
    "positions read",
    "orders read",
    "fills read",
    "market data read",
    "adapter instantiation",
    "adapter runtime wiring",
    "scheduler",
    "filesystem I/O",
    "network I/O",
    "DNS lookup",
    "HTTP request",
    "WebSocket connection",
    "credential read",
    "secret read",
    "secure store read",
    "secure store write",
    "config file read",
    "config discovery",
    "YAML parse",
    "JSON parse",
    "environment variable read",
    "TradingController change",
    "DecisionEnvelope change",
    "QML action dispatch",
    "bridge API changes",
    "PyInstaller/EXE packaging",
]
BLOCK_K_SOURCE_BOUNDARIES: Final[list[str]] = [
    "no PySide import",
    "no QML import",
    "no runtime loop import",
    "no scheduler import",
    "no TradingController import",
    "no DecisionEnvelope import",
    "no strategy/AI/scoring/recommendation import",
    "no order module import",
    "no live adapter import",
    "no testnet adapter import",
    "no sandbox adapter import",
    "no exchange adapter runtime import",
    "no account module import",
    "no secrets module import",
    "no security store import",
    "no observability runtime import",
    "no logger/exporter runtime import",
    "no metrics exporter import",
    "no audit writer import",
    "no audit exporter import",
    "no rollback runner import",
    "no rollback executor import",
    "no soak runner import",
    "no soak scheduler import",
    "no filesystem I/O",
    "no audit file read",
    "no audit file write",
    "no log file read",
    "no log file write",
    "no audit write",
    "no audit export",
    "no runtime shutdown",
    "no state mutation",
    "no wall-clock runtime measurement",
    "no stability probe",
    "no config file read",
    "no config discovery",
    "no YAML parse",
    "no JSON parse",
    "no environment variable read",
    "no credential read",
    "no credential validation",
    "no secret material handling",
    "no secure store read",
    "no secure store write",
    "no real market data read",
    "no private endpoint access",
    "no account read",
    "no balance read",
    "no positions read",
    "no orders read",
    "no fills read",
    "no order generation",
    "no order submission",
    "no order cancel",
    "no order replace",
    "no position mutation",
    "no gate execution",
    "no gate state mutation",
    "no runtime activation",
    "no Block L implementation",
    "no live canary",
    "no testnet runtime",
    "no paper runtime activation",
    "no network I/O",
    "no DNS lookup",
    "no HTTP request",
    "no WebSocket connection",
    "no QML changes",
    "no bridge API changes",
    "no .bat changes",
    "no app.py changes",
    "no dependency declarations changes",
    "no workflow changes",
]


def _pick(source: dict[str, Any], keys: list[str]) -> dict[str, Any]:
    return {key: source[key] for key in keys}


def _completed_steps() -> list[dict[str, Any]]:
    return [
        {
            "completed_step_id": i,
            "functional_preview_step": s,
            "title": t,
            "completion_state": "complete",
            "ready_flag": r,
            "runtime_activation_allowed_now": False,
            "order_flow_allowed_now": False,
            "private_endpoint_access_allowed_now": False,
            "network_io_allowed_now": False,
            "safe_for_offline_tests": True,
            "notes": f"{t} completed as static Block K preview source.",
        }
        for i, s, t, r in _COMPLETED
    ]


def build_preview_block_k_closure_audit() -> dict[str, Any]:
    contract = _pick(build_preview_observability_audit_rollback_soak_contract(), _BLOCK_K_KEYS)
    observability = _pick(build_preview_observability_read_model(), _OBSERVABILITY_KEYS)
    audit = _pick(build_preview_audit_envelope_read_model(), _AUDIT_KEYS)
    rollback = _pick(build_preview_rollback_read_model(), _ROLLBACK_KEYS)
    soak = _pick(build_preview_soak_read_model(), _SOAK_KEYS)
    gate = _pick(build_preview_observability_audit_rollback_soak_gate_matrix(), _GATE_KEYS)
    completed = _completed_steps()
    completed_ids = [item["completed_step_id"] for item in completed]
    ready_flags = [item["ready_flag"] for item in completed]
    scope = {
        "scope_name": "block_k_closure_audit",
        "closure_audit_only": True,
        "closes_block_k": True,
        "derived_from_block_k_contract_13_0": True,
        "derived_from_observability_read_model_13_1": True,
        "derived_from_audit_envelope_read_model_13_2": True,
        "derived_from_rollback_read_model_13_3": True,
        "derived_from_soak_read_model_13_4": True,
        "derived_from_gate_matrix_13_5": True,
        "next_block_is_block_l": True,
        **{flag: False for flag in _FALSE_SCOPE_FLAGS},
        "exe_direction_preserved": True,
    }
    non_activation = {
        "block_k_contract_13_0_read": True,
        "observability_read_model_13_1_read": True,
        "audit_envelope_read_model_13_2_read": True,
        "rollback_read_model_13_3_read": True,
        "soak_read_model_13_4_read": True,
        "gate_matrix_13_5_read": True,
        "block_k_closure_audit_built": True,
        **{
            key: False
            for key in [
                "block_l_implemented",
                "runtime_activation_started",
                "runtime_gate_executed",
                "gate_state_mutated",
                "live_canary_started",
                "testnet_runtime_started",
                "paper_runtime_activated",
                "observability_runtime_started",
                "metrics_collected",
                "metrics_exported",
                "audit_writer_started",
                "audit_exported",
                "audit_file_read",
                "audit_file_written",
                "log_file_read",
                "log_file_written",
                "rollback_executed",
                "runtime_shutdown_executed",
                "soak_runtime_started",
                "soak_scheduler_started",
                "runtime_loop_started",
                "wall_clock_runtime_measured",
                "stability_probe_started",
                "state_mutated",
                "order_generated",
                "order_submitted",
                "order_cancelled",
                "order_replaced",
                "position_mutated",
                "private_endpoint_accessed",
                "account_read_performed",
                "balance_read_performed",
                "positions_read_performed",
                "orders_read_performed",
                "fills_read_performed",
                "market_data_read_performed",
                "adapter_instantiated",
                "adapter_wired_to_runtime",
                "scheduler_started",
                "filesystem_io_performed",
                "network_io_performed",
                "dns_lookup_performed",
                "http_request_performed",
                "websocket_opened",
                "credentials_read",
                "secrets_read",
                "secure_store_read",
                "secure_store_write",
                "config_files_read",
                "config_discovery_performed",
                "yaml_parsed",
                "json_parsed",
                "environment_variables_read",
                "trading_controller_touched",
                "decision_envelope_touched",
                "qml_changed",
                "bridge_api_changed",
            ]
        },
    }
    result = {
        "schema_version": PREVIEW_BLOCK_K_CLOSURE_AUDIT_SCHEMA_VERSION,
        "block_k_closure_audit_kind": PREVIEW_BLOCK_K_CLOSURE_AUDIT_KIND,
        "block": BLOCK_ID,
        "step": STEP_ID,
        "block_k_closure_audit_status": BLOCK_K_CLOSURE_AUDIT_STATUS,
        "block_k_closure_audit_decision": BLOCK_K_CLOSURE_AUDIT_DECISION,
        "ready_for_next_block": READY_FOR_NEXT_BLOCK,
        "next_block": NEXT_BLOCK,
        "next_step": NEXT_STEP,
        "next_step_title": NEXT_STEP_TITLE,
        "closure_line": CLOSURE_LINE,
        "block_k_contract_reference": contract,
        "observability_read_model_reference": observability,
        "audit_envelope_read_model_reference": audit,
        "rollback_read_model_reference": rollback,
        "soak_read_model_reference": soak,
        "gate_matrix_reference": gate,
        "block_k_closure_scope": scope,
        "block_k_completed_steps": completed,
        "block_k_completion_matrix": {
            "completed_step_ids": completed_ids,
            "source_step_ids": completed_ids[:6],
            "closure_step_id": "functional_preview_13_6_closure_audit",
            "ready_flags_in_order": ready_flags,
            "source_steps_all_complete": True,
            "closure_audit_complete": True,
            "block_k_complete": True,
            "ready_for_next_block": True,
            "next_block": NEXT_BLOCK,
            "next_step": NEXT_STEP,
            "next_step_title": NEXT_STEP_TITLE,
            "closure_line": CLOSURE_LINE,
        },
        "block_k_safety_summary": {
            "block_k_complete": True,
            "block_k_runtime_activation_performed": False,
            "block_k_order_flow_performed": False,
            "block_k_private_endpoint_access_performed": False,
            "block_k_network_io_performed": False,
            "block_k_filesystem_io_performed": False,
            "block_k_qml_changed": False,
            "block_k_bridge_api_changed": False,
            "block_k_ready_for_next_block": True,
            "next_block_requires_new_explicit_contract": True,
            "safe_to_enter_block_l_contract_only": True,
            "safe_to_enter_block_l_runtime_activation": False,
            "safe_to_enter_live_canary": False,
        },
        "observability_audit_rollback_soak_capability_closure": {
            "observability_contract_ready": True,
            "observability_read_model_ready": True,
            "audit_envelope_read_model_ready": True,
            "rollback_read_model_ready": True,
            "soak_read_model_ready": True,
            "gate_matrix_ready": True,
            "closure_audit_ready": True,
            "observability_runtime_enabled": False,
            "metrics_collection_enabled": False,
            "metrics_export_enabled": False,
            "audit_writer_enabled": False,
            "audit_export_enabled": False,
            "rollback_execution_enabled": False,
            "soak_runtime_enabled": False,
            "soak_scheduler_enabled": False,
            "runtime_loop_enabled": False,
        },
        "runtime_order_private_network_closure": {
            "runtime_activation_allowed_now": False,
            "runtime_gate_execution_allowed_now": False,
            "runtime_started": False,
            "order_generation_allowed_now": False,
            "order_submission_allowed_now": False,
            "order_cancel_allowed_now": False,
            "order_replace_allowed_now": False,
            "order_flow_performed": False,
            "private_endpoint_access_allowed_now": False,
            "private_endpoint_accessed": False,
            "account_read_allowed_now": False,
            "balance_read_allowed_now": False,
            "positions_read_allowed_now": False,
            "orders_read_allowed_now": False,
            "fills_read_allowed_now": False,
            "market_data_read_allowed_now": False,
            "network_io_allowed_now": False,
            "dns_lookup_allowed_now": False,
            "http_request_allowed_now": False,
            "websocket_allowed_now": False,
        },
        "blocked_block_k_capabilities": BLOCKED_BLOCK_K_CAPABILITIES,
        "block_k_source_boundaries": BLOCK_K_SOURCE_BOUNDARIES,
        "non_activation_evidence": non_activation,
        "next_block_entry_requirements": {
            "next_block": NEXT_BLOCK,
            "next_step": NEXT_STEP,
            "next_step_title": NEXT_STEP_TITLE,
            "requires_new_explicit_contract": True,
            "block_l_contract_only_first": True,
            "runtime_activation_must_remain_blocked_until_block_l_gate": True,
            "live_canary_must_remain_blocked_until_explicit_gate": True,
            "testnet_runtime_must_remain_blocked_until_explicit_gate": True,
            "paper_runtime_activation_must_remain_blocked_until_explicit_gate": True,
            "risk_governor_runtime_must_remain_blocked_until_explicit_gate": True,
            "order_flow_must_remain_blocked_until_explicit_gate": True,
            "private_endpoint_must_remain_blocked_until_explicit_gate": True,
            "network_io_must_remain_blocked_until_explicit_gate": True,
            "credentials_must_remain_blocked_until_explicit_gate": True,
            "qml_bridge_changes_must_remain_blocked_until_explicit_gate": True,
        },
        "future_blocks": [
            "BLOK L — RUNTIME ACTIVATION / LIVE CANARY GATES",
            "BLOK M — FULL RUNTIME PRODUCTIZATION",
            "BLOK N — FULL UI PRODUCT COMPLETION",
            "BLOK O — SECURITY / CREDENTIALS / LICENSING",
            "BLOK P — EXE PACKAGING / INSTALLER / SIGNING",
            "BLOK Q — PRODUCTION READINESS / FINAL RC",
        ],
        "status": STATUS,
    }
    return {key: result[key] for key in _TOP_LEVEL_FIELDS}
