"""FUNCTIONAL-PREVIEW-13.5 Block K gate matrix.

Pure-data Observability / Audit / Rollback / Soak gate matrix. This module
combines safe static subsets from Block K 13.0 through 13.4 and does not run
or activate runtime, writers, exporters, rollback, soak, orders, private
endpoints, network access, filesystem access, QML, or bridge surfaces.
"""

from __future__ import annotations

from typing import Any, Final

from ui.pyside_app.preview_audit_envelope_read_model import (
    build_preview_audit_envelope_read_model,
)
from ui.pyside_app.preview_observability_audit_rollback_soak_contract import (
    build_preview_observability_audit_rollback_soak_contract,
)
from ui.pyside_app.preview_observability_read_model import build_preview_observability_read_model
from ui.pyside_app.preview_rollback_read_model import build_preview_rollback_read_model
from ui.pyside_app.preview_soak_read_model import build_preview_soak_read_model

PREVIEW_OBSERVABILITY_AUDIT_ROLLBACK_SOAK_GATE_MATRIX_SCHEMA_VERSION: Final[str] = (
    "preview_observability_audit_rollback_soak_gate_matrix.v1"
)
PREVIEW_OBSERVABILITY_AUDIT_ROLLBACK_SOAK_GATE_MATRIX_KIND: Final[str] = (
    "functional_preview_block_k_observability_audit_rollback_soak_gate_matrix"
)
BLOCK_ID: Final[str] = "K"
STEP_ID: Final[str] = "13.5"
OBSERVABILITY_AUDIT_ROLLBACK_SOAK_GATE_MATRIX_STATUS: Final[str] = (
    "observability_audit_rollback_soak_gate_matrix_ready_no_runtime"
)
OBSERVABILITY_AUDIT_ROLLBACK_SOAK_GATE_MATRIX_DECISION: Final[str] = (
    "BUILD_BLOCK_K_GATE_MATRIX_ONLY_NO_RUNTIME_NO_EXPORTS_NO_IO"
)
READY_FOR_BLOCK_K_6: Final[bool] = True
NEXT_STEP: Final[str] = "FUNCTIONAL-PREVIEW-13.6"
NEXT_STEP_TITLE: Final[str] = "BLOCK K CLOSURE AUDIT"
STATUS: Final[str] = "ready_for_functional_preview_13_6_block_k_closure_audit"

_BLOCK_K_KEYS: Final[list[str]] = [
    "schema_version",
    "observability_audit_rollback_soak_contract_kind",
    "observability_audit_rollback_soak_contract_status",
    "observability_audit_rollback_soak_contract_decision",
    "ready_for_block_k_1",
    "next_step",
    "next_step_title",
    "status",
]
_OBSERVABILITY_KEYS: Final[list[str]] = [
    "schema_version",
    "observability_read_model_kind",
    "observability_read_model_status",
    "observability_read_model_decision",
    "ready_for_block_k_2",
    "next_step",
    "next_step_title",
    "status",
]
_AUDIT_KEYS: Final[list[str]] = [
    "schema_version",
    "audit_envelope_read_model_kind",
    "audit_envelope_read_model_status",
    "audit_envelope_read_model_decision",
    "ready_for_block_k_3",
    "next_step",
    "next_step_title",
    "status",
]
_ROLLBACK_KEYS: Final[list[str]] = [
    "schema_version",
    "rollback_read_model_kind",
    "rollback_read_model_status",
    "rollback_read_model_decision",
    "ready_for_block_k_4",
    "next_step",
    "next_step_title",
    "status",
]
_SOAK_KEYS: Final[list[str]] = [
    "schema_version",
    "soak_read_model_kind",
    "soak_read_model_status",
    "soak_read_model_decision",
    "ready_for_block_k_5",
    "next_step",
    "next_step_title",
    "status",
]

_ENTRY_DEFINITIONS: Final[list[tuple[str, str, str, str, str, str]]] = [
    (
        "block_k_contract_present_gate",
        "Block K contract present gate",
        "contract",
        "source_presence",
        "FUNCTIONAL-PREVIEW-13.0",
        "observability_audit_rollback_soak_contract_ready_no_runtime",
    ),
    (
        "observability_read_model_present_gate",
        "Observability read model present gate",
        "observability",
        "source_presence",
        "FUNCTIONAL-PREVIEW-13.1",
        "observability_read_model_ready_no_runtime_collection",
    ),
    (
        "audit_envelope_read_model_present_gate",
        "Audit envelope read model present gate",
        "audit",
        "source_presence",
        "FUNCTIONAL-PREVIEW-13.2",
        "audit_envelope_read_model_ready_no_audit_writer_no_exports",
    ),
    (
        "rollback_read_model_present_gate",
        "Rollback read model present gate",
        "rollback",
        "source_presence",
        "FUNCTIONAL-PREVIEW-13.3",
        "rollback_read_model_ready_no_execution_no_runtime_shutdown",
    ),
    (
        "soak_read_model_present_gate",
        "Soak read model present gate",
        "soak",
        "source_presence",
        "FUNCTIONAL-PREVIEW-13.4",
        "soak_read_model_ready_no_runtime_no_scheduler",
    ),
    (
        "runtime_activation_blocked_gate",
        "Runtime activation blocked gate",
        "runtime",
        "blocked_capability",
        "FUNCTIONAL-PREVIEW-13.5",
        "runtime_activation_blocked_until_future_gate",
    ),
    (
        "audit_writer_export_blocked_gate",
        "Audit writer export blocked gate",
        "audit",
        "blocked_capability",
        "FUNCTIONAL-PREVIEW-13.5",
        "audit_writer_export_blocked_until_future_gate",
    ),
    (
        "rollback_execution_blocked_gate",
        "Rollback execution blocked gate",
        "rollback",
        "blocked_capability",
        "FUNCTIONAL-PREVIEW-13.5",
        "rollback_execution_blocked_until_future_gate",
    ),
    (
        "soak_runtime_blocked_gate",
        "Soak runtime blocked gate",
        "soak",
        "blocked_capability",
        "FUNCTIONAL-PREVIEW-13.5",
        "soak_runtime_blocked_until_future_gate",
    ),
    (
        "order_private_network_blocked_gate",
        "Order private network blocked gate",
        "execution_safety",
        "blocked_capability",
        "FUNCTIONAL-PREVIEW-13.5",
        "order_private_network_blocked_until_future_gate",
    ),
]

_SCOPE_FALSE_FLAGS: Final[list[str]] = [
    "runtime_gate_execution_allowed_now",
    "gate_state_mutation_allowed_now",
    "observability_runtime_allowed_now",
    "audit_writer_allowed_now",
    "audit_export_allowed_now",
    "rollback_execution_allowed_now",
    "runtime_shutdown_allowed_now",
    "soak_runtime_allowed_now",
    "soak_scheduler_allowed_now",
    "runtime_loop_allowed_now",
    "metrics_collection_allowed_now",
    "metrics_export_allowed_now",
    "log_file_read_allowed_now",
    "log_file_write_allowed_now",
    "audit_file_read_allowed_now",
    "audit_file_write_allowed_now",
    "filesystem_io_allowed_now",
    "state_mutation_allowed_now",
    "order_cancel_allowed_now",
    "order_replace_allowed_now",
    "order_generation_allowed_now",
    "order_submission_allowed_now",
    "position_mutation_allowed_now",
    "private_endpoint_access_allowed_now",
    "account_read_allowed_now",
    "balance_read_allowed_now",
    "positions_read_allowed_now",
    "orders_read_allowed_now",
    "fills_read_allowed_now",
    "market_data_read_allowed_now",
    "network_io_allowed_now",
    "dns_lookup_allowed_now",
    "http_request_allowed_now",
    "websocket_allowed_now",
    "adapter_instantiation_allowed_now",
    "adapter_wiring_allowed_now",
    "scheduler_allowed_now",
    "config_file_read_allowed_now",
    "config_discovery_allowed_now",
    "yaml_parse_allowed_now",
    "json_parse_allowed_now",
    "environment_variable_read_allowed_now",
    "credential_secret_read_allowed_now",
    "credential_validation_allowed_now",
    "secure_store_read_allowed_now",
    "secure_store_write_allowed_now",
    "qml_changes_allowed",
    "new_qml_method_calls_allowed",
    "bridge_api_changes_allowed",
    "exe_packaging_in_scope",
    "bat_productization_allowed",
]

BLOCKED_GATE_MATRIX_CAPABILITIES: Final[list[str]] = [
    "runtime gate execution",
    "gate state mutation",
    "runtime activation",
    "observability runtime collection",
    "metrics collection",
    "metrics export",
    "audit writer",
    "audit export",
    "audit file read",
    "audit file write",
    "log file read",
    "log file write",
    "rollback execution",
    "runtime shutdown",
    "soak runtime",
    "soak scheduler",
    "runtime loop",
    "wall-clock runtime measurement",
    "stability probe",
    "state mutation",
    "order generation",
    "order submission",
    "order cancel",
    "order replace",
    "position mutation",
    "private endpoint access",
    "account read",
    "balance read",
    "positions read",
    "orders read",
    "fills read",
    "market data read",
    "adapter instantiation",
    "adapter runtime wiring",
    "scheduler",
    "filesystem I/O",
    "network I/O",
    "DNS lookup",
    "HTTP request",
    "WebSocket connection",
    "credential read",
    "secret read",
    "secure store read",
    "secure store write",
    "config file read",
    "config discovery",
    "YAML parse",
    "JSON parse",
    "environment variable read",
    "TradingController change",
    "DecisionEnvelope change",
    "QML action dispatch",
    "bridge API changes",
    "PyInstaller/EXE packaging",
]

SOURCE_BOUNDARIES: Final[list[str]] = [
    "no PySide import",
    "no QML import",
    "no runtime loop import",
    "no scheduler import",
    "no TradingController import",
    "no DecisionEnvelope import",
    "no strategy/AI/scoring/recommendation import",
    "no order module import",
    "no live adapter import",
    "no testnet adapter import",
    "no sandbox adapter import",
    "no exchange adapter runtime import",
    "no account module import",
    "no secrets module import",
    "no security store import",
    "no observability runtime import",
    "no logger/exporter runtime import",
    "no metrics exporter import",
    "no audit writer import",
    "no audit exporter import",
    "no rollback runner import",
    "no rollback executor import",
    "no soak runner import",
    "no soak scheduler import",
    "no filesystem I/O",
    "no audit file read",
    "no audit file write",
    "no log file read",
    "no log file write",
    "no audit write",
    "no audit export",
    "no runtime shutdown",
    "no state mutation",
    "no wall-clock runtime measurement",
    "no stability probe",
    "no config file read",
    "no config discovery",
    "no YAML parse",
    "no JSON parse",
    "no environment variable read",
    "no credential read",
    "no credential validation",
    "no secret material handling",
    "no secure store read",
    "no secure store write",
    "no real market data read",
    "no private endpoint access",
    "no account read",
    "no balance read",
    "no positions read",
    "no orders read",
    "no fills read",
    "no order generation",
    "no order submission",
    "no order cancel",
    "no order replace",
    "no position mutation",
    "no gate execution",
    "no gate state mutation",
    "no runtime activation",
    "no network I/O",
    "no DNS lookup",
    "no HTTP request",
    "no WebSocket connection",
    "no QML changes",
    "no bridge API changes",
    "no .bat changes",
    "no app.py changes",
    "no dependency declarations changes",
    "no workflow changes",
]


def _subset(source: dict[str, Any], keys: list[str]) -> dict[str, Any]:
    return {key: source[key] for key in keys}


def _entries() -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []
    for source_id, display, domain, gate_type, source_step, status in _ENTRY_DEFINITIONS:
        state = (
            "passed_static_source_gate"
            if gate_type == "source_presence"
            else "blocked_until_future_gate"
        )
        entries.append(
            {
                "gate_matrix_entry_id": f"gate_matrix_{source_id}",
                "source_gate_id": source_id,
                "display_name": display,
                "gate_domain": domain,
                "gate_type": gate_type,
                "source_step": source_step,
                "required_source_status": status,
                "gate_matrix_state": state,
                "required_for_block_k_closure": True,
                "eligible_for_13_6_closure_audit": True,
                "runtime_gate_execution_allowed_now": False,
                "gate_state_mutation_allowed_now": False,
                "runtime_activation_allowed_now": False,
                "audit_writer_allowed_now": False,
                "rollback_execution_allowed_now": False,
                "soak_runtime_allowed_now": False,
                "order_flow_allowed_now": False,
                "private_endpoint_access_allowed_now": False,
                "network_io_allowed_now": False,
                "filesystem_io_allowed_now": False,
                "safe_for_offline_tests": True,
                "notes": "Static gate matrix entry only; future gate required for any runtime action.",
            }
        )
    return entries


def build_preview_observability_audit_rollback_soak_gate_matrix() -> dict[str, Any]:
    entries = _entries()
    scope = {
        "scope_name": "observability_audit_rollback_soak_gate_matrix",
        "gate_matrix_only": True,
        "derived_from_block_k_contract_13_0": True,
        "derived_from_observability_read_model_13_1": True,
        "derived_from_audit_envelope_read_model_13_2": True,
        "derived_from_rollback_read_model_13_3": True,
        "derived_from_soak_read_model_13_4": True,
        **{key: False for key in _SCOPE_FALSE_FLAGS},
        "exe_direction_preserved": True,
    }
    false_evidence = [
        "runtime_gate_executed",
        "gate_state_mutated",
        "runtime_activated",
        "observability_runtime_started",
        "metrics_collected",
        "metrics_exported",
        "audit_writer_started",
        "audit_exported",
        "audit_file_read",
        "audit_file_written",
        "log_file_read",
        "log_file_written",
        "rollback_executed",
        "runtime_shutdown_executed",
        "soak_runtime_started",
        "soak_scheduler_started",
        "runtime_loop_started",
        "wall_clock_runtime_measured",
        "stability_probe_started",
        "state_mutated",
        "order_generated",
        "order_submitted",
        "order_cancelled",
        "order_replaced",
        "position_mutated",
        "private_endpoint_accessed",
        "account_read_performed",
        "balance_read_performed",
        "positions_read_performed",
        "orders_read_performed",
        "fills_read_performed",
        "market_data_read_performed",
        "adapter_instantiated",
        "adapter_wired_to_runtime",
        "scheduler_started",
        "filesystem_io_performed",
        "network_io_performed",
        "dns_lookup_performed",
        "http_request_performed",
        "websocket_opened",
        "credentials_read",
        "secrets_read",
        "secure_store_read",
        "secure_store_write",
        "config_files_read",
        "config_discovery_performed",
        "yaml_parsed",
        "json_parsed",
        "environment_variables_read",
        "trading_controller_touched",
        "decision_envelope_touched",
        "qml_changed",
        "bridge_api_changed",
    ]
    boundaries = {
        key: True
        for key in [
            "gate_matrix_is_static",
            "gate_matrix_is_derived_from_13_0_contract",
            "gate_matrix_is_derived_from_13_1_observability",
            "gate_matrix_is_derived_from_13_2_audit_envelope",
            "gate_matrix_is_derived_from_13_3_rollback",
            "gate_matrix_is_derived_from_13_4_soak",
            "gate_matrix_can_feed_13_6_closure_audit",
            "gate_matrix_cannot_feed_runtime_directly",
            "gate_matrix_cannot_execute_gates",
            "gate_matrix_cannot_mutate_gate_state",
            "gate_matrix_cannot_activate_runtime",
            "gate_matrix_cannot_start_observability_runtime",
            "gate_matrix_cannot_collect_metrics",
            "gate_matrix_cannot_export_metrics",
            "gate_matrix_cannot_write_audit",
            "gate_matrix_cannot_export_audit",
            "gate_matrix_cannot_read_audit_files",
            "gate_matrix_cannot_write_audit_files",
            "gate_matrix_cannot_read_logs",
            "gate_matrix_cannot_write_logs",
            "gate_matrix_cannot_execute_rollback",
            "gate_matrix_cannot_execute_runtime_shutdown",
            "gate_matrix_cannot_run_soak",
            "gate_matrix_cannot_start_scheduler",
            "gate_matrix_cannot_start_runtime_loop",
            "gate_matrix_cannot_measure_wall_clock_runtime",
            "gate_matrix_cannot_run_stability_probe",
            "gate_matrix_cannot_mutate_state",
            "gate_matrix_cannot_generate_orders",
            "gate_matrix_cannot_submit_orders",
            "gate_matrix_cannot_cancel_orders",
            "gate_matrix_cannot_replace_orders",
            "gate_matrix_cannot_mutate_positions",
            "gate_matrix_cannot_access_private_endpoints",
            "gate_matrix_cannot_read_account",
            "gate_matrix_balance_read_blocked",
            "gate_matrix_cannot_read_positions",
            "gate_matrix_cannot_read_orders",
            "gate_matrix_cannot_read_fills",
            "gate_matrix_cannot_read_market_data",
            "gate_matrix_cannot_open_network_connection",
            "gate_matrix_cannot_perform_dns_lookup",
            "gate_matrix_cannot_perform_http_request",
            "gate_matrix_cannot_open_websocket",
            "gate_matrix_cannot_read_credentials",
            "gate_matrix_cannot_read_secrets",
            "gate_matrix_cannot_read_secure_store",
            "gate_matrix_cannot_change_qml_or_bridge",
        ]
    }
    return {
        "schema_version": PREVIEW_OBSERVABILITY_AUDIT_ROLLBACK_SOAK_GATE_MATRIX_SCHEMA_VERSION,
        "observability_audit_rollback_soak_gate_matrix_kind": PREVIEW_OBSERVABILITY_AUDIT_ROLLBACK_SOAK_GATE_MATRIX_KIND,
        "block": BLOCK_ID,
        "step": STEP_ID,
        "observability_audit_rollback_soak_gate_matrix_status": OBSERVABILITY_AUDIT_ROLLBACK_SOAK_GATE_MATRIX_STATUS,
        "observability_audit_rollback_soak_gate_matrix_decision": OBSERVABILITY_AUDIT_ROLLBACK_SOAK_GATE_MATRIX_DECISION,
        "ready_for_block_k_6": READY_FOR_BLOCK_K_6,
        "next_step": NEXT_STEP,
        "next_step_title": NEXT_STEP_TITLE,
        "block_k_contract_reference": _subset(
            build_preview_observability_audit_rollback_soak_contract(), _BLOCK_K_KEYS
        ),
        "observability_read_model_reference": _subset(
            build_preview_observability_read_model(), _OBSERVABILITY_KEYS
        ),
        "audit_envelope_read_model_reference": _subset(
            build_preview_audit_envelope_read_model(), _AUDIT_KEYS
        ),
        "rollback_read_model_reference": _subset(
            build_preview_rollback_read_model(), _ROLLBACK_KEYS
        ),
        "soak_read_model_reference": _subset(build_preview_soak_read_model(), _SOAK_KEYS),
        "gate_matrix_scope": scope,
        "gate_matrix_entries": entries,
        "default_gate_matrix_selection": {
            "gate_matrix_entry_id": "gate_matrix_block_k_contract_present_gate",
            "source_gate_id": "block_k_contract_present_gate",
            "reason": "first Block K gate matrix entry; static source gate only, no runtime execution",
            "runtime_gate_execution_allowed_now": False,
            "gate_state_mutation_allowed_now": False,
        },
        "gate_matrix_summary": {
            "entry_count": 10,
            "static_source_gate_count": 5,
            "blocked_capability_gate_count": 5,
            "passed_static_source_gate_count": 5,
            "blocked_until_future_gate_count": 5,
            "runtime_gate_execution_enabled_entry_count": 0,
            "gate_state_mutation_enabled_entry_count": 0,
            "runtime_activation_enabled_entry_count": 0,
            "audit_writer_enabled_entry_count": 0,
            "rollback_execution_enabled_entry_count": 0,
            "soak_runtime_enabled_entry_count": 0,
            "order_flow_enabled_entry_count": 0,
            "private_endpoint_enabled_entry_count": 0,
            "network_io_enabled_entry_count": 0,
            "filesystem_io_enabled_entry_count": 0,
            "offline_safe_entry_count": 10,
            "entries_required_for_block_k_closure": 10,
            "entries_eligible_for_13_6_closure_audit": 10,
            "safe_to_render_in_future_ui_as_read_only": True,
            "safe_for_runtime_execution_now": False,
            "safe_for_gate_execution_now": False,
            "safe_for_export_now": False,
        },
        "gate_matrix_dependency_map": {
            "source_steps_in_order": [
                "FUNCTIONAL-PREVIEW-13.0",
                "FUNCTIONAL-PREVIEW-13.1",
                "FUNCTIONAL-PREVIEW-13.2",
                "FUNCTIONAL-PREVIEW-13.3",
                "FUNCTIONAL-PREVIEW-13.4",
            ],
            "target_step": "FUNCTIONAL-PREVIEW-13.5",
            "next_step": "FUNCTIONAL-PREVIEW-13.6",
            "required_ready_flags": [
                "ready_for_block_k_1",
                "ready_for_block_k_2",
                "ready_for_block_k_3",
                "ready_for_block_k_4",
                "ready_for_block_k_5",
            ],
            "required_static_source_statuses": [
                "observability_audit_rollback_soak_contract_ready_no_runtime",
                "observability_read_model_ready_no_runtime_collection",
                "audit_envelope_read_model_ready_no_audit_writer_no_exports",
                "rollback_read_model_ready_no_execution_no_runtime_shutdown",
                "soak_read_model_ready_no_runtime_no_scheduler",
            ],
            "requires_runtime_blocked": True,
            "requires_audit_writer_export_blocked": True,
            "requires_rollback_execution_blocked": True,
            "requires_soak_runtime_blocked": True,
            "requires_order_flow_blocked": True,
            "requires_private_endpoint_blocked": True,
            "requires_network_blocked": True,
            "requires_filesystem_io_blocked": True,
            "ready_for_13_6_block_k_closure_audit": True,
        },
        "gate_matrix_contract": {
            "contract_id": "block_k_observability_audit_rollback_soak_gate_matrix_contract",
            "gate_matrix_is_static": True,
            "all_source_models_present": True,
            "all_source_models_are_read_only": True,
            "all_source_models_safe_for_offline_tests": True,
            "runtime_activation_blocked_until_future_gate": True,
            "audit_writer_export_blocked_until_future_gate": True,
            "rollback_execution_blocked_until_future_gate": True,
            "soak_runtime_blocked_until_future_gate": True,
            "order_flow_blocked_until_future_gate": True,
            "private_endpoint_blocked_until_future_gate": True,
            "network_io_blocked_until_future_gate": True,
            "filesystem_io_blocked_until_future_gate": True,
            "closure_audit_required_next": True,
        },
        "blocked_gate_matrix_capabilities": BLOCKED_GATE_MATRIX_CAPABILITIES,
        "gate_matrix_boundaries": boundaries,
        "non_activation_evidence": {
            "block_k_contract_13_0_read": True,
            "observability_read_model_13_1_read": True,
            "audit_envelope_read_model_13_2_read": True,
            "rollback_read_model_13_3_read": True,
            "soak_read_model_13_4_read": True,
            "gate_matrix_built": True,
            **{key: False for key in false_evidence},
        },
        "source_boundaries": SOURCE_BOUNDARIES,
        "future_steps": ["functional_preview_13_6_block_k_closure_audit"],
        "status": STATUS,
    }
