"""FUNCTIONAL-PREVIEW-13.3 Block K rollback read model.

Pure-data read model for planned Block K rollback scenarios. This module only
assembles static dictionaries from accepted Block K 13.0, 13.1, and 13.2 safe
subsets. It does not execute rollback, shut down runtime, cancel orders, mutate
state, perform filesystem/network I/O, collect metrics, write audits, or touch
QML/bridge/runtime surfaces.
"""

from __future__ import annotations

from typing import Any, Final

from ui.pyside_app.preview_audit_envelope_read_model import (
    build_preview_audit_envelope_read_model,
)
from ui.pyside_app.preview_observability_audit_rollback_soak_contract import (
    build_preview_observability_audit_rollback_soak_contract,
)
from ui.pyside_app.preview_observability_read_model import build_preview_observability_read_model

PREVIEW_ROLLBACK_READ_MODEL_SCHEMA_VERSION: Final[str] = "preview_rollback_read_model.v1"
PREVIEW_ROLLBACK_READ_MODEL_KIND: Final[str] = "functional_preview_block_k_rollback_read_model"
BLOCK_ID: Final[str] = "K"
STEP_ID: Final[str] = "13.3"
ROLLBACK_READ_MODEL_STATUS: Final[str] = (
    "rollback_read_model_ready_no_execution_no_runtime_shutdown"
)
ROLLBACK_READ_MODEL_DECISION: Final[str] = (
    "BUILD_ROLLBACK_READ_MODEL_ONLY_NO_EXECUTION_NO_RUNTIME_SHUTDOWN_NO_IO"
)
READY_FOR_BLOCK_K_4: Final[bool] = True
NEXT_STEP: Final[str] = "FUNCTIONAL-PREVIEW-13.4"
NEXT_STEP_TITLE: Final[str] = "SOAK READ MODEL"
STATUS: Final[str] = "ready_for_functional_preview_13_4_soak_read_model"

_BLOCK_K_CONTRACT_SAFE_KEYS: Final[list[str]] = [
    "schema_version",
    "observability_audit_rollback_soak_contract_kind",
    "observability_audit_rollback_soak_contract_status",
    "observability_audit_rollback_soak_contract_decision",
    "ready_for_block_k_1",
    "next_step",
    "next_step_title",
    "status",
]
_OBSERVABILITY_READ_MODEL_SAFE_KEYS: Final[list[str]] = [
    "schema_version",
    "observability_read_model_kind",
    "observability_read_model_status",
    "observability_read_model_decision",
    "ready_for_block_k_2",
    "next_step",
    "next_step_title",
    "status",
]
_AUDIT_ENVELOPE_READ_MODEL_SAFE_KEYS: Final[list[str]] = [
    "schema_version",
    "audit_envelope_read_model_kind",
    "audit_envelope_read_model_status",
    "audit_envelope_read_model_decision",
    "ready_for_block_k_3",
    "next_step",
    "next_step_title",
    "status",
]

_FALSE_SCOPE_FLAGS: Final[list[str]] = [
    "rollback_execution_allowed_now",
    "runtime_shutdown_allowed_now",
    "state_mutation_allowed_now",
    "order_cancel_allowed_now",
    "order_replace_allowed_now",
    "order_generation_allowed_now",
    "order_submission_allowed_now",
    "position_mutation_allowed_now",
    "audit_writer_allowed_now",
    "audit_export_allowed_now",
    "audit_file_read_allowed_now",
    "audit_file_write_allowed_now",
    "log_file_read_allowed_now",
    "log_file_write_allowed_now",
    "filesystem_io_allowed_now",
    "observability_runtime_allowed_now",
    "runtime_metrics_collection_allowed_now",
    "metrics_export_allowed_now",
    "soak_runtime_allowed_now",
    "runtime_enforcement_allowed_now",
    "risk_decision_runtime_allowed_now",
    "limit_enforcement_runtime_allowed_now",
    "kill_switch_runtime_allowed_now",
    "manual_trigger_allowed_now",
    "automatic_trigger_allowed_now",
    "kill_switch_state_mutation_allowed_now",
    "private_endpoint_access_allowed_now",
    "account_read_allowed_now",
    "balance_read_allowed_now",
    "positions_read_allowed_now",
    "orders_read_allowed_now",
    "fills_read_allowed_now",
    "market_data_read_allowed_now",
    "network_io_allowed_now",
    "dns_lookup_allowed_now",
    "http_request_allowed_now",
    "websocket_allowed_now",
    "adapter_instantiation_allowed_now",
    "adapter_wiring_allowed_now",
    "scheduler_allowed_now",
    "config_file_read_allowed_now",
    "config_discovery_allowed_now",
    "yaml_parse_allowed_now",
    "json_parse_allowed_now",
    "environment_variable_read_allowed_now",
    "credential_secret_read_allowed_now",
    "credential_validation_allowed_now",
    "secure_store_read_allowed_now",
    "secure_store_write_allowed_now",
    "qml_changes_allowed",
    "new_qml_method_calls_allowed",
    "bridge_api_changes_allowed",
    "exe_packaging_in_scope",
    "bat_productization_allowed",
]

_ENTRY_DEFINITIONS: Final[list[dict[str, str]]] = [
    {
        "source_rollback_id": "operator_requested_rollback",
        "display_name": "Operator requested rollback",
        "rollback_domain": "operator",
        "planned_rollback_source": "future_operator_rollback_request",
        "planned_rollback_type": "manual_request",
        "required_readiness_profile": "operator_rollback_readiness_profile",
        "planned_operator_action": "future_operator_confirmed_rollback",
        "planned_audit_event_id": "runtime_lifecycle_event",
    },
    {
        "source_rollback_id": "runtime_health_rollback",
        "display_name": "Runtime health rollback",
        "rollback_domain": "runtime",
        "planned_rollback_source": "future_runtime_health_failure",
        "planned_rollback_type": "runtime_health",
        "required_readiness_profile": "runtime_health_rollback_readiness_profile",
        "planned_operator_action": "future_operator_review_required",
        "planned_audit_event_id": "runtime_lifecycle_event",
    },
    {
        "source_rollback_id": "risk_gate_rollback",
        "display_name": "Risk gate rollback",
        "rollback_domain": "risk",
        "planned_rollback_source": "future_risk_gate_failure",
        "planned_rollback_type": "risk_gate",
        "required_readiness_profile": "risk_gate_rollback_readiness_profile",
        "planned_operator_action": "future_operator_review_required",
        "planned_audit_event_id": "risk_gate_event",
    },
    {
        "source_rollback_id": "audit_failure_rollback",
        "display_name": "Audit failure rollback",
        "rollback_domain": "audit",
        "planned_rollback_source": "future_audit_envelope_failure",
        "planned_rollback_type": "audit_failure",
        "required_readiness_profile": "audit_failure_rollback_readiness_profile",
        "planned_operator_action": "future_operator_review_required",
        "planned_audit_event_id": "rollback_event",
    },
    {
        "source_rollback_id": "order_flow_rollback",
        "display_name": "Order flow rollback",
        "rollback_domain": "order_flow",
        "planned_rollback_source": "future_order_flow_failure",
        "planned_rollback_type": "order_flow",
        "required_readiness_profile": "order_flow_rollback_readiness_profile",
        "planned_operator_action": "future_operator_review_required",
        "planned_audit_event_id": "order_flow_event",
    },
    {
        "source_rollback_id": "private_endpoint_rollback",
        "display_name": "Private endpoint rollback",
        "rollback_domain": "private_endpoint",
        "planned_rollback_source": "future_private_endpoint_failure",
        "planned_rollback_type": "private_endpoint",
        "required_readiness_profile": "private_endpoint_rollback_readiness_profile",
        "planned_operator_action": "future_operator_review_required",
        "planned_audit_event_id": "private_endpoint_gate_event",
    },
    {
        "source_rollback_id": "network_failure_rollback",
        "display_name": "Network failure rollback",
        "rollback_domain": "network",
        "planned_rollback_source": "future_network_failure",
        "planned_rollback_type": "network",
        "required_readiness_profile": "network_rollback_readiness_profile",
        "planned_operator_action": "future_operator_review_required",
        "planned_audit_event_id": "network_gate_event",
    },
    {
        "source_rollback_id": "soak_failure_rollback",
        "display_name": "Soak failure rollback",
        "rollback_domain": "soak",
        "planned_rollback_source": "future_soak_failure",
        "planned_rollback_type": "soak",
        "required_readiness_profile": "soak_rollback_readiness_profile",
        "planned_operator_action": "future_operator_review_required",
        "planned_audit_event_id": "soak_event",
    },
]
_REQUIRED_FIELD_NAMES: Final[list[str]] = [
    "rollback_id",
    "rollback_type",
    "rollback_reason",
    "source_component",
    "required_operator_action",
    "pre_rollback_state_snapshot",
    "rollback_target_state",
    "audit_correlation_id",
    "safety_gate_state",
    "rollback_blocking_reason",
]
BLOCKED_ROLLBACK_READ_MODEL_CAPABILITIES: Final[list[str]] = [
    "rollback execution",
    "runtime shutdown",
    "state mutation",
    "order cancel",
    "order replace",
    "audit writer",
    "audit export",
    "audit file read",
    "audit file write",
    "log file read",
    "log file write",
    "filesystem I/O",
    "observability runtime collection",
    "metrics collection",
    "metrics export",
    "soak runtime",
    "soak scheduler",
    "risk runtime enforcement",
    "limit runtime enforcement",
    "kill switch runtime trigger",
    "manual kill switch trigger",
    "automatic kill switch trigger",
    "kill switch state mutation",
    "order generation",
    "order submission",
    "position mutation",
    "private endpoint access",
    "account read",
    "balance read",
    "positions read",
    "orders read",
    "fills read",
    "market data read",
    "adapter instantiation",
    "adapter runtime wiring",
    "runtime loop",
    "scheduler",
    "network I/O",
    "DNS lookup",
    "HTTP request",
    "WebSocket connection",
    "credential read",
    "secret read",
    "secure store read",
    "secure store write",
    "config file read",
    "config discovery",
    "YAML parse",
    "JSON parse",
    "environment variable read",
    "TradingController change",
    "DecisionEnvelope change",
    "QML action dispatch",
    "bridge API changes",
    "PyInstaller/EXE packaging",
]
SOURCE_BOUNDARIES: Final[list[str]] = [
    "no PySide import",
    "no QML import",
    "no runtime loop import",
    "no scheduler import",
    "no TradingController import",
    "no DecisionEnvelope import",
    "no strategy/AI/scoring/recommendation import",
    "no order module import",
    "no live adapter import",
    "no testnet adapter import",
    "no sandbox adapter import",
    "no exchange adapter runtime import",
    "no account module import",
    "no secrets module import",
    "no security store import",
    "no observability runtime import",
    "no logger/exporter runtime import",
    "no metrics exporter import",
    "no audit writer import",
    "no audit exporter import",
    "no rollback runner import",
    "no rollback executor import",
    "no soak runner import",
    "no filesystem I/O",
    "no audit file read",
    "no audit file write",
    "no log file read",
    "no log file write",
    "no audit write",
    "no audit export",
    "no runtime shutdown",
    "no state mutation",
    "no config file read",
    "no config discovery",
    "no YAML parse",
    "no JSON parse",
    "no environment variable read",
    "no credential read",
    "no credential validation",
    "no secret material handling",
    "no secure store read",
    "no secure store write",
    "no real market data read",
    "no private endpoint access",
    "no account read",
    "no balance read",
    "no positions read",
    "no orders read",
    "no fills read",
    "no order generation",
    "no order submission",
    "no order cancel",
    "no order replace",
    "no position mutation",
    "no network I/O",
    "no DNS lookup",
    "no HTTP request",
    "no WebSocket connection",
    "no QML changes",
    "no bridge API changes",
    "no .bat changes",
    "no app.py changes",
    "no dependency declarations changes",
    "no workflow changes",
]


def _safe_subset(source: dict[str, Any], keys: list[str]) -> dict[str, Any]:
    return {key: source[key] for key in keys}


def _build_entries() -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []
    for definition in _ENTRY_DEFINITIONS:
        source_id = definition["source_rollback_id"]
        entries.append(
            {
                "rollback_read_model_id": f"rollback_read_model_{source_id}",
                "source_rollback_id": definition["source_rollback_id"],
                "display_name": definition["display_name"],
                "read_model_classification": "static_rollback_read_model_only",
                "rollback_domain": definition["rollback_domain"],
                "planned_rollback_source": definition["planned_rollback_source"],
                "planned_rollback_type": definition["planned_rollback_type"],
                "required_readiness_profile": definition["required_readiness_profile"],
                "planned_operator_action": definition["planned_operator_action"],
                "planned_audit_event_id": definition["planned_audit_event_id"],
                "operator_visibility": "future_read_only_rollback",
                "eligible_for_13_5_gate_matrix": True,
                "rollback_execution_allowed_now": False,
                "runtime_shutdown_allowed_now": False,
                "state_mutation_allowed_now": False,
                "order_cancel_allowed_now": False,
                "private_endpoint_access_allowed_now": False,
                "network_io_allowed_now": False,
                "filesystem_io_allowed_now": False,
                "safe_for_offline_tests": True,
                "notes": "Static planned rollback scenario only; no execution or runtime shutdown in 13.3.",
            }
        )
    return entries


def build_preview_rollback_read_model() -> dict[str, Any]:
    """Build the static Block K rollback read model without runtime side effects."""
    block_k_contract = build_preview_observability_audit_rollback_soak_contract()
    observability_read_model = build_preview_observability_read_model()
    audit_envelope_read_model = build_preview_audit_envelope_read_model()
    entries = _build_entries()
    ids = [entry["rollback_read_model_id"] for entry in entries]
    required_fields = [
        {
            "field_name": name,
            "field_classification": "planned_rollback_readiness_field_only",
            "required_for_future_executor": True,
            "contains_secret_material": False,
            "contains_private_key_material": False,
            "allowed_to_collect_now": False,
            "allowed_to_mutate_now": False,
            "notes": "Planned future executor readiness field; not collected or mutated in 13.3.",
        }
        for name in _REQUIRED_FIELD_NAMES
    ]
    scope = {
        "scope_name": "rollback_read_model",
        "read_model_only": True,
        "derived_from_block_k_contract_13_0": True,
        "derived_from_observability_read_model_13_1": True,
        "derived_from_audit_envelope_read_model_13_2": True,
        **{flag: False for flag in _FALSE_SCOPE_FLAGS},
        "exe_direction_preserved": True,
    }
    matrix = {
        "rollback_read_model_ids": ids,
        "operator_domain_ids": ["rollback_read_model_operator_requested_rollback"],
        "runtime_domain_ids": ["rollback_read_model_runtime_health_rollback"],
        "risk_domain_ids": ["rollback_read_model_risk_gate_rollback"],
        "audit_domain_ids": ["rollback_read_model_audit_failure_rollback"],
        "order_flow_domain_ids": ["rollback_read_model_order_flow_rollback"],
        "private_endpoint_domain_ids": ["rollback_read_model_private_endpoint_rollback"],
        "network_domain_ids": ["rollback_read_model_network_failure_rollback"],
        "soak_domain_ids": ["rollback_read_model_soak_failure_rollback"],
        "entries_requiring_13_5_gate_matrix": ids,
        "entries_never_executed_in_13_3": ids,
        "planned_rollback_sources_by_id": {
            entry["rollback_read_model_id"]: entry["planned_rollback_source"] for entry in entries
        },
        "planned_audit_event_ids_by_id": {
            entry["rollback_read_model_id"]: entry["planned_audit_event_id"] for entry in entries
        },
        "required_readiness_profiles_by_id": {
            entry["rollback_read_model_id"]: entry["required_readiness_profile"]
            for entry in entries
        },
    }
    return {
        "schema_version": PREVIEW_ROLLBACK_READ_MODEL_SCHEMA_VERSION,
        "rollback_read_model_kind": PREVIEW_ROLLBACK_READ_MODEL_KIND,
        "block": BLOCK_ID,
        "step": STEP_ID,
        "rollback_read_model_status": ROLLBACK_READ_MODEL_STATUS,
        "rollback_read_model_decision": ROLLBACK_READ_MODEL_DECISION,
        "ready_for_block_k_4": READY_FOR_BLOCK_K_4,
        "next_step": NEXT_STEP,
        "next_step_title": NEXT_STEP_TITLE,
        "block_k_contract_reference": _safe_subset(block_k_contract, _BLOCK_K_CONTRACT_SAFE_KEYS),
        "observability_read_model_reference": _safe_subset(
            observability_read_model, _OBSERVABILITY_READ_MODEL_SAFE_KEYS
        ),
        "audit_envelope_read_model_reference": _safe_subset(
            audit_envelope_read_model, _AUDIT_ENVELOPE_READ_MODEL_SAFE_KEYS
        ),
        "rollback_read_model_scope": scope,
        "rollback_read_model_entries": entries,
        "default_rollback_read_model_selection": {
            "rollback_read_model_id": "rollback_read_model_operator_requested_rollback",
            "source_rollback_id": "operator_requested_rollback",
            "reason": "first rollback read-model scenario; static only, no rollback execution, no runtime shutdown",
            "rollback_execution_allowed_now": False,
            "runtime_shutdown_allowed_now": False,
        },
        "rollback_readiness_required_fields": required_fields,
        "rollback_read_model_summary": {
            "entry_count": 8,
            "required_field_count": 10,
            "default_selection_id": "rollback_read_model_operator_requested_rollback",
            "rollback_execution_enabled_entry_count": 0,
            "runtime_shutdown_enabled_entry_count": 0,
            "state_mutation_enabled_entry_count": 0,
            "order_cancel_enabled_entry_count": 0,
            "private_endpoint_enabled_entry_count": 0,
            "network_enabled_entry_count": 0,
            "filesystem_io_enabled_entry_count": 0,
            "offline_safe_entry_count": 8,
            "entries_eligible_for_13_5_gate_matrix": 8,
            "operator_domain_entry_count": 1,
            "runtime_domain_entry_count": 1,
            "risk_domain_entry_count": 1,
            "audit_domain_entry_count": 1,
            "order_flow_domain_entry_count": 1,
            "private_endpoint_domain_entry_count": 1,
            "network_domain_entry_count": 1,
            "soak_domain_entry_count": 1,
            "safe_to_render_in_future_ui_as_read_only": True,
            "safe_for_rollback_execution_now": False,
            "safe_for_runtime_shutdown_now": False,
            "safe_for_state_mutation_now": False,
        },
        "rollback_read_model_matrix": matrix,
        "rollback_surface_contract": {
            "surface_contract_id": "block_k_rollback_read_model_surface_contract",
            "read_model_is_static": True,
            "rollback_scenarios_are_planned_only": True,
            "rollback_is_not_executed_now": True,
            "runtime_shutdown_is_not_executed_now": True,
            "state_is_not_mutated_now": True,
            "orders_are_not_cancelled_now": True,
            "private_endpoints_are_not_accessed_now": True,
            "filesystem_io_forbidden_now": True,
            "network_io_forbidden_now": True,
            "executor_requires_future_gate": True,
            "ui_surface_requires_future_qml_gate": True,
        },
        "blocked_rollback_read_model_capabilities": BLOCKED_ROLLBACK_READ_MODEL_CAPABILITIES,
        "rollback_read_model_boundaries": {
            key: True
            for key in [
                "rollback_read_model_is_static",
                "rollback_read_model_is_derived_from_13_0_contract",
                "rollback_read_model_is_derived_from_13_1_observability",
                "rollback_read_model_is_derived_from_13_2_audit_envelope",
                "rollback_read_model_can_feed_13_5_gate_matrix",
                "rollback_read_model_cannot_feed_runtime_directly",
                "rollback_read_model_cannot_execute_rollback",
                "rollback_read_model_cannot_execute_runtime_shutdown",
                "rollback_read_model_cannot_mutate_state",
                "rollback_read_model_cannot_cancel_orders",
                "rollback_read_model_cannot_replace_orders",
                "rollback_read_model_cannot_write_audit",
                "rollback_read_model_cannot_export_audit",
                "rollback_read_model_cannot_read_audit_files",
                "rollback_read_model_cannot_write_audit_files",
                "rollback_read_model_cannot_read_logs",
                "rollback_read_model_cannot_write_logs",
                "rollback_read_model_cannot_touch_filesystem",
                "rollback_read_model_cannot_collect_metrics",
                "rollback_read_model_cannot_export_metrics",
                "rollback_read_model_cannot_run_soak",
                "rollback_read_model_cannot_enable_runtime",
                "rollback_read_model_cannot_enforce_limits",
                "rollback_read_model_cannot_trigger_kill_switch",
                "rollback_read_model_cannot_mutate_kill_switch_state",
                "rollback_read_model_cannot_generate_orders",
                "rollback_read_model_cannot_submit_orders",
                "rollback_read_model_cannot_access_private_endpoints",
                "rollback_read_model_cannot_read_account",
                "rollback_read_model_balance_read_blocked",
                "rollback_read_model_cannot_read_positions",
                "rollback_read_model_cannot_read_orders",
                "rollback_read_model_cannot_read_fills",
                "rollback_read_model_cannot_read_market_data",
                "rollback_read_model_cannot_open_network_connection",
                "rollback_read_model_cannot_perform_dns_lookup",
                "rollback_read_model_cannot_perform_http_request",
                "rollback_read_model_cannot_open_websocket",
                "rollback_read_model_cannot_read_credentials",
                "rollback_read_model_cannot_read_secrets",
                "rollback_read_model_cannot_read_secure_store",
                "rollback_read_model_cannot_change_qml_or_bridge",
            ]
        },
        "non_activation_evidence": {
            **{
                "block_k_contract_13_0_read": True,
                "observability_read_model_13_1_read": True,
                "audit_envelope_read_model_13_2_read": True,
                "rollback_read_model_built": True,
            },
            **{
                key: False
                for key in [
                    "rollback_executed",
                    "runtime_shutdown_executed",
                    "state_mutated",
                    "order_cancelled",
                    "order_replaced",
                    "audit_writer_started",
                    "audit_exported",
                    "audit_file_read",
                    "audit_file_written",
                    "log_file_read",
                    "log_file_written",
                    "observability_runtime_started",
                    "metrics_collected",
                    "metrics_exported",
                    "soak_runtime_started",
                    "soak_scheduler_started",
                    "filesystem_io_performed",
                    "risk_runtime_enforcement_started",
                    "limit_runtime_enforcement_started",
                    "kill_switch_runtime_trigger_enabled",
                    "manual_kill_switch_trigger_enabled",
                    "automatic_kill_switch_trigger_enabled",
                    "kill_switch_state_mutated",
                    "order_generated",
                    "order_submitted",
                    "position_mutated",
                    "private_endpoint_accessed",
                    "account_read_performed",
                    "balance_read_performed",
                    "positions_read_performed",
                    "orders_read_performed",
                    "fills_read_performed",
                    "market_data_read_performed",
                    "adapter_instantiated",
                    "adapter_wired_to_runtime",
                    "runtime_started",
                    "scheduler_started",
                    "network_io_performed",
                    "dns_lookup_performed",
                    "http_request_performed",
                    "websocket_opened",
                    "credentials_read",
                    "secrets_read",
                    "secure_store_read",
                    "secure_store_write",
                    "config_files_read",
                    "config_discovery_performed",
                    "yaml_parsed",
                    "json_parsed",
                    "environment_variables_read",
                    "trading_controller_touched",
                    "decision_envelope_touched",
                    "qml_changed",
                    "bridge_api_changed",
                ]
            },
        },
        "source_boundaries": SOURCE_BOUNDARIES,
        "future_steps": [
            "functional_preview_13_4_soak_read_model",
            "functional_preview_13_5_observability_audit_rollback_soak_gate_matrix",
            "functional_preview_13_6_block_k_closure_audit",
        ],
        "status": STATUS,
    }
