"""FUNCTIONAL-PREVIEW-13.4 Block K soak read model.

Pure-data read model for planned Block K soak readiness. This module only
assembles static dictionaries from accepted Block K 13.0, 13.1, 13.2, and 13.3
safe subsets. It does not run soak, start schedulers or loops, collect metrics,
write audits, touch files, access networks, execute rollback, submit orders, or
change QML/bridge/runtime surfaces.
"""

from __future__ import annotations

from typing import Any, Final

from ui.pyside_app.preview_audit_envelope_read_model import (
    build_preview_audit_envelope_read_model,
)
from ui.pyside_app.preview_observability_audit_rollback_soak_contract import (
    build_preview_observability_audit_rollback_soak_contract,
)
from ui.pyside_app.preview_observability_read_model import build_preview_observability_read_model
from ui.pyside_app.preview_rollback_read_model import build_preview_rollback_read_model

PREVIEW_SOAK_READ_MODEL_SCHEMA_VERSION: Final[str] = "preview_soak_read_model.v1"
PREVIEW_SOAK_READ_MODEL_KIND: Final[str] = "functional_preview_block_k_soak_read_model"
BLOCK_ID: Final[str] = "K"
STEP_ID: Final[str] = "13.4"
SOAK_READ_MODEL_STATUS: Final[str] = "soak_read_model_ready_no_runtime_no_scheduler"
SOAK_READ_MODEL_DECISION: Final[str] = "BUILD_SOAK_READ_MODEL_ONLY_NO_RUNTIME_NO_SCHEDULER_NO_IO"
READY_FOR_BLOCK_K_5: Final[bool] = True
NEXT_STEP: Final[str] = "FUNCTIONAL-PREVIEW-13.5"
NEXT_STEP_TITLE: Final[str] = "OBSERVABILITY AUDIT ROLLBACK SOAK GATE MATRIX"
STATUS: Final[str] = (
    "ready_for_functional_preview_13_5_observability_audit_rollback_soak_gate_matrix"
)

_BLOCK_K_CONTRACT_SAFE_KEYS: Final[list[str]] = [
    "schema_version",
    "observability_audit_rollback_soak_contract_kind",
    "observability_audit_rollback_soak_contract_status",
    "observability_audit_rollback_soak_contract_decision",
    "ready_for_block_k_1",
    "next_step",
    "next_step_title",
    "status",
]
_OBSERVABILITY_READ_MODEL_SAFE_KEYS: Final[list[str]] = [
    "schema_version",
    "observability_read_model_kind",
    "observability_read_model_status",
    "observability_read_model_decision",
    "ready_for_block_k_2",
    "next_step",
    "next_step_title",
    "status",
]
_AUDIT_ENVELOPE_READ_MODEL_SAFE_KEYS: Final[list[str]] = [
    "schema_version",
    "audit_envelope_read_model_kind",
    "audit_envelope_read_model_status",
    "audit_envelope_read_model_decision",
    "ready_for_block_k_3",
    "next_step",
    "next_step_title",
    "status",
]
_ROLLBACK_READ_MODEL_SAFE_KEYS: Final[list[str]] = [
    "schema_version",
    "rollback_read_model_kind",
    "rollback_read_model_status",
    "rollback_read_model_decision",
    "ready_for_block_k_4",
    "next_step",
    "next_step_title",
    "status",
]

_SCOPE_FALSE_FLAGS: Final[list[str]] = [
    "soak_runtime_allowed_now",
    "soak_scheduler_allowed_now",
    "runtime_loop_allowed_now",
    "wall_clock_measurement_allowed_now",
    "stability_probe_allowed_now",
    "metrics_collection_allowed_now",
    "metrics_export_allowed_now",
    "observability_runtime_allowed_now",
    "runtime_metrics_collection_allowed_now",
    "audit_writer_allowed_now",
    "audit_export_allowed_now",
    "audit_file_read_allowed_now",
    "audit_file_write_allowed_now",
    "log_file_read_allowed_now",
    "log_file_write_allowed_now",
    "filesystem_io_allowed_now",
    "rollback_execution_allowed_now",
    "runtime_shutdown_allowed_now",
    "state_mutation_allowed_now",
    "order_cancel_allowed_now",
    "order_replace_allowed_now",
    "order_generation_allowed_now",
    "order_submission_allowed_now",
    "position_mutation_allowed_now",
    "private_endpoint_access_allowed_now",
    "account_read_allowed_now",
    "balance_read_allowed_now",
    "positions_read_allowed_now",
    "orders_read_allowed_now",
    "fills_read_allowed_now",
    "market_data_read_allowed_now",
    "network_io_allowed_now",
    "dns_lookup_allowed_now",
    "http_request_allowed_now",
    "websocket_allowed_now",
    "adapter_instantiation_allowed_now",
    "adapter_wiring_allowed_now",
    "scheduler_allowed_now",
    "config_file_read_allowed_now",
    "config_discovery_allowed_now",
    "yaml_parse_allowed_now",
    "json_parse_allowed_now",
    "environment_variable_read_allowed_now",
    "credential_secret_read_allowed_now",
    "credential_validation_allowed_now",
    "secure_store_read_allowed_now",
    "secure_store_write_allowed_now",
    "qml_changes_allowed",
    "new_qml_method_calls_allowed",
    "bridge_api_changes_allowed",
    "exe_packaging_in_scope",
    "bat_productization_allowed",
]

_ENTRY_DEFINITIONS: Final[list[dict[str, str]]] = [
    {
        "source_soak_id": "paper_runtime_soak",
        "display_name": "Paper runtime soak",
        "soak_domain": "paper_runtime",
        "planned_soak_source": "future_paper_runtime_soak_plan",
        "planned_soak_type": "paper_runtime_stability",
        "required_soak_profile": "paper_runtime_soak_profile",
        "planned_window_class": "future_short_window_planned_only",
        "planned_exit_criteria_profile": "paper_runtime_exit_criteria_profile",
        "planned_failure_audit_event_id": "soak_event",
    },
    {
        "source_soak_id": "testnet_runtime_soak",
        "display_name": "Testnet runtime soak",
        "soak_domain": "testnet_runtime",
        "planned_soak_source": "future_testnet_runtime_soak_plan",
        "planned_soak_type": "testnet_runtime_stability",
        "required_soak_profile": "testnet_runtime_soak_profile",
        "planned_window_class": "future_standard_window_planned_only",
        "planned_exit_criteria_profile": "testnet_runtime_exit_criteria_profile",
        "planned_failure_audit_event_id": "soak_event",
    },
    {
        "source_soak_id": "audit_pipeline_soak",
        "display_name": "Audit pipeline soak",
        "soak_domain": "audit",
        "planned_soak_source": "future_audit_pipeline_soak_plan",
        "planned_soak_type": "audit_pipeline_stability",
        "required_soak_profile": "audit_pipeline_soak_profile",
        "planned_window_class": "future_short_window_planned_only",
        "planned_exit_criteria_profile": "audit_pipeline_exit_criteria_profile",
        "planned_failure_audit_event_id": "audit_failure_rollback",
    },
    {
        "source_soak_id": "rollback_readiness_soak",
        "display_name": "Rollback readiness soak",
        "soak_domain": "rollback",
        "planned_soak_source": "future_rollback_readiness_soak_plan",
        "planned_soak_type": "rollback_readiness_stability",
        "required_soak_profile": "rollback_readiness_soak_profile",
        "planned_window_class": "future_short_window_planned_only",
        "planned_exit_criteria_profile": "rollback_readiness_exit_criteria_profile",
        "planned_failure_audit_event_id": "rollback_event",
    },
    {
        "source_soak_id": "risk_gate_soak",
        "display_name": "Risk gate soak",
        "soak_domain": "risk",
        "planned_soak_source": "future_risk_gate_soak_plan",
        "planned_soak_type": "risk_gate_stability",
        "required_soak_profile": "risk_gate_soak_profile",
        "planned_window_class": "future_standard_window_planned_only",
        "planned_exit_criteria_profile": "risk_gate_exit_criteria_profile",
        "planned_failure_audit_event_id": "risk_gate_event",
    },
    {
        "source_soak_id": "order_flow_block_soak",
        "display_name": "Order flow block soak",
        "soak_domain": "order_flow",
        "planned_soak_source": "future_order_flow_block_soak_plan",
        "planned_soak_type": "order_flow_block_stability",
        "required_soak_profile": "order_flow_block_soak_profile",
        "planned_window_class": "future_standard_window_planned_only",
        "planned_exit_criteria_profile": "order_flow_block_exit_criteria_profile",
        "planned_failure_audit_event_id": "order_flow_event",
    },
    {
        "source_soak_id": "private_endpoint_block_soak",
        "display_name": "Private endpoint block soak",
        "soak_domain": "private_endpoint",
        "planned_soak_source": "future_private_endpoint_block_soak_plan",
        "planned_soak_type": "private_endpoint_block_stability",
        "required_soak_profile": "private_endpoint_block_soak_profile",
        "planned_window_class": "future_standard_window_planned_only",
        "planned_exit_criteria_profile": "private_endpoint_block_exit_criteria_profile",
        "planned_failure_audit_event_id": "private_endpoint_gate_event",
    },
    {
        "source_soak_id": "network_block_soak",
        "display_name": "Network block soak",
        "soak_domain": "network",
        "planned_soak_source": "future_network_block_soak_plan",
        "planned_soak_type": "network_block_stability",
        "required_soak_profile": "network_block_soak_profile",
        "planned_window_class": "future_standard_window_planned_only",
        "planned_exit_criteria_profile": "network_block_exit_criteria_profile",
        "planned_failure_audit_event_id": "network_gate_event",
    },
]
_REQUIRED_FIELD_NAMES: Final[list[str]] = [
    "soak_id",
    "soak_type",
    "soak_window_class",
    "source_component",
    "required_exit_criteria",
    "failure_audit_event_id",
    "rollback_readiness_state",
    "safety_gate_state",
    "runtime_liveness_state",
    "soak_blocking_reason",
]
BLOCKED_SOAK_READ_MODEL_CAPABILITIES: Final[list[str]] = [
    "soak runtime",
    "soak scheduler",
    "runtime loop",
    "wall-clock runtime measurement",
    "stability probe",
    "metrics collection",
    "metrics export",
    "audit writer",
    "audit export",
    "audit file read",
    "audit file write",
    "log file read",
    "log file write",
    "filesystem I/O",
    "rollback execution",
    "runtime shutdown",
    "state mutation",
    "order cancel",
    "order replace",
    "observability runtime collection",
    "risk runtime enforcement",
    "limit runtime enforcement",
    "kill switch runtime trigger",
    "manual kill switch trigger",
    "automatic kill switch trigger",
    "kill switch state mutation",
    "order generation",
    "order submission",
    "position mutation",
    "private endpoint access",
    "account read",
    "balance read",
    "positions read",
    "orders read",
    "fills read",
    "market data read",
    "adapter instantiation",
    "adapter runtime wiring",
    "scheduler",
    "network I/O",
    "DNS lookup",
    "HTTP request",
    "WebSocket connection",
    "credential read",
    "secret read",
    "secure store read",
    "secure store write",
    "config file read",
    "config discovery",
    "YAML parse",
    "JSON parse",
    "environment variable read",
    "TradingController change",
    "DecisionEnvelope change",
    "QML action dispatch",
    "bridge API changes",
    "PyInstaller/EXE packaging",
]
SOURCE_BOUNDARIES: Final[list[str]] = [
    "no PySide import",
    "no QML import",
    "no runtime loop import",
    "no scheduler import",
    "no TradingController import",
    "no DecisionEnvelope import",
    "no strategy/AI/scoring/recommendation import",
    "no order module import",
    "no live adapter import",
    "no testnet adapter import",
    "no sandbox adapter import",
    "no exchange adapter runtime import",
    "no account module import",
    "no secrets module import",
    "no security store import",
    "no observability runtime import",
    "no logger/exporter runtime import",
    "no metrics exporter import",
    "no audit writer import",
    "no audit exporter import",
    "no rollback runner import",
    "no rollback executor import",
    "no soak runner import",
    "no soak scheduler import",
    "no filesystem I/O",
    "no audit file read",
    "no audit file write",
    "no log file read",
    "no log file write",
    "no audit write",
    "no audit export",
    "no runtime shutdown",
    "no state mutation",
    "no wall-clock runtime measurement",
    "no stability probe",
    "no config file read",
    "no config discovery",
    "no YAML parse",
    "no JSON parse",
    "no environment variable read",
    "no credential read",
    "no credential validation",
    "no secret material handling",
    "no secure store read",
    "no secure store write",
    "no real market data read",
    "no private endpoint access",
    "no account read",
    "no balance read",
    "no positions read",
    "no orders read",
    "no fills read",
    "no order generation",
    "no order submission",
    "no order cancel",
    "no order replace",
    "no position mutation",
    "no network I/O",
    "no DNS lookup",
    "no HTTP request",
    "no WebSocket connection",
    "no QML changes",
    "no bridge API changes",
    "no .bat changes",
    "no app.py changes",
    "no dependency declarations changes",
    "no workflow changes",
]


def _select(source: dict[str, Any], keys: list[str]) -> dict[str, Any]:
    return {key: source[key] for key in keys}


def _entries() -> list[dict[str, Any]]:
    return [
        {
            "soak_read_model_id": f"soak_read_model_{item['source_soak_id']}",
            "source_soak_id": item["source_soak_id"],
            "display_name": item["display_name"],
            "read_model_classification": "static_soak_read_model_only",
            "soak_domain": item["soak_domain"],
            "planned_soak_source": item["planned_soak_source"],
            "planned_soak_type": item["planned_soak_type"],
            "required_soak_profile": item["required_soak_profile"],
            "planned_window_class": item["planned_window_class"],
            "planned_exit_criteria_profile": item["planned_exit_criteria_profile"],
            "planned_failure_audit_event_id": item["planned_failure_audit_event_id"],
            "operator_visibility": "future_read_only_soak",
            "eligible_for_13_5_gate_matrix": True,
            "soak_runtime_allowed_now": False,
            "soak_scheduler_allowed_now": False,
            "runtime_loop_allowed_now": False,
            "metrics_collection_allowed_now": False,
            "metrics_export_allowed_now": False,
            "filesystem_io_allowed_now": False,
            "network_io_allowed_now": False,
            "order_flow_allowed_now": False,
            "private_endpoint_access_allowed_now": False,
            "safe_for_offline_tests": True,
            "notes": "Static planned soak read-model entry only; never executed in 13.4.",
        }
        for item in _ENTRY_DEFINITIONS
    ]


def _required_fields() -> list[dict[str, Any]]:
    return [
        {
            "field_name": name,
            "field_classification": "planned_soak_readiness_field_only",
            "required_for_future_soak_runner": True,
            "contains_secret_material": False,
            "contains_private_key_material": False,
            "allowed_to_collect_now": False,
            "allowed_to_mutate_now": False,
            "notes": "Declared for a future gated soak runner only; not collected in 13.4.",
        }
        for name in _REQUIRED_FIELD_NAMES
    ]


def build_preview_soak_read_model() -> dict[str, Any]:
    """Build a static Block K soak read model without activating runtime paths."""
    entries = _entries()
    ids = [entry["soak_read_model_id"] for entry in entries]
    return {
        "schema_version": PREVIEW_SOAK_READ_MODEL_SCHEMA_VERSION,
        "soak_read_model_kind": PREVIEW_SOAK_READ_MODEL_KIND,
        "block": BLOCK_ID,
        "step": STEP_ID,
        "soak_read_model_status": SOAK_READ_MODEL_STATUS,
        "soak_read_model_decision": SOAK_READ_MODEL_DECISION,
        "ready_for_block_k_5": READY_FOR_BLOCK_K_5,
        "next_step": NEXT_STEP,
        "next_step_title": NEXT_STEP_TITLE,
        "block_k_contract_reference": _select(
            build_preview_observability_audit_rollback_soak_contract(), _BLOCK_K_CONTRACT_SAFE_KEYS
        ),
        "observability_read_model_reference": _select(
            build_preview_observability_read_model(), _OBSERVABILITY_READ_MODEL_SAFE_KEYS
        ),
        "audit_envelope_read_model_reference": _select(
            build_preview_audit_envelope_read_model(), _AUDIT_ENVELOPE_READ_MODEL_SAFE_KEYS
        ),
        "rollback_read_model_reference": _select(
            build_preview_rollback_read_model(), _ROLLBACK_READ_MODEL_SAFE_KEYS
        ),
        "soak_read_model_scope": {
            "scope_name": "soak_read_model",
            "read_model_only": True,
            "derived_from_block_k_contract_13_0": True,
            "derived_from_observability_read_model_13_1": True,
            "derived_from_audit_envelope_read_model_13_2": True,
            "derived_from_rollback_read_model_13_3": True,
            **{flag: False for flag in _SCOPE_FALSE_FLAGS},
            "exe_direction_preserved": True,
        },
        "soak_read_model_entries": entries,
        "default_soak_read_model_selection": {
            "soak_read_model_id": "soak_read_model_paper_runtime_soak",
            "source_soak_id": "paper_runtime_soak",
            "reason": "first soak read-model scenario; static only, no soak runtime, no scheduler, no runtime loop",
            "soak_runtime_allowed_now": False,
            "soak_scheduler_allowed_now": False,
            "runtime_loop_allowed_now": False,
        },
        "soak_readiness_required_fields": _required_fields(),
        "soak_read_model_summary": {
            "entry_count": 8,
            "required_field_count": 10,
            "default_selection_id": "soak_read_model_paper_runtime_soak",
            "soak_runtime_enabled_entry_count": 0,
            "soak_scheduler_enabled_entry_count": 0,
            "runtime_loop_enabled_entry_count": 0,
            "metrics_collection_enabled_entry_count": 0,
            "metrics_export_enabled_entry_count": 0,
            "filesystem_io_enabled_entry_count": 0,
            "network_enabled_entry_count": 0,
            "order_flow_enabled_entry_count": 0,
            "private_endpoint_enabled_entry_count": 0,
            "offline_safe_entry_count": 8,
            "entries_eligible_for_13_5_gate_matrix": 8,
            "paper_runtime_domain_entry_count": 1,
            "testnet_runtime_domain_entry_count": 1,
            "audit_domain_entry_count": 1,
            "rollback_domain_entry_count": 1,
            "risk_domain_entry_count": 1,
            "order_flow_domain_entry_count": 1,
            "private_endpoint_domain_entry_count": 1,
            "network_domain_entry_count": 1,
            "safe_to_render_in_future_ui_as_read_only": True,
            "safe_for_soak_runtime_now": False,
            "safe_for_scheduler_now": False,
            "safe_for_runtime_loop_now": False,
        },
        "soak_read_model_matrix": {
            "soak_read_model_ids": ids,
            "paper_runtime_domain_ids": ["soak_read_model_paper_runtime_soak"],
            "testnet_runtime_domain_ids": ["soak_read_model_testnet_runtime_soak"],
            "audit_domain_ids": ["soak_read_model_audit_pipeline_soak"],
            "rollback_domain_ids": ["soak_read_model_rollback_readiness_soak"],
            "risk_domain_ids": ["soak_read_model_risk_gate_soak"],
            "order_flow_domain_ids": ["soak_read_model_order_flow_block_soak"],
            "private_endpoint_domain_ids": ["soak_read_model_private_endpoint_block_soak"],
            "network_domain_ids": ["soak_read_model_network_block_soak"],
            "entries_requiring_13_5_gate_matrix": ids,
            "entries_never_run_in_13_4": ids,
            "planned_soak_sources_by_id": {
                entry["soak_read_model_id"]: entry["planned_soak_source"] for entry in entries
            },
            "planned_failure_audit_event_ids_by_id": {
                entry["soak_read_model_id"]: entry["planned_failure_audit_event_id"]
                for entry in entries
            },
            "required_soak_profiles_by_id": {
                entry["soak_read_model_id"]: entry["required_soak_profile"] for entry in entries
            },
            "planned_exit_criteria_profiles_by_id": {
                entry["soak_read_model_id"]: entry["planned_exit_criteria_profile"]
                for entry in entries
            },
        },
        "soak_surface_contract": {
            "surface_contract_id": "block_k_soak_read_model_surface_contract",
            "read_model_is_static": True,
            "soak_scenarios_are_planned_only": True,
            "soak_is_not_run_now": True,
            "soak_scheduler_is_not_started_now": True,
            "runtime_loop_is_not_started_now": True,
            "metrics_are_not_collected_now": True,
            "metrics_are_not_exported_now": True,
            "logs_are_not_read_now": True,
            "logs_are_not_written_now": True,
            "filesystem_io_forbidden_now": True,
            "network_io_forbidden_now": True,
            "runner_requires_future_gate": True,
            "ui_surface_requires_future_qml_gate": True,
        },
        "blocked_soak_read_model_capabilities": BLOCKED_SOAK_READ_MODEL_CAPABILITIES,
        "soak_read_model_boundaries": {
            key: True
            for key in [
                "soak_read_model_is_static",
                "soak_read_model_is_derived_from_13_0_contract",
                "soak_read_model_is_derived_from_13_1_observability",
                "soak_read_model_is_derived_from_13_2_audit_envelope",
                "soak_read_model_is_derived_from_13_3_rollback",
                "soak_read_model_can_feed_13_5_gate_matrix",
                "soak_read_model_cannot_feed_runtime_directly",
                "soak_read_model_cannot_run_soak",
                "soak_read_model_cannot_start_scheduler",
                "soak_read_model_cannot_start_runtime_loop",
                "soak_read_model_cannot_measure_wall_clock_runtime",
                "soak_read_model_cannot_run_stability_probe",
                "soak_read_model_cannot_collect_metrics",
                "soak_read_model_cannot_export_metrics",
                "soak_read_model_cannot_write_audit",
                "soak_read_model_cannot_export_audit",
                "soak_read_model_cannot_read_audit_files",
                "soak_read_model_cannot_write_audit_files",
                "soak_read_model_cannot_read_logs",
                "soak_read_model_cannot_write_logs",
                "soak_read_model_cannot_touch_filesystem",
                "soak_read_model_cannot_execute_rollback",
                "soak_read_model_cannot_execute_runtime_shutdown",
                "soak_read_model_cannot_mutate_state",
                "soak_read_model_cannot_cancel_orders",
                "soak_read_model_cannot_replace_orders",
                "soak_read_model_cannot_enable_runtime",
                "soak_read_model_cannot_enforce_limits",
                "soak_read_model_cannot_trigger_kill_switch",
                "soak_read_model_cannot_mutate_kill_switch_state",
                "soak_read_model_cannot_generate_orders",
                "soak_read_model_cannot_submit_orders",
                "soak_read_model_cannot_access_private_endpoints",
                "soak_read_model_cannot_read_account",
                "soak_read_model_balance_read_blocked",
                "soak_read_model_cannot_read_positions",
                "soak_read_model_cannot_read_orders",
                "soak_read_model_cannot_read_fills",
                "soak_read_model_cannot_read_market_data",
                "soak_read_model_cannot_open_network_connection",
                "soak_read_model_cannot_perform_dns_lookup",
                "soak_read_model_cannot_perform_http_request",
                "soak_read_model_cannot_open_websocket",
                "soak_read_model_cannot_read_credentials",
                "soak_read_model_cannot_read_secrets",
                "soak_read_model_cannot_read_secure_store",
                "soak_read_model_cannot_change_qml_or_bridge",
            ]
        },
        "non_activation_evidence": {
            "block_k_contract_13_0_read": True,
            "observability_read_model_13_1_read": True,
            "audit_envelope_read_model_13_2_read": True,
            "rollback_read_model_13_3_read": True,
            "soak_read_model_built": True,
            **{
                key: False
                for key in [
                    "soak_runtime_started",
                    "soak_scheduler_started",
                    "runtime_loop_started",
                    "wall_clock_runtime_measured",
                    "stability_probe_started",
                    "metrics_collected",
                    "metrics_exported",
                    "audit_writer_started",
                    "audit_exported",
                    "audit_file_read",
                    "audit_file_written",
                    "log_file_read",
                    "log_file_written",
                    "rollback_executed",
                    "runtime_shutdown_executed",
                    "state_mutated",
                    "order_cancelled",
                    "order_replaced",
                    "observability_runtime_started",
                    "filesystem_io_performed",
                    "risk_runtime_enforcement_started",
                    "limit_runtime_enforcement_started",
                    "kill_switch_runtime_trigger_enabled",
                    "manual_kill_switch_trigger_enabled",
                    "automatic_kill_switch_trigger_enabled",
                    "kill_switch_state_mutated",
                    "order_generated",
                    "order_submitted",
                    "position_mutated",
                    "private_endpoint_accessed",
                    "account_read_performed",
                    "balance_read_performed",
                    "positions_read_performed",
                    "orders_read_performed",
                    "fills_read_performed",
                    "market_data_read_performed",
                    "adapter_instantiated",
                    "adapter_wired_to_runtime",
                    "runtime_started",
                    "scheduler_started",
                    "network_io_performed",
                    "dns_lookup_performed",
                    "http_request_performed",
                    "websocket_opened",
                    "credentials_read",
                    "secrets_read",
                    "secure_store_read",
                    "secure_store_write",
                    "config_files_read",
                    "config_discovery_performed",
                    "yaml_parsed",
                    "json_parsed",
                    "environment_variables_read",
                    "trading_controller_touched",
                    "decision_envelope_touched",
                    "qml_changed",
                    "bridge_api_changed",
                ]
            },
        },
        "source_boundaries": SOURCE_BOUNDARIES,
        "future_steps": [
            "functional_preview_13_5_observability_audit_rollback_soak_gate_matrix",
            "functional_preview_13_6_block_k_closure_audit",
        ],
        "status": STATUS,
    }
