"""Pure-data FUNCTIONAL-PREVIEW-10.3 BLOK H market data audit envelope.

This module builds a local, static, read-only audit envelope over the 10.2
market-data fixture. It intentionally does not implement a market-data adapter,
fetch market data, perform network I/O, access accounts, read credentials,
start runtimes, export audit data, or integrate with QML/trading paths.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any, Final

from ui.pyside_app.preview_read_only_market_data_static_fixture import (
    build_preview_read_only_market_data_static_fixture,
)

PREVIEW_READ_ONLY_MARKET_DATA_AUDIT_ENVELOPE_SCHEMA_VERSION: Final[str] = (
    "preview_read_only_market_data_audit_envelope.v1"
)
PREVIEW_READ_ONLY_MARKET_DATA_AUDIT_ENVELOPE_KIND: Final[str] = (
    "functional_preview_block_h_read_only_market_data_audit_envelope"
)
BLOCK_ID: Final[str] = "H"
STEP_ID: Final[str] = "10.3"
READ_ONLY_MARKET_DATA_AUDIT_ENVELOPE_STATUS: Final[str] = (
    "read_only_market_data_audit_envelope_ready_no_export_no_network_io"
)
READ_ONLY_MARKET_DATA_AUDIT_ENVELOPE_DECISION: Final[str] = (
    "BUILD_AUDIT_ENVELOPE_ONLY_NO_NETWORK_IO_NO_MARKET_DATA_FETCH_NO_EXPORT"
)
READY_FOR_BLOCK_H_4: Final[bool] = True
NEXT_STEP: Final[str] = "FUNCTIONAL-PREVIEW-10.4"
NEXT_STEP_TITLE: Final[str] = "READ-ONLY MARKET DATA UI READ-ONLY SURFACE"

_ALLOWLIST_FIELDS: Final[tuple[str, ...]] = (
    "symbol",
    "timestamp",
    "bid",
    "ask",
    "last",
    "volume",
    "source",
    "latency_ms_preview",
)
_DENYLIST_FIELDS: Final[tuple[str, ...]] = (
    "account_id",
    "balance",
    "position",
    "order_id",
    "fill_id",
    "api_key",
    "secret",
    "private_endpoint",
)
_BLOCKED_CAPABILITIES: Final[tuple[str, ...]] = (
    "market data adapter implementation now",
    "network I/O",
    "live market data fetch now",
    "exchange API connection",
    "private account endpoint access",
    "account balance fetch",
    "positions fetch",
    "orders fetch",
    "fills fetch",
    "order generation",
    "order submission",
    "fill simulation",
    "lifecycle mutation",
    "runtime loop",
    "scheduler",
    "audit export",
    "TradingController / DecisionEnvelope",
    "live/testnet/account/secrets/export/cloud",
    "QML changes / new QML calls",
    "EXE packaging",
)
_SOURCE_BOUNDARIES: Final[tuple[str, ...]] = (
    "no PySide import",
    "no QML import",
    "no runtime loop import",
    "no scheduler import",
    "no TradingController import",
    "no DecisionEnvelope import",
    "no strategy/AI/scoring/recommendation import",
    "no order module import",
    "no live adapter import",
    "no testnet adapter import",
    "no market data runtime adapter import",
    "no account module import",
    "no secrets module import",
    "no filesystem I/O",
    "no network I/O",
    "no QML changes",
    "no .bat changes",
    "no app.py changes",
    "no dependency declarations changes",
    "no workflow changes",
)
_AUDIT_EVENTS: Final[tuple[dict[str, str | bool], ...]] = (
    {
        "event_id": "market-data-audit-0001-btc-usdt-static-fixture",
        "symbol": "BTC/USDT",
        "event_type": "read_only_market_data_fixture_row_audited",
        "source": "static_fixture",
        "quality_status": "ok_preview_only",
        "field_boundary_status": "allowlist_only_private_fields_absent",
        "network_io_performed": False,
        "market_data_fetch_performed": False,
        "account_data_present": False,
        "order_or_fill_data_present": False,
        "credentials_or_secrets_present": False,
        "exported": False,
    },
    {
        "event_id": "market-data-audit-0002-eth-usdt-static-fixture",
        "symbol": "ETH/USDT",
        "event_type": "read_only_market_data_fixture_row_audited",
        "source": "static_fixture",
        "quality_status": "ok_preview_only",
        "field_boundary_status": "allowlist_only_private_fields_absent",
        "network_io_performed": False,
        "market_data_fetch_performed": False,
        "account_data_present": False,
        "order_or_fill_data_present": False,
        "credentials_or_secrets_present": False,
        "exported": False,
    },
    {
        "event_id": "market-data-audit-0003-sol-usdt-low-liquidity-preview",
        "symbol": "SOL/USDT",
        "event_type": "read_only_market_data_fixture_row_audited",
        "source": "static_fixture_low_liquidity_preview",
        "quality_status": "low_liquidity_preview_only",
        "field_boundary_status": "allowlist_only_private_fields_absent",
        "network_io_performed": False,
        "market_data_fetch_performed": False,
        "account_data_present": False,
        "order_or_fill_data_present": False,
        "credentials_or_secrets_present": False,
        "exported": False,
    },
    {
        "event_id": "market-data-audit-0004-ada-usdt-stale-preview",
        "symbol": "ADA/USDT",
        "event_type": "read_only_market_data_fixture_row_audited",
        "source": "static_fixture_stale_preview",
        "quality_status": "stale_preview_only",
        "field_boundary_status": "allowlist_only_private_fields_absent",
        "network_io_performed": False,
        "market_data_fetch_performed": False,
        "account_data_present": False,
        "order_or_fill_data_present": False,
        "credentials_or_secrets_present": False,
        "exported": False,
    },
)


def _static_fixture_reference() -> dict[str, Any]:
    fixture = build_preview_read_only_market_data_static_fixture()
    return {
        "schema_version": fixture["schema_version"],
        "market_data_static_fixture_kind": fixture["market_data_static_fixture_kind"],
        "market_data_static_fixture_status": fixture["market_data_static_fixture_status"],
        "market_data_static_fixture_decision": fixture["market_data_static_fixture_decision"],
        "ready_for_block_h_3": fixture["ready_for_block_h_3"],
        "next_step": fixture["next_step"],
        "next_step_title": fixture["next_step_title"],
        "status": fixture["status"],
    }


def build_preview_read_only_market_data_audit_envelope() -> dict[str, Any]:
    """Build the inert FUNCTIONAL-PREVIEW-10.3 Block H audit envelope."""

    envelope: dict[str, Any] = {
        "schema_version": PREVIEW_READ_ONLY_MARKET_DATA_AUDIT_ENVELOPE_SCHEMA_VERSION,
        "market_data_audit_envelope_kind": PREVIEW_READ_ONLY_MARKET_DATA_AUDIT_ENVELOPE_KIND,
        "block": BLOCK_ID,
        "step": STEP_ID,
        "market_data_audit_envelope_status": READ_ONLY_MARKET_DATA_AUDIT_ENVELOPE_STATUS,
        "market_data_audit_envelope_decision": READ_ONLY_MARKET_DATA_AUDIT_ENVELOPE_DECISION,
        "ready_for_block_h_4": READY_FOR_BLOCK_H_4,
        "next_step": NEXT_STEP,
        "next_step_title": NEXT_STEP_TITLE,
        "static_fixture_reference": _static_fixture_reference(),
        "audit_envelope_scope": {
            "scope_name": "read_only_market_data_audit_envelope",
            "audit_envelope_only": True,
            "static_fixture_reference_required": True,
            "adapter_implemented_now": False,
            "network_io_allowed_now": False,
            "market_data_fetch_allowed_now": False,
            "live_market_data_fetch_allowed_now": False,
            "exchange_connection_allowed_now": False,
            "audit_export_allowed_now": False,
            "fixture_data_read_allowed_now": True,
            "fixture_row_audit_allowed_now": True,
            "field_boundary_audit_allowed_now": True,
            "data_quality_audit_preview_allowed_now": True,
            "ui_surface_allowed_next_step": True,
            "account_data_allowed": False,
            "balance_data_allowed": False,
            "orders_allowed": False,
            "fills_allowed": False,
            "trading_allowed": False,
            "credentials_allowed": False,
            "secrets_allowed": False,
            "export_allowed": False,
        },
        "market_data_audit_envelope": {
            "audit_envelope_available": True,
            "audit_envelope_static_only": True,
            "audit_envelope_executable": False,
            "audit_envelope_name": "read_only_market_data_preview_audit_envelope",
            "audit_source_mode": "local_static_fixture_audit_no_network_io",
            "audited_fixture_available": True,
            "audited_fixture_row_count": 4,
            "audit_event_count": 4,
            "audit_source": "functional_preview_static_fixture",
            "audit_version": "10.3",
            "audit_generated_from_network": False,
            "audit_generated_from_account": False,
            "audit_contains_private_data": False,
            "audit_contains_orders_or_fills": False,
            "audit_contains_credentials_or_secrets": False,
            "audit_exported": False,
            "network_io_allowed_now": False,
            "market_fetch_performed": False,
            "runtime_execution_allowed": False,
            "trading_execution_allowed": False,
            "account_access_allowed": False,
            "credentials_access_allowed": False,
        },
        "audit_events": [dict(event) for event in _AUDIT_EVENTS],
        "fixture_row_audit_summary": {
            "row_audit_available": True,
            "row_audit_static_only": True,
            "row_audit_executable": False,
            "row_count": 4,
            "audited_symbols": ["BTC/USDT", "ETH/USDT", "SOL/USDT", "ADA/USDT"],
            "normal_preview_symbols": ["BTC/USDT", "ETH/USDT"],
            "low_liquidity_preview_symbols": ["SOL/USDT"],
            "stale_preview_symbols": ["ADA/USDT"],
            "all_rows_audited": True,
            "all_rows_allowlist_only": True,
            "private_fields_absent": True,
            "account_fields_absent": True,
            "order_fields_absent": True,
            "fill_fields_absent": True,
            "credentials_fields_absent": True,
            "network_required_for_audit": False,
            "market_data_fetch_required_for_audit": False,
            "export_required_for_audit": False,
        },
        "field_boundary_audit": {
            "field_boundary_audit_available": True,
            "field_boundary_static_only": True,
            "field_boundary_executable": False,
            "allowlist_fields": list(_ALLOWLIST_FIELDS),
            "denylist_fields": list(_DENYLIST_FIELDS),
            "allowlist_denylist_disjoint": True,
            "fixture_rows_match_allowlist": True,
            "fixture_rows_contain_denylist_fields": False,
            "private_field_leak_detected": False,
            "account_field_leak_detected": False,
            "order_field_leak_detected": False,
            "fill_field_leak_detected": False,
            "credentials_field_leak_detected": False,
        },
        "data_quality_audit_preview": {
            "quality_audit_available": True,
            "quality_audit_static_only": True,
            "quality_audit_executable": False,
            "row_count": 4,
            "normal_preview_count": 2,
            "low_liquidity_preview_count": 1,
            "stale_preview_count": 1,
            "all_rows_have_bid_less_than_or_equal_ask": True,
            "all_rows_have_last_within_bid_ask": True,
            "all_rows_have_non_negative_volume": True,
            "all_rows_have_non_negative_latency": True,
            "market_data_fetch_required_for_quality": False,
            "network_required_now": False,
            "account_required_now": False,
        },
        "no_fetch_no_export_no_execution_evidence": {
            "audit_envelope_evaluated": True,
            "static_fixture_read": True,
            "audit_events_built_from_static_literals": True,
            "adapter_implemented": False,
            "network_io_performed": False,
            "market_data_fetch_performed": False,
            "exchange_connection_opened": False,
            "private_endpoint_accessed": False,
            "account_fetch_performed": False,
            "balance_fetch_performed": False,
            "positions_fetch_performed": False,
            "orders_fetch_performed": False,
            "fills_fetch_performed": False,
            "order_generated": False,
            "order_submitted": False,
            "fill_simulated": False,
            "lifecycle_mutated": False,
            "runtime_loop_started": False,
            "scheduler_started": False,
            "trading_controller_touched": False,
            "decision_envelope_touched": False,
            "secrets_read_performed": False,
            "audit_export_performed": False,
            "export_performed": False,
            "qml_changes_performed": False,
        },
        "boundary_checks": {
            "local_only": True,
            "block_h_audit_envelope_only": True,
            "static_fixture_reference_valid": True,
            "read_only_market_data_scope_defined": True,
            "adapter_implemented_now": False,
            "audit_envelope_available_now": True,
            "audit_envelope_static_only": True,
            "audit_envelope_executable": False,
            "audit_export_allowed_now": False,
            "network_io_allowed_now": False,
            "market_data_fetch_allowed_now": False,
            "live_market_data_fetch_allowed_now": False,
            "exchange_connection_allowed_now": False,
            "public_market_data_allowed_future_only": True,
            "recorded_replay_allowed_future_only": True,
            "private_account_data_allowed": False,
            "account_fetch_allowed": False,
            "balance_fetch_allowed": False,
            "positions_fetch_allowed": False,
            "orders_fetch_allowed": False,
            "fills_fetch_allowed": False,
            "order_generation_allowed": False,
            "order_submission_allowed": False,
            "fill_simulation_allowed": False,
            "lifecycle_mutation_allowed": False,
            "runtime_loop_allowed": False,
            "scheduler_allowed": False,
            "trading_controller_allowed": False,
            "decision_envelope_allowed": False,
            "strategy_execution_allowed": False,
            "ai_scoring_execution_allowed": False,
            "model_inference_execution_allowed": False,
            "live_mode_allowed": False,
            "testnet_mode_allowed_initially": False,
            "live_credentials_allowed": False,
            "secrets_read_allowed": False,
            "secrets_export_allowed": False,
            "cloud_export_allowed": False,
            "external_export_allowed": False,
            "dynamic_action_dispatch_allowed": False,
            "new_qml_method_calls_allowed": False,
            "qml_changes_allowed": False,
            "exe_packaging_in_scope": False,
            "bat_productization_allowed": False,
            "exe_direction_preserved": True,
            "ready_for_block_h_4": True,
        },
        "blocked_capabilities": list(_BLOCKED_CAPABILITIES),
        "source_boundaries": list(_SOURCE_BOUNDARIES),
        "future_steps": [
            "functional_preview_10_4_read_only_market_data_ui_read_only_surface",
            "functional_preview_10_5_read_only_market_data_selection_gate",
            "functional_preview_10_6_read_only_market_data_controlled_refresh_preview",
        ],
        "status": "ready_for_functional_preview_10_4_read_only_market_data_ui_read_only_surface",
    }
    return deepcopy(envelope)
