"""FUNCTIONAL-PREVIEW-13.1 Block K observability read model.

Pure-data read model for planned Block K observability signals. This module
only assembles static dictionaries and does not collect metrics, export data,
read or write logs, perform filesystem/network I/O, touch QML/bridge surfaces,
or activate any runtime behavior.
"""

from __future__ import annotations

from typing import Any, Final

from ui.pyside_app.preview_observability_audit_rollback_soak_contract import (
    build_preview_observability_audit_rollback_soak_contract,
)

PREVIEW_OBSERVABILITY_READ_MODEL_SCHEMA_VERSION: Final[str] = "preview_observability_read_model.v1"
PREVIEW_OBSERVABILITY_READ_MODEL_KIND: Final[str] = (
    "functional_preview_block_k_observability_read_model"
)
BLOCK_ID: Final[str] = "K"
STEP_ID: Final[str] = "13.1"
OBSERVABILITY_READ_MODEL_STATUS: Final[str] = "observability_read_model_ready_no_runtime_collection"
OBSERVABILITY_READ_MODEL_DECISION: Final[str] = (
    "BUILD_OBSERVABILITY_READ_MODEL_ONLY_NO_RUNTIME_COLLECTION_NO_EXPORTS_NO_IO"
)
READY_FOR_BLOCK_K_2: Final[bool] = True
NEXT_STEP: Final[str] = "FUNCTIONAL-PREVIEW-13.2"
NEXT_STEP_TITLE: Final[str] = "AUDIT ENVELOPE READ MODEL"
STATUS: Final[str] = "ready_for_functional_preview_13_2_audit_envelope_read_model"

_BLOCK_K_CONTRACT_SAFE_KEYS: Final[list[str]] = [
    "schema_version",
    "observability_audit_rollback_soak_contract_kind",
    "observability_audit_rollback_soak_contract_status",
    "observability_audit_rollback_soak_contract_decision",
    "ready_for_block_k_1",
    "next_step",
    "next_step_title",
    "status",
]

_FALSE_SCOPE_FLAGS: Final[list[str]] = [
    "observability_runtime_allowed_now",
    "runtime_metrics_collection_allowed_now",
    "metrics_export_allowed_now",
    "log_file_read_allowed_now",
    "log_file_write_allowed_now",
    "filesystem_io_allowed_now",
    "audit_writer_allowed_now",
    "audit_export_allowed_now",
    "rollback_execution_allowed_now",
    "soak_runtime_allowed_now",
    "runtime_enforcement_allowed_now",
    "risk_decision_runtime_allowed_now",
    "limit_enforcement_runtime_allowed_now",
    "kill_switch_runtime_allowed_now",
    "manual_trigger_allowed_now",
    "automatic_trigger_allowed_now",
    "kill_switch_state_mutation_allowed_now",
    "order_generation_allowed_now",
    "order_submission_allowed_now",
    "order_cancel_allowed_now",
    "order_replace_allowed_now",
    "position_mutation_allowed_now",
    "private_endpoint_access_allowed_now",
    "account_read_allowed_now",
    "balance_read_allowed_now",
    "positions_read_allowed_now",
    "orders_read_allowed_now",
    "fills_read_allowed_now",
    "market_data_read_allowed_now",
    "network_io_allowed_now",
    "dns_lookup_allowed_now",
    "http_request_allowed_now",
    "websocket_allowed_now",
    "adapter_instantiation_allowed_now",
    "adapter_wiring_allowed_now",
    "scheduler_allowed_now",
    "config_file_read_allowed_now",
    "config_discovery_allowed_now",
    "yaml_parse_allowed_now",
    "json_parse_allowed_now",
    "environment_variable_read_allowed_now",
    "credential_secret_read_allowed_now",
    "credential_validation_allowed_now",
    "secure_store_read_allowed_now",
    "secure_store_write_allowed_now",
    "qml_changes_allowed",
    "new_qml_method_calls_allowed",
    "bridge_api_changes_allowed",
    "exe_packaging_in_scope",
    "bat_productization_allowed",
]

_ENTRY_DEFINITIONS: Final[list[dict[str, str]]] = [
    {
        "source_observability_id": "runtime_liveness",
        "display_name": "Runtime liveness",
        "observation_domain": "runtime",
        "planned_signal_source": "future_runtime_liveness_probe",
        "planned_signal_type": "status",
        "planned_display_group": "runtime_health",
    },
    {
        "source_observability_id": "runtime_safety_gate",
        "display_name": "Runtime safety gate",
        "observation_domain": "safety",
        "planned_signal_source": "future_safety_gate_probe",
        "planned_signal_type": "gate_state",
        "planned_display_group": "safety",
    },
    {
        "source_observability_id": "audit_envelope_health",
        "display_name": "Audit envelope health",
        "observation_domain": "audit",
        "planned_signal_source": "future_audit_envelope_probe",
        "planned_signal_type": "health",
        "planned_display_group": "audit",
    },
    {
        "source_observability_id": "rollback_readiness",
        "display_name": "Rollback readiness",
        "observation_domain": "rollback",
        "planned_signal_source": "future_rollback_readiness_probe",
        "planned_signal_type": "readiness",
        "planned_display_group": "rollback",
    },
    {
        "source_observability_id": "soak_readiness",
        "display_name": "Soak readiness",
        "observation_domain": "soak",
        "planned_signal_source": "future_soak_readiness_probe",
        "planned_signal_type": "readiness",
        "planned_display_group": "soak",
    },
    {
        "source_observability_id": "order_flow_block_state",
        "display_name": "Order flow block state",
        "observation_domain": "order_flow",
        "planned_signal_source": "future_order_flow_gate_probe",
        "planned_signal_type": "block_state",
        "planned_display_group": "execution_safety",
    },
    {
        "source_observability_id": "private_endpoint_block_state",
        "display_name": "Private endpoint block state",
        "observation_domain": "private_endpoint",
        "planned_signal_source": "future_private_endpoint_gate_probe",
        "planned_signal_type": "block_state",
        "planned_display_group": "execution_safety",
    },
    {
        "source_observability_id": "network_block_state",
        "display_name": "Network block state",
        "observation_domain": "network",
        "planned_signal_source": "future_network_gate_probe",
        "planned_signal_type": "block_state",
        "planned_display_group": "execution_safety",
    },
]

BLOCKED_OBSERVABILITY_READ_MODEL_CAPABILITIES: Final[list[str]] = [
    "observability runtime collection",
    "metrics collection",
    "metrics export",
    "log file read",
    "log file write",
    "audit writer",
    "audit export",
    "rollback execution",
    "runtime shutdown",
    "soak runtime",
    "soak scheduler",
    "filesystem I/O",
    "risk runtime enforcement",
    "limit runtime enforcement",
    "kill switch runtime trigger",
    "manual kill switch trigger",
    "automatic kill switch trigger",
    "kill switch state mutation",
    "order generation",
    "order submission",
    "order cancel",
    "order replace",
    "position mutation",
    "private endpoint access",
    "account read",
    "balance read",
    "positions read",
    "orders read",
    "fills read",
    "market data read",
    "adapter instantiation",
    "adapter runtime wiring",
    "runtime loop",
    "scheduler",
    "network I/O",
    "DNS lookup",
    "HTTP request",
    "WebSocket connection",
    "credential read",
    "secret read",
    "secure store read",
    "secure store write",
    "config file read",
    "config discovery",
    "YAML parse",
    "JSON parse",
    "environment variable read",
    "TradingController change",
    "DecisionEnvelope change",
    "QML action dispatch",
    "bridge API changes",
    "PyInstaller/EXE packaging",
]

SOURCE_BOUNDARIES: Final[list[str]] = [
    "no PySide import",
    "no QML import",
    "no runtime loop import",
    "no scheduler import",
    "no TradingController import",
    "no DecisionEnvelope import",
    "no strategy/AI/scoring/recommendation import",
    "no order module import",
    "no live adapter import",
    "no testnet adapter import",
    "no sandbox adapter import",
    "no exchange adapter runtime import",
    "no account module import",
    "no secrets module import",
    "no security store import",
    "no observability runtime import",
    "no logger/exporter runtime import",
    "no metrics exporter import",
    "no rollback runner import",
    "no soak runner import",
    "no filesystem I/O",
    "no log file read",
    "no log file write",
    "no audit write",
    "no audit export",
    "no config file read",
    "no config discovery",
    "no YAML parse",
    "no JSON parse",
    "no environment variable read",
    "no credential read",
    "no credential validation",
    "no secret material handling",
    "no secure store read",
    "no secure store write",
    "no real market data read",
    "no private endpoint access",
    "no account read",
    "no balance read",
    "no positions read",
    "no orders read",
    "no fills read",
    "no order generation",
    "no order submission",
    "no order cancel",
    "no order replace",
    "no position mutation",
    "no network I/O",
    "no DNS lookup",
    "no HTTP request",
    "no WebSocket connection",
    "no QML changes",
    "no bridge API changes",
    "no .bat changes",
    "no app.py changes",
    "no dependency declarations changes",
    "no workflow changes",
]


def _subset(source: dict[str, Any], keys: list[str]) -> dict[str, Any]:
    return {key: source[key] for key in keys}


def _entries() -> list[dict[str, Any]]:
    return [
        {
            "observability_read_model_id": f"observability_read_model_{definition['source_observability_id']}",
            "source_observability_id": definition["source_observability_id"],
            "display_name": definition["display_name"],
            "read_model_classification": "static_observability_read_model_only",
            "observation_domain": definition["observation_domain"],
            "planned_signal_source": definition["planned_signal_source"],
            "planned_signal_type": definition["planned_signal_type"],
            "planned_display_group": definition["planned_display_group"],
            "operator_visibility": "future_read_only_observability",
            "eligible_for_13_5_gate_matrix": True,
            "runtime_collection_allowed_now": False,
            "metrics_export_allowed_now": False,
            "log_file_read_allowed_now": False,
            "log_file_write_allowed_now": False,
            "filesystem_io_allowed_now": False,
            "network_io_allowed_now": False,
            "order_flow_allowed_now": False,
            "private_endpoint_access_allowed_now": False,
            "safe_for_offline_tests": True,
            "notes": "Static planned signal only; no runtime collection, exports, logs, filesystem, network, or execution wiring.",
        }
        for definition in _ENTRY_DEFINITIONS
    ]


def build_preview_observability_read_model() -> dict[str, Any]:
    """Build the static Block K observability read-model payload."""
    block_k_contract = build_preview_observability_audit_rollback_soak_contract()
    entries = _entries()
    ids = [entry["observability_read_model_id"] for entry in entries]

    return {
        "schema_version": PREVIEW_OBSERVABILITY_READ_MODEL_SCHEMA_VERSION,
        "observability_read_model_kind": PREVIEW_OBSERVABILITY_READ_MODEL_KIND,
        "block": BLOCK_ID,
        "step": STEP_ID,
        "observability_read_model_status": OBSERVABILITY_READ_MODEL_STATUS,
        "observability_read_model_decision": OBSERVABILITY_READ_MODEL_DECISION,
        "ready_for_block_k_2": READY_FOR_BLOCK_K_2,
        "next_step": NEXT_STEP,
        "next_step_title": NEXT_STEP_TITLE,
        "block_k_contract_reference": _subset(block_k_contract, _BLOCK_K_CONTRACT_SAFE_KEYS),
        "observability_read_model_scope": {
            "scope_name": "observability_read_model",
            "read_model_only": True,
            "derived_from_block_k_contract_13_0": True,
            **{key: False for key in _FALSE_SCOPE_FLAGS},
            "exe_direction_preserved": True,
        },
        "observability_read_model_entries": entries,
        "default_observability_read_model_selection": {
            "observability_read_model_id": "observability_read_model_runtime_liveness",
            "source_observability_id": "runtime_liveness",
            "reason": "first observability read-model signal; static only, no runtime collection, no exports",
            "runtime_collection_allowed_now": False,
            "metrics_export_allowed_now": False,
        },
        "observability_read_model_summary": {
            "entry_count": 8,
            "default_selection_id": "observability_read_model_runtime_liveness",
            "runtime_collection_enabled_entry_count": 0,
            "metrics_export_enabled_entry_count": 0,
            "log_file_read_enabled_entry_count": 0,
            "log_file_write_enabled_entry_count": 0,
            "filesystem_io_enabled_entry_count": 0,
            "network_enabled_entry_count": 0,
            "order_flow_enabled_entry_count": 0,
            "private_endpoint_enabled_entry_count": 0,
            "offline_safe_entry_count": 8,
            "entries_eligible_for_13_5_gate_matrix": 8,
            "runtime_domain_entry_count": 1,
            "safety_domain_entry_count": 1,
            "audit_domain_entry_count": 1,
            "rollback_domain_entry_count": 1,
            "soak_domain_entry_count": 1,
            "execution_safety_entry_count": 3,
            "safe_to_render_in_future_ui_as_read_only": True,
            "safe_for_runtime_execution_now": False,
            "safe_for_metrics_collection_now": False,
            "safe_for_export_now": False,
        },
        "observability_read_model_matrix": {
            "observability_read_model_ids": ids,
            "runtime_domain_ids": ["observability_read_model_runtime_liveness"],
            "safety_domain_ids": ["observability_read_model_runtime_safety_gate"],
            "audit_domain_ids": ["observability_read_model_audit_envelope_health"],
            "rollback_domain_ids": ["observability_read_model_rollback_readiness"],
            "soak_domain_ids": ["observability_read_model_soak_readiness"],
            "execution_safety_domain_ids": [
                "observability_read_model_order_flow_block_state",
                "observability_read_model_private_endpoint_block_state",
                "observability_read_model_network_block_state",
            ],
            "entries_requiring_13_5_gate_matrix": ids,
            "entries_never_runtime_collected_in_13_1": ids,
            "planned_signal_sources_by_id": {
                entry["observability_read_model_id"]: entry["planned_signal_source"]
                for entry in entries
            },
            "planned_display_groups_by_id": {
                entry["observability_read_model_id"]: entry["planned_display_group"]
                for entry in entries
            },
        },
        "observability_surface_contract": {
            "surface_contract_id": "block_k_observability_read_model_surface_contract",
            "read_model_is_static": True,
            "signals_are_planned_only": True,
            "signals_are_not_collected_now": True,
            "metrics_are_not_exported_now": True,
            "logs_are_not_read_now": True,
            "logs_are_not_written_now": True,
            "filesystem_io_forbidden_now": True,
            "network_io_forbidden_now": True,
            "runtime_collection_requires_future_gate": True,
            "ui_surface_requires_future_qml_gate": True,
        },
        "blocked_observability_read_model_capabilities": BLOCKED_OBSERVABILITY_READ_MODEL_CAPABILITIES,
        "observability_read_model_boundaries": {
            key: True
            for key in [
                "observability_read_model_is_static",
                "observability_read_model_is_derived_from_13_0_contract",
                "observability_read_model_can_feed_13_5_gate_matrix",
                "observability_read_model_cannot_feed_runtime_directly",
                "observability_read_model_cannot_collect_metrics",
                "observability_read_model_cannot_export_metrics",
                "observability_read_model_cannot_read_logs",
                "observability_read_model_cannot_write_logs",
                "observability_read_model_cannot_touch_filesystem",
                "observability_read_model_cannot_write_audit",
                "observability_read_model_cannot_export_audit",
                "observability_read_model_cannot_execute_rollback",
                "observability_read_model_cannot_run_soak",
                "observability_read_model_cannot_enable_runtime",
                "observability_read_model_cannot_enforce_limits",
                "observability_read_model_cannot_trigger_kill_switch",
                "observability_read_model_cannot_mutate_kill_switch_state",
                "observability_read_model_cannot_generate_orders",
                "observability_read_model_cannot_submit_orders",
                "observability_read_model_cannot_cancel_orders",
                "observability_read_model_cannot_replace_orders",
                "observability_read_model_cannot_access_private_endpoints",
                "observability_read_model_cannot_read_account",
                "observability_read_model_balance_read_blocked",
                "observability_read_model_cannot_read_positions",
                "observability_read_model_cannot_read_orders",
                "observability_read_model_cannot_read_fills",
                "observability_read_model_cannot_read_market_data",
                "observability_read_model_cannot_open_network_connection",
                "observability_read_model_cannot_perform_dns_lookup",
                "observability_read_model_cannot_perform_http_request",
                "observability_read_model_cannot_open_websocket",
                "observability_read_model_cannot_read_credentials",
                "observability_read_model_cannot_read_secrets",
                "observability_read_model_cannot_read_secure_store",
                "observability_read_model_cannot_change_qml_or_bridge",
            ]
        },
        "non_activation_evidence": {
            "block_k_contract_13_0_read": True,
            "observability_read_model_built": True,
            **{
                key: False
                for key in [
                    "observability_runtime_started",
                    "metrics_collected",
                    "metrics_exported",
                    "log_file_read",
                    "log_file_written",
                    "audit_writer_started",
                    "audit_exported",
                    "rollback_executed",
                    "runtime_shutdown_executed",
                    "soak_runtime_started",
                    "soak_scheduler_started",
                    "filesystem_io_performed",
                    "risk_runtime_enforcement_started",
                    "limit_runtime_enforcement_started",
                    "kill_switch_runtime_trigger_enabled",
                    "manual_kill_switch_trigger_enabled",
                    "automatic_kill_switch_trigger_enabled",
                    "kill_switch_state_mutated",
                    "order_generated",
                    "order_submitted",
                    "order_cancelled",
                    "order_replaced",
                    "position_mutated",
                    "private_endpoint_accessed",
                    "account_read_performed",
                    "balance_read_performed",
                    "positions_read_performed",
                    "orders_read_performed",
                    "fills_read_performed",
                    "market_data_read_performed",
                    "adapter_instantiated",
                    "adapter_wired_to_runtime",
                    "runtime_started",
                    "scheduler_started",
                    "network_io_performed",
                    "dns_lookup_performed",
                    "http_request_performed",
                    "websocket_opened",
                    "credentials_read",
                    "secrets_read",
                    "secure_store_read",
                    "secure_store_write",
                    "config_files_read",
                    "config_discovery_performed",
                    "yaml_parsed",
                    "json_parsed",
                    "environment_variables_read",
                    "trading_controller_touched",
                    "decision_envelope_touched",
                    "qml_changed",
                    "bridge_api_changed",
                ]
            },
        },
        "source_boundaries": SOURCE_BOUNDARIES,
        "future_steps": [
            "functional_preview_13_2_audit_envelope_read_model",
            "functional_preview_13_3_rollback_read_model",
            "functional_preview_13_4_soak_read_model",
            "functional_preview_13_5_observability_audit_rollback_soak_gate_matrix",
            "functional_preview_13_6_block_k_closure_audit",
        ],
        "status": STATUS,
    }
