"""Narrow, platform-neutral contracts implemented outside the trading core."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Protocol


@dataclass(frozen=True)
class DeploymentPaths:
    """OS-resolved locations; callers must not construct platform paths."""

    install: Path
    state: Path
    configuration: Path
    logs: Path
    runtime: Path
    update_staging: Path
    gui_user_state: Path | None


class ServiceManager(Protocol):
    def install(self) -> None: ...
    def remove(self) -> None: ...
    def start(self) -> None: ...
    def stop(self, *, graceful_timeout_seconds: int) -> None: ...
    def restart(self) -> None: ...
    def qualify_crash_restart_and_autostart(self) -> None: ...


class LocalSecurityBoundary(Protocol):
    def paths(self) -> DeploymentPaths: ...
    def service_identity(self) -> str: ...
    def local_ipc_endpoint(self) -> str: ...
    def qualify_permissions(self) -> None: ...
    def qualify_authenticated_principal(self) -> None: ...


class ProcessSupervisor(Protocol):
    def notify_shutdown(self) -> None: ...
    def terminate_process_tree(self, *, timeout_seconds: int) -> None: ...


class UpdateExecutor(Protocol):
    def quiesce_and_handoff(self, staged_payload: Path) -> None: ...
    def restart_and_report_evidence(self) -> None: ...

