# Konfiguracja bazowa etapu 1 – wartości placeholder do dalszego dostosowania.

risk_profiles:
  conservative:
    max_daily_loss_pct: 0.01
    max_position_pct: 0.03
    target_volatility: 0.07
    max_leverage: 2.0
    stop_loss_atr_multiple: 1.0
    max_open_positions: 3
    hard_drawdown_pct: 0.05
  balanced:
    max_daily_loss_pct: 0.015
    max_position_pct: 0.05
    target_volatility: 0.11
    max_leverage: 3.0
    stop_loss_atr_multiple: 1.5
    max_open_positions: 5
    hard_drawdown_pct: 0.10
  aggressive:
    max_daily_loss_pct: 0.03
    max_position_pct: 0.10
    target_volatility: 0.19
    max_leverage: 5.0
    stop_loss_atr_multiple: 2.0
    max_open_positions: 10
    hard_drawdown_pct: 0.20
  manual:
    max_daily_loss_pct: 0.0
    max_position_pct: 0.0
    target_volatility: 0.0
    max_leverage: 0.0
    stop_loss_atr_multiple: 0.0
    max_open_positions: 0
    hard_drawdown_pct: 0.0

runtime:
  controllers:
    daily_trend_core:
      tick_seconds: 86400
      interval: 1d

strategies:
  core_daily_trend:
    engine: daily_trend_momentum
    parameters:
      fast_ma: 25
      slow_ma: 100
      breakout_lookback: 55
      momentum_window: 20
      atr_window: 14
      atr_multiplier: 2.0
      min_trend_strength: 0.005
      min_momentum: 0.001

instrument_universes:
  core_multi_exchange:
    description: >-
      Bazowy koszyk instrumentów dostępny na Binance, Krakenie i Zondzie.
      Zawiera pary BTC i ETH do USDT oraz EUR, sześć głównych altów oraz
      fiatowe pary na Zondzie wykorzystywane do testów integracyjnych.
    instruments:
      BTC_USDT:
        base_asset: BTC
        quote_asset: USDT
        categories: [core, btc, stable]
        exchanges:
          binance_spot: BTCUSDT
          binance_futures: BTCUSDT
          kraken_spot: XBTUSDT
          kraken_futures: pi_xbtusd
          zonda_spot: BTC-USDT
        backfill:
          - interval: 1d
            lookback_days: 3650
          - interval: 1h
            lookback_days: 1095
      ETH_USDT:
        base_asset: ETH
        quote_asset: USDT
        categories: [core, eth, stable]
        exchanges:
          binance_spot: ETHUSDT
          binance_futures: ETHUSDT
          kraken_spot: ETHUSDT
          kraken_futures: pi_ethusd
          zonda_spot: ETH-USDT
        backfill:
          - interval: 1d
            lookback_days: 3650
          - interval: 1h
            lookback_days: 1095
      BTC_EUR:
        base_asset: BTC
        quote_asset: EUR
        categories: [core, btc, fiat]
        exchanges:
          binance_spot: BTCEUR
          kraken_spot: XBTEUR
          kraken_futures: pi_xbteur
          zonda_spot: BTC-EUR
        backfill:
          - interval: 1d
            lookback_days: 3650
          - interval: 1h
            lookback_days: 730
      ETH_EUR:
        base_asset: ETH
        quote_asset: EUR
        categories: [core, eth, fiat]
        exchanges:
          binance_spot: ETHEUR
          kraken_spot: ETHEUR
          kraken_futures: pi_etheur
          zonda_spot: ETH-EUR
        backfill:
          - interval: 1d
            lookback_days: 3650
          - interval: 1h
            lookback_days: 730
      SOL_USDT:
        base_asset: SOL
        quote_asset: USDT
        categories: [alt, high_liquidity]
        exchanges:
          binance_spot: SOLUSDT
          binance_futures: SOLUSDT
          kraken_spot: SOLUSDT
        backfill:
          - interval: 1d
            lookback_days: 1825
          - interval: 1h
            lookback_days: 730
      BNB_USDT:
        base_asset: BNB
        quote_asset: USDT
        categories: [alt, high_liquidity]
        exchanges:
          binance_spot: BNBUSDT
          binance_futures: BNBUSDT
        backfill:
          - interval: 1d
            lookback_days: 1825
          - interval: 1h
            lookback_days: 730
      XRP_USDT:
        base_asset: XRP
        quote_asset: USDT
        categories: [alt, high_liquidity]
        exchanges:
          binance_spot: XRPUSDT
          kraken_spot: XRPUSDT
        backfill:
          - interval: 1d
            lookback_days: 1825
          - interval: 1h
            lookback_days: 730
      ADA_USDT:
        base_asset: ADA
        quote_asset: USDT
        categories: [alt, high_liquidity]
        exchanges:
          binance_spot: ADAUSDT
          binance_futures: ADAUSDT
          kraken_spot: ADAUSDT
        backfill:
          - interval: 1d
            lookback_days: 1825
          - interval: 1h
            lookback_days: 730
      LTC_USDT:
        base_asset: LTC
        quote_asset: USDT
        categories: [alt, high_liquidity]
        exchanges:
          binance_spot: LTCUSDT
          binance_futures: LTCUSDT
          kraken_spot: LTCUSDT
        backfill:
          - interval: 1d
            lookback_days: 1825
          - interval: 1h
            lookback_days: 730
      MATIC_USDT:
        base_asset: MATIC
        quote_asset: USDT
        categories: [alt, high_liquidity]
        exchanges:
          binance_spot: MATICUSDT
          binance_futures: MATICUSDT
          kraken_spot: MATICUSDT
        backfill:
          - interval: 1d
            lookback_days: 1825
          - interval: 1h
            lookback_days: 730
      BTC_PLN:
        base_asset: BTC
        quote_asset: PLN
        categories: [fiat, zonda]
        exchanges:
          zonda_spot: BTC-PLN
        backfill:
          - interval: 1d
            lookback_days: 3650
      ETH_PLN:
        base_asset: ETH
        quote_asset: PLN
        categories: [fiat, zonda]
        exchanges:
          zonda_spot: ETH-PLN
        backfill:
          - interval: 1d
            lookback_days: 3650

environments:
  binance_paper:
    exchange: binance_spot
    environment: paper
    keychain_key: binance_paper_trading
    credential_purpose: trading
    data_cache_path: ./var/data/binance_paper
    risk_profile: balanced
    alert_channels: ["telegram:primary", "email:ops"]
    ip_allowlist: []
    instrument_universe: core_multi_exchange

  binance_live:
    exchange: binance_spot
    environment: live
    keychain_key: binance_live_trading
    data_cache_path: ./var/data/binance_live
    risk_profile: conservative
    alert_channels: ["telegram:primary", "sms:orange_local", "email:ops"]
    ip_allowlist: []
    instrument_universe: core_multi_exchange

  binance_futures_paper:
    exchange: binance_futures
    environment: paper
    keychain_key: binance_futures_paper_trading
    data_cache_path: ./var/data/binance_futures_paper
    risk_profile: balanced
    alert_channels: ["telegram:primary", "email:ops"]
    ip_allowlist: []
    instrument_universe: core_multi_exchange

  binance_futures_live:
    exchange: binance_futures
    environment: live
    keychain_key: binance_futures_live_trading
    data_cache_path: ./var/data/binance_futures_live
    risk_profile: conservative
    alert_channels: ["telegram:primary", "sms:orange_local", "email:ops"]
    ip_allowlist: []
    instrument_universe: core_multi_exchange

  kraken_paper:
    exchange: kraken_spot
    environment: paper
    keychain_key: kraken_paper_trading
    data_cache_path: ./var/data/kraken_paper
    risk_profile: balanced
    alert_channels: ["telegram:primary", "email:ops"]
    ip_allowlist: []
    instrument_universe: core_multi_exchange

  kraken_live:
    exchange: kraken_spot
    environment: live
    keychain_key: kraken_live_trading
    data_cache_path: ./var/data/kraken_live
    risk_profile: conservative
    alert_channels: ["telegram:primary", "sms:orange_local", "email:ops"]
    ip_allowlist: []
    instrument_universe: core_multi_exchange

  kraken_futures_paper:
    exchange: kraken_futures
    environment: paper
    keychain_key: kraken_futures_paper_trading
    data_cache_path: ./var/data/kraken_futures_paper
    risk_profile: balanced
    alert_channels: ["telegram:primary", "email:ops"]
    ip_allowlist: []
    instrument_universe: core_multi_exchange

  kraken_futures_live:
    exchange: kraken_futures
    environment: live
    keychain_key: kraken_futures_live_trading
    data_cache_path: ./var/data/kraken_futures_live
    risk_profile: conservative
    alert_channels: ["telegram:primary", "sms:orange_local", "email:ops"]
    ip_allowlist: []
    instrument_universe: core_multi_exchange

  zonda_paper:
    exchange: zonda_spot
    environment: paper
    keychain_key: zonda_paper_trading
    data_cache_path: ./var/data/zonda_paper
    risk_profile: conservative
    alert_channels: ["telegram:primary"]
    ip_allowlist: []
    instrument_universe: core_multi_exchange

  zonda_live:
    exchange: zonda_spot
    environment: live
    keychain_key: zonda_live_trading
    data_cache_path: ./var/data/zonda_live
    risk_profile: conservative
    alert_channels: ["telegram:primary", "sms:nova_is", "email:ops"]
    ip_allowlist: []
    instrument_universe: core_multi_exchange

reporting:
  daily_report_time_utc: "21:00"
  weekly_report_day: "sunday"
  retention_months: "24"

alerts:
  telegram_channels:
    primary:
      chat_id: "123456789"
      token_secret: telegram_primary_token
      parse_mode: MarkdownV2
  signal_channels:
    primary_signal:
      service_url: https://signal-gateway.local
      sender_number: "+48500100999"
      recipients:
        - "+48555111222"
      credential_secret: signal_cli_token
      verify_tls: true
  whatsapp_channels:
    primary_whatsapp:
      phone_number_id: "10987654321"
      recipients:
        - "48555111222"
      token_secret: whatsapp_primary_token
      api_base_url: https://graph.facebook.com
      api_version: v16.0
  messenger_channels:
    ops_messenger:
      page_id: "1357924680"
      recipients:
        - "2468013579"
      token_secret: messenger_page_token
      api_base_url: https://graph.facebook.com
      api_version: v16.0
  email_channels:
    ops:
      host: smtp.example.com
      port: 587
      from_address: bot@example.com
      recipients:
        - ops@example.com
      credential_secret: smtp_ops_credentials
      use_tls: true
  sms_providers:
    orange_local:
      provider: orange_pl
      api_base_url: https://api.orange.pl/sms/v1
      from_number: "+48500100100"
      recipients: ["+48555111222"]
      allow_alphanumeric_sender: true
      sender_id: "BOT-ORANGE"
      credential_key: orange_sms_credentials
    tmobile_local:
      provider: tmobile_pl
      api_base_url: https://api.t-mobile.pl/sms/v1
      from_number: "+48500100101"
      recipients: ["+48555111333"]
      allow_alphanumeric_sender: true
      sender_id: "BOT-TMOBILE"
      credential_key: tmobile_sms_credentials
    plus_local:
      provider: plus_pl
      api_base_url: https://api.plus.pl/messaging/v1
      from_number: "+48500100102"
      recipients: ["+48555111444"]
      allow_alphanumeric_sender: false
      credential_key: plus_sms_credentials
    play_local:
      provider: play_pl
      api_base_url: https://api.play.pl/sms/v1
      from_number: "+48500100103"
      recipients: ["+48555111555"]
      allow_alphanumeric_sender: true
      sender_id: "BOT-PLAY"
      credential_key: play_sms_credentials
    nova_is:
      provider: nova_is
      api_base_url: https://api.nova.is/sms/v1
      from_number: "+3546001001"
      recipients: ["+3546601234"]
      allow_alphanumeric_sender: true
      sender_id: "BOT-NOVA"
      credential_key: nova_sms_credentials
