from typing import Any, Dict, List, Optional

class ExchangeAdapter:
    def fetch_ohlcv(self, symbol: str, timeframe: str = ..., limit: int = ...) -> Optional[List[List[float]]]: ...
    def fetch_ticker(self, symbol: str) -> Optional[Dict[str, Any]]: ...
    def fetch_order_book(self, symbol: str, limit: int = ...) -> Optional[Dict[str, Any]]: ...
    def create_order(self, *args: Any, **kwargs: Any) -> Dict[str, Any]: ...
