# Konfiguracja przykładowa dla powłoki Qt/QML korzystającej z trading stub server
endpoint: 127.0.0.1:50061

grpc:
  tls:
    enabled: true
    root_cert: secrets/mtls/ca/ca.pem
    client_cert: secrets/mtls/client/client.crt
    client_key: secrets/mtls/client/client.key
    server_name: core-daemon.internal
    pinned_sha256: ""          # opcjonalne pinning certyfikatu serwera (SHA-256 SPKI)
    require_client_auth: true  # mamy cert klienta, więc włączone

# Wsteczna kompatybilność (starsze buildy mogą czytać te klucze)
tls:
  enabled: true
  root_certificate: secrets/mtls/ca/ca.pem
  client_certificate: secrets/mtls/client/client.crt
  client_key: secrets/mtls/client/client.key
  target_name_override: core-daemon.internal

instrument:
  exchange: BINANCE
  symbol: BTC/USDT
  venue_symbol: BTCUSDT
  quote_currency: USDT
  base_currency: BTC
  granularity: PT1M

performance_guard:
  fps_target: 120
  reduce_motion_after_seconds: 0.6
  jank_threshold_ms: 12.0
  overlays:
    max_overlays: 4
    disable_secondary_when_fps_below: 55
  # Wsteczna kompatybilność (preferuj performance_guard.overlays.max_overlays)
  max_overlay_count: 4

telemetry:
  metrics_endpoint: 127.0.0.1:50061
  metrics_tag: desktop-shell-dev
  metrics_auth_token: dev-secret

history_limit: 800
maximum_samples: 12000
