# Konfiguracja przykładowa dla powłoki Qt/QML korzystającej z trading stub server
endpoint: 127.0.0.1:50061

transport:
  mode: grpc               # możliwe wartości: grpc, in-process (dla trybu lokalnego bez gRPC)
  dataset: data/sample_ohlcv/trend.csv  # wymagane wyłącznie w trybie in-process – ścieżka do CSV/pipe musi istnieć

grpc:
  tls:
    enabled: true
    root_cert: secrets/mtls/core-oem-ca.pem          # plik musi być dostępny lokalnie
    client_cert: secrets/mtls/core-oem-client.pem    # wymagane przy mTLS – walidowane przy starcie UI
    client_key: secrets/mtls/core-oem-client-key.pem # wymagane przy mTLS – walidowane przy starcie UI
    server_name: core-daemon.internal
    pinned_sha256: ""          # opcjonalne – pinning certyfikatu serwera (SHA-256 SPKI)
    require_client_auth: true  # mamy cert klienta, więc włączone

# Wsteczna kompatybilność (starsze buildy czytają te klucze)
tls:
  enabled: true
  root_certificate: secrets/mtls/core-oem-ca.pem
  client_certificate: secrets/mtls/core-oem-client.pem
  client_key: secrets/mtls/core-oem-client-key.pem

# Legacy override dla SNI / SAN serwera (nowe buildy używają grpc.tls.server_name)
target_name_override: core-daemon.internal

instrument:
  exchange: BINANCE
  symbol: BTC/USDT
  venue_symbol: BTCUSDT
  quote_currency: USDT
  base_currency: BTC
  granularity: PT1M

performance_guard:
  fps_target: 120
  reduce_motion_after_seconds: 0.6
  jank_threshold_ms: 12.0
  overlays:
    max_overlays: 4
    disable_secondary_when_fps_below: 55
  # Wsteczna kompatybilność (preferuj performance_guard.overlays.max_overlays)
  max_overlay_count: 4

telemetry:
  metrics_endpoint: 127.0.0.1:50061  # w trybie in-process ustaw 'in-process'
  metrics_tag: desktop-shell-dev
  metrics_auth_token: dev-secret

# Tryb w pełni lokalny bez gRPC (in-process):
# transport:
#   mode: in-process
#   dataset: data/sample_ohlcv/trend.csv
# telemetry:
#   metrics_endpoint: in-process
# health:
#   endpoint: in-process

history_limit: 800
maximum_samples: 12000
