#!/usr/bin/env bash
set -euo pipefail

python scripts/ci/require_python311.py

lock=deploy/packaging/requirements-desktop.lock
tmp="${lock}.tmp"
trap 'rm -f "$tmp"' EXIT
# pip-compile intentionally updates the checked-in lock in place so unchanged
# transitive pins remain stable; only the reviewed security pins below move.
python -m piptools compile pyproject.toml deploy/packaging/requirements-desktop.txt \
  --extra desktop \
  --output-file "$lock" --no-header --allow-unsafe \
  --resolver backtracking --strip-extras \
  --upgrade-package click==8.3.3 \
  --upgrade-package GitPython==3.1.60 \
  --upgrade-package Pygments==2.20.0 \
  --upgrade-package idna==3.15 \
  --upgrade-package requests==2.33.0 \
  --upgrade-package urllib3==2.8.0
{
  printf '%s\n' \
    '# Generated by scripts/compile_desktop_lock.sh.' \
    '# Python 3.11 is required; that script is the canonical generation authority.'
  cat "$lock"
} > "$tmp"
mv "$tmp" "$lock"
