groups:
  - name: multi_strategy_runtime
    interval: 30s
    rules:
      - alert: MultiStrategySchedulerLatencyHigh
        expr: max_over_time(bot_core_multi_strategy_latency_ms[2m]) > 250
        for: 2m
        labels:
          severity: warning
          team: trading-ops
        annotations:
          summary: "Scheduler latency przekracza 250 ms"
          description: |
            Opóźnienie pętli harmonogramu multi-strategy utrzymuje się powyżej 250 ms.
            Sprawdź stan scheduler-a (`scripts/run_multi_strategy_scheduler.py --dry-run`) oraz telemetrię.
      - alert: MultiStrategySchedulerLatencyCritical
        expr: max_over_time(bot_core_multi_strategy_latency_ms[5m]) > 320
        for: 1m
        labels:
          severity: critical
          team: trading-ops
        annotations:
          summary: "Krytyczne opóźnienie scheduler-a (>320 ms)"
          description: |
            Scheduler multi-strategy przekroczył 320 ms opóźnienia. Rozważ przełączenie na tryb manualny
            i wykonanie procedury rollbacku strategii.
      - alert: MultiStrategyRiskExposureDeviation
        expr: avg_over_time(bot_core_multi_strategy_allocation_error_pct[10m]) > 20
        for: 5m
        labels:
          severity: warning
          team: risk
        annotations:
          summary: "Odchylenie ekspozycji strategii przekracza 20%"
          description: |
            Średni błąd alokacji względem profilu ryzyka przekracza 20%. Zidentyfikuj strategię o najwyższym błędzie
            i potwierdź z Risk Engine korekty limitów.
      - alert: MultiStrategyPnlDrawdown
        expr: min_over_time(bot_core_multi_strategy_pnl_drawdown_pct[30m]) < -4
        for: 10m
        labels:
          severity: critical
          team: trading-ops
        annotations:
          summary: "Drawdown PnL przekracza -4%"
          description: |
            Zanotowano drawdown PnL poniżej -4% w oknie 30 minut. Wymagane jest ręczne potwierdzenie kontynuacji
            lub aktywacja procedury awaryjnego wyłączenia strategii.
      - alert: MultiStrategySecondaryDelay
        expr: max_over_time(bot_core_multi_strategy_secondary_delay_ms[5m]) > 450
        for: 3m
        labels:
          severity: warning
          team: trading-ops
        annotations:
          summary: "Opóźnienie giełdy secondary przekracza 450 ms"
          description: |
            Zauważono wzrost opóźnień danych z giełdy secondary powyżej 450 ms. Zweryfikuj łączność (VPN/testnet)
            oraz dostępność adapterów arbitrażowych.
