name: Cleanup old artifacts

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  actions: write

jobs:
  delete-old-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Delete artifacts older than 7 days
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '7 days'
          skip-tags: true
